// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/swarmkit/api/dispatcher.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	raftselector "github.com/moby/swarmkit/v2/manager/raftselector"
	_ "github.com/moby/swarmkit/v2/protobuf/plugin"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AssignmentChange_AssignmentAction int32

const (
	AssignmentChange_AssignmentActionUpdate AssignmentChange_AssignmentAction = 0
	AssignmentChange_AssignmentActionRemove AssignmentChange_AssignmentAction = 1
)

var AssignmentChange_AssignmentAction_name = map[int32]string{
	0: "UPDATE",
	1: "REMOVE",
}

var AssignmentChange_AssignmentAction_value = map[string]int32{
	"UPDATE": 0,
	"REMOVE": 1,
}

func (x AssignmentChange_AssignmentAction) String() string { _ = "STUB: not implemented"; return "" }

func (AssignmentChange_AssignmentAction) EnumDescriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssignmentType specifies whether this assignment message carries
// the full state, or is an update to an existing state.
type AssignmentsMessage_Type int32

const (
	AssignmentsMessage_COMPLETE    AssignmentsMessage_Type = 0
	AssignmentsMessage_INCREMENTAL AssignmentsMessage_Type = 1
)

var AssignmentsMessage_Type_name = map[int32]string{
	0: "COMPLETE",
	1: "INCREMENTAL",
}

var AssignmentsMessage_Type_value = map[string]int32{
	"COMPLETE":    0,
	"INCREMENTAL": 1,
}

func (x AssignmentsMessage_Type) String() string { _ = "STUB: not implemented"; return "" }

func (AssignmentsMessage_Type) EnumDescriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SessionRequest starts a session.
type SessionRequest struct {
	Description *NodeDescription `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// SessionID can be provided to attempt resuming an existing session. If the
	// SessionID is empty or invalid, a new SessionID will be assigned.
	//
	// See SessionMessage.SessionID for details.
	SessionID string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (m *SessionRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*SessionRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SessionRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SessionRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SessionRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SessionRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SessionRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

// SessionMessage instructs an agent on various actions as part of the current
// session. An agent should act immediately on the contents.
type SessionMessage struct {
	// SessionID is allocated after a successful registration. It should be
	// used on all RPC calls after registration. A dispatcher may choose to
	// change the SessionID, at which time an agent must re-register and obtain
	// a new one.
	//
	// All Dispatcher calls after register should include the SessionID. If the
	// Dispatcher so chooses, it may reject the call with an InvalidArgument
	// error code, at which time the agent should call Register to start a new
	// session.
	//
	// As a rule, once an agent has a SessionID, it should never save it to
	// disk or try to otherwise reuse. If the agent loses its SessionID, it
	// must start a new session through a call to Register. A Dispatcher may
	// choose to reuse the SessionID, if it sees fit, but it is not advised.
	//
	// The actual implementation of the SessionID is Dispatcher specific and
	// should be treated as opaque by agents.
	//
	// From a Dispatcher perspective, there are many ways to use the SessionID
	// to ensure uniqueness of a set of client RPC calls. One method is to keep
	// the SessionID unique to every call to Register in a single Dispatcher
	// instance. This ensures that the SessionID represents the unique
	// session from a single Agent to Manager. If the Agent restarts, we
	// allocate a new session, since the restarted Agent is not aware of the
	// new SessionID.
	//
	// The most compelling use case is to support duplicate node detection. If
	// one clones a virtual machine, including certificate material, two nodes
	// may end up with the same identity. This can also happen if two identical
	// agent processes are coming from the same node. If the SessionID is
	// replicated through the cluster, we can immediately detect the condition
	// and address it.
	//
	// Extending from the case above, we can actually detect a compromised
	// identity. Coupled with provisions to rebuild node identity, we can ban
	// the compromised node identity and have the nodes re-authenticate and
	// build a new identity. At this time, an administrator can then
	// re-authorize the compromised nodes, if it was a mistake or ensure that a
	// misbehaved node can no longer connect to the cluster.
	//
	// We considered placing this field in a GRPC header. Because this is a
	// critical feature of the protocol, we thought it should be represented
	// directly in the RPC message set.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Node identifies the registering node.
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Managers provides a weight list of alternative dispatchers
	Managers []*WeightedPeer `protobuf:"bytes,3,rep,name=managers,proto3" json:"managers,omitempty"`
	// Symmetric encryption key distributed by the lead manager. Used by agents
	// for securing network bootstrapping and communication.
	NetworkBootstrapKeys []*EncryptionKey `protobuf:"bytes,4,rep,name=network_bootstrap_keys,json=networkBootstrapKeys,proto3" json:"network_bootstrap_keys,omitempty"`
	// Which root certificates to trust
	RootCA []byte `protobuf:"bytes,5,opt,name=RootCA,proto3" json:"RootCA,omitempty"`
}

func (m *SessionMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (*SessionMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SessionMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SessionMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SessionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SessionMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SessionMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SessionMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SessionMessage proto.InternalMessageInfo

// HeartbeatRequest provides identifying properties for a single heartbeat.
type HeartbeatRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (m *HeartbeatRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*HeartbeatRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HeartbeatRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HeartbeatRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HeartbeatRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HeartbeatRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

type HeartbeatResponse struct {
	// Period is the duration to wait before sending the next heartbeat.
	// Well-behaved agents should update this on every heartbeat round trip.
	Period time.Duration `protobuf:"bytes,1,opt,name=period,proto3,stdduration" json:"period"`
}

func (m *HeartbeatResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (*HeartbeatResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HeartbeatResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HeartbeatResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HeartbeatResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HeartbeatResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

type UpdateTaskStatusRequest struct {
	// Tasks should contain all statuses for running tasks. Only the status
	// field must be set. The spec is not required.
	SessionID string                                      `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Updates   []*UpdateTaskStatusRequest_TaskStatusUpdate `protobuf:"bytes,3,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (m *UpdateTaskStatusRequest) Reset()      { _ = "STUB: not implemented"; return }
func (*UpdateTaskStatusRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *UpdateTaskStatusRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *UpdateTaskStatusRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_UpdateTaskStatusRequest proto.InternalMessageInfo

type UpdateTaskStatusRequest_TaskStatusUpdate struct {
	TaskID string      `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status *TaskStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) Reset() { _ = "STUB: not implemented"; return }

func (*UpdateTaskStatusRequest_TaskStatusUpdate) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*UpdateTaskStatusRequest_TaskStatusUpdate) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) XXX_Size() int {
	_ = "STUB: not implemented"
	return 0
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_UpdateTaskStatusRequest_TaskStatusUpdate proto.InternalMessageInfo

type UpdateTaskStatusResponse struct {
}

func (m *UpdateTaskStatusResponse) Reset()      { _ = "STUB: not implemented"; return }
func (*UpdateTaskStatusResponse) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *UpdateTaskStatusResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *UpdateTaskStatusResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_UpdateTaskStatusResponse proto.InternalMessageInfo

type UpdateVolumeStatusRequest struct {
	SessionID string                                          `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Updates   []*UpdateVolumeStatusRequest_VolumeStatusUpdate `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (m *UpdateVolumeStatusRequest) Reset()      { _ = "STUB: not implemented"; return }
func (*UpdateVolumeStatusRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*UpdateVolumeStatusRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *UpdateVolumeStatusRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *UpdateVolumeStatusRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_UpdateVolumeStatusRequest proto.InternalMessageInfo

type UpdateVolumeStatusRequest_VolumeStatusUpdate struct {
	// ID is the ID of the volume being updated. This is the Swarmkit ID,
	// not the CSI VolumeID.
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unpublished is set to true when the volume is affirmatively
	// unpublished on the Node side. We don't need to report that a Volume
	// is published on the the node; as soon as the Volume is assigned to
	// the Node, we must assume that it has been published until informed
	// otherwise.
	//
	// Further, the Node must not send unpublished = true unless it will
	// definitely no longer attempt to call NodePublishVolume.
	Unpublished bool `protobuf:"varint,2,opt,name=unpublished,proto3" json:"unpublished,omitempty"`
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) Reset() { _ = "STUB: not implemented"; return }

func (*UpdateVolumeStatusRequest_VolumeStatusUpdate) ProtoMessage() {
	_ = "STUB: not implemented"
	return
}
func (*UpdateVolumeStatusRequest_VolumeStatusUpdate) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) XXX_Size() int {
	_ = "STUB: not implemented"
	return 0
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_UpdateVolumeStatusRequest_VolumeStatusUpdate proto.InternalMessageInfo

type UpdateVolumeStatusResponse struct {
}

func (m *UpdateVolumeStatusResponse) Reset()      { _ = "STUB: not implemented"; return }
func (*UpdateVolumeStatusResponse) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*UpdateVolumeStatusResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *UpdateVolumeStatusResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *UpdateVolumeStatusResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_UpdateVolumeStatusResponse proto.InternalMessageInfo

type TasksRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (m *TasksRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*TasksRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TasksRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TasksRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TasksRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TasksRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TasksRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TasksRequest proto.InternalMessageInfo

type TasksMessage struct {
	// Tasks is the set of tasks that should be running on the node.
	// Tasks outside of this set running on the node should be terminated.
	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (m *TasksMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (*TasksMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TasksMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TasksMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TasksMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TasksMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TasksMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TasksMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TasksMessage proto.InternalMessageInfo

type AssignmentsRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (m *AssignmentsRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*AssignmentsRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AssignmentsRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AssignmentsRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AssignmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AssignmentsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AssignmentsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AssignmentsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AssignmentsRequest proto.InternalMessageInfo

type Assignment struct {
	// Types that are valid to be assigned to Item:
	//	*Assignment_Task
	//	*Assignment_Secret
	//	*Assignment_Config
	//	*Assignment_Volume
	Item isAssignment_Item `protobuf_oneof:"item"`
}

func (m *Assignment) Reset()                    { _ = "STUB: not implemented"; return }
func (*Assignment) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Assignment) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Assignment) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Assignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Assignment) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Assignment) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Assignment) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Assignment proto.InternalMessageInfo

type isAssignment_Item interface {
	isAssignment_Item()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Assignment_Task struct {
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3,oneof" json:"task,omitempty"`
}
type Assignment_Secret struct {
	Secret *Secret `protobuf:"bytes,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
}
type Assignment_Config struct {
	Config *Config `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
}
type Assignment_Volume struct {
	Volume *VolumeAssignment `protobuf:"bytes,4,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
}

func (*Assignment_Task) isAssignment_Item()   { _ = "STUB: not implemented"; return }
func (*Assignment_Secret) isAssignment_Item() { _ = "STUB: not implemented"; return }
func (*Assignment_Config) isAssignment_Item() { _ = "STUB: not implemented"; return }
func (*Assignment_Volume) isAssignment_Item() { _ = "STUB: not implemented"; return }

func (m *Assignment) GetItem() isAssignment_Item {
	_ = "STUB: not implemented"
	return *new(isAssignment_Item)
}

func (m *Assignment) GetTask() *Task { _ = "STUB: not implemented"; return nil }

func (m *Assignment) GetSecret() *Secret { _ = "STUB: not implemented"; return nil }

func (m *Assignment) GetConfig() *Config { _ = "STUB: not implemented"; return nil }

func (m *Assignment) GetVolume() *VolumeAssignment { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Assignment) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

type AssignmentChange struct {
	Assignment *Assignment                       `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Action     AssignmentChange_AssignmentAction `protobuf:"varint,2,opt,name=action,proto3,enum=docker.swarmkit.v1.AssignmentChange_AssignmentAction" json:"action,omitempty"`
}

func (m *AssignmentChange) Reset()                    { _ = "STUB: not implemented"; return }
func (*AssignmentChange) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AssignmentChange) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AssignmentChange) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AssignmentChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AssignmentChange) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AssignmentChange) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AssignmentChange) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AssignmentChange proto.InternalMessageInfo

type AssignmentsMessage struct {
	Type AssignmentsMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=docker.swarmkit.v1.AssignmentsMessage_Type" json:"type,omitempty"`
	// AppliesTo references the previous ResultsIn value, to chain
	// incremental updates together. For the first update in a stream,
	// AppliesTo is empty.  If AppliesTo does not match the previously
	// received ResultsIn, the consumer of the stream should start a new
	// Assignments stream to re-sync.
	AppliesTo string `protobuf:"bytes,2,opt,name=applies_to,json=appliesTo,proto3" json:"applies_to,omitempty"`
	// ResultsIn identifies the result of this assignments message, to
	// match against the next message's AppliesTo value and protect
	// against missed messages.
	ResultsIn string `protobuf:"bytes,3,opt,name=results_in,json=resultsIn,proto3" json:"results_in,omitempty"`
	// AssignmentChange is a set of changes to apply on this node.
	Changes []*AssignmentChange `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (m *AssignmentsMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (*AssignmentsMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AssignmentsMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AssignmentsMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AssignmentsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AssignmentsMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AssignmentsMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AssignmentsMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AssignmentsMessage proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("docker.swarmkit.v1.AssignmentChange_AssignmentAction", AssignmentChange_AssignmentAction_name, AssignmentChange_AssignmentAction_value)
	proto.RegisterEnum("docker.swarmkit.v1.AssignmentsMessage_Type", AssignmentsMessage_Type_name, AssignmentsMessage_Type_value)
	proto.RegisterType((*SessionRequest)(nil), "docker.swarmkit.v1.SessionRequest")
	proto.RegisterType((*SessionMessage)(nil), "docker.swarmkit.v1.SessionMessage")
	proto.RegisterType((*HeartbeatRequest)(nil), "docker.swarmkit.v1.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "docker.swarmkit.v1.HeartbeatResponse")
	proto.RegisterType((*UpdateTaskStatusRequest)(nil), "docker.swarmkit.v1.UpdateTaskStatusRequest")
	proto.RegisterType((*UpdateTaskStatusRequest_TaskStatusUpdate)(nil), "docker.swarmkit.v1.UpdateTaskStatusRequest.TaskStatusUpdate")
	proto.RegisterType((*UpdateTaskStatusResponse)(nil), "docker.swarmkit.v1.UpdateTaskStatusResponse")
	proto.RegisterType((*UpdateVolumeStatusRequest)(nil), "docker.swarmkit.v1.UpdateVolumeStatusRequest")
	proto.RegisterType((*UpdateVolumeStatusRequest_VolumeStatusUpdate)(nil), "docker.swarmkit.v1.UpdateVolumeStatusRequest.VolumeStatusUpdate")
	proto.RegisterType((*UpdateVolumeStatusResponse)(nil), "docker.swarmkit.v1.UpdateVolumeStatusResponse")
	proto.RegisterType((*TasksRequest)(nil), "docker.swarmkit.v1.TasksRequest")
	proto.RegisterType((*TasksMessage)(nil), "docker.swarmkit.v1.TasksMessage")
	proto.RegisterType((*AssignmentsRequest)(nil), "docker.swarmkit.v1.AssignmentsRequest")
	proto.RegisterType((*Assignment)(nil), "docker.swarmkit.v1.Assignment")
	proto.RegisterType((*AssignmentChange)(nil), "docker.swarmkit.v1.AssignmentChange")
	proto.RegisterType((*AssignmentsMessage)(nil), "docker.swarmkit.v1.AssignmentsMessage")
}

func init() {
	proto.RegisterFile("github.com/docker/swarmkit/api/dispatcher.proto", fileDescriptor_71002346457e55a8)
}

var fileDescriptor_71002346457e55a8 = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xbf, 0x6f, 0xdb, 0x46,
	0x14, 0x16, 0x15, 0x85, 0xb6, 0x9e, 0x9c, 0x54, 0x3d, 0x04, 0xae, 0x42, 0x34, 0xb2, 0xca, 0x24,
	0x86, 0xd1, 0x38, 0x54, 0xaa, 0xfe, 0x1a, 0x1a, 0xb8, 0xb1, 0x2c, 0x01, 0x11, 0x12, 0x3b, 0xc6,
	0xc5, 0x71, 0x80, 0x2e, 0x06, 0x25, 0x5e, 0x68, 0x56, 0x12, 0x8f, 0xe5, 0x1d, 0x9d, 0x6a, 0x28,
	0xd0, 0xa1, 0x01, 0x8a, 0x4e, 0x41, 0x27, 0x03, 0x45, 0xff, 0x85, 0x2e, 0xfd, 0x27, 0x8c, 0x4e,
	0x19, 0x33, 0xb9, 0x8d, 0xbc, 0x17, 0x5d, 0xba, 0x74, 0x2a, 0x78, 0x3c, 0x4a, 0xaa, 0x4c, 0xd9,
	0xb2, 0x3b, 0x49, 0x7c, 0xf7, 0x7d, 0xef, 0x3e, 0x7e, 0xf7, 0xde, 0x3d, 0x42, 0xd9, 0x76, 0xf8,
	0x6e, 0xd0, 0x34, 0x5a, 0xb4, 0x5b, 0xb6, 0x68, 0xab, 0x4d, 0xfc, 0x32, 0x7b, 0x6e, 0xfa, 0xdd,
	0xb6, 0xc3, 0xcb, 0xa6, 0xe7, 0x94, 0x2d, 0x87, 0x79, 0x26, 0x6f, 0xed, 0x12, 0xdf, 0xf0, 0x7c,
	0xca, 0x29, 0x42, 0x11, 0xca, 0x88, 0x51, 0xc6, 0xde, 0x07, 0xda, 0xfb, 0xa7, 0x24, 0xe1, 0x3d,
	0x8f, 0xb0, 0x88, 0xaf, 0x2d, 0x9f, 0x82, 0xa5, 0xcd, 0x2f, 0x49, 0x8b, 0xc7, 0xe8, 0x2b, 0x36,
	0xb5, 0xa9, 0xf8, 0x5b, 0x0e, 0xff, 0xc9, 0xe8, 0xa7, 0x27, 0xe4, 0x10, 0x88, 0x66, 0xf0, 0xac,
	0xec, 0x75, 0x02, 0xdb, 0x71, 0xe5, 0x8f, 0x24, 0x16, 0x6d, 0x4a, 0xed, 0x0e, 0x19, 0x82, 0xac,
	0xc0, 0x37, 0xb9, 0x43, 0xe5, 0xba, 0xfe, 0x42, 0x81, 0xcb, 0x8f, 0x09, 0x63, 0x0e, 0x75, 0x31,
	0xf9, 0x2a, 0x20, 0x8c, 0xa3, 0x3a, 0xe4, 0x2c, 0xc2, 0x5a, 0xbe, 0xe3, 0x85, 0xb8, 0x82, 0x52,
	0x52, 0x96, 0x72, 0x95, 0xeb, 0xc6, 0x71, 0x17, 0x8c, 0x0d, 0x6a, 0x91, 0xda, 0x10, 0x8a, 0x47,
	0x79, 0x68, 0x19, 0x80, 0x45, 0x89, 0x77, 0x1c, 0xab, 0x90, 0x2e, 0x29, 0x4b, 0xd9, 0xea, 0xa5,
	0xfe, 0xe1, 0x42, 0x56, 0x6e, 0xd7, 0xa8, 0xe1, 0xac, 0x04, 0x34, 0x2c, 0xfd, 0xa7, 0xf4, 0x40,
	0xc7, 0x3a, 0x61, 0xcc, 0xb4, 0xc9, 0x58, 0x02, 0xe5, 0xe4, 0x04, 0x68, 0x19, 0x32, 0x2e, 0xb5,
	0x88, 0xd8, 0x28, 0x57, 0x29, 0x4c, 0x92, 0x8b, 0x05, 0x0a, 0xdd, 0x85, 0xd9, 0xae, 0xe9, 0x9a,
	0x36, 0xf1, 0x59, 0xe1, 0x42, 0xe9, 0xc2, 0x52, 0xae, 0x52, 0x4a, 0x62, 0x3c, 0x25, 0x8e, 0xbd,
	0xcb, 0x89, 0xb5, 0x49, 0x88, 0x8f, 0x07, 0x0c, 0xf4, 0x14, 0xe6, 0x5d, 0xc2, 0x9f, 0x53, 0xbf,
	0xbd, 0xd3, 0xa4, 0x94, 0x33, 0xee, 0x9b, 0xde, 0x4e, 0x9b, 0xf4, 0x58, 0x21, 0x23, 0x72, 0xbd,
	0x97, 0x94, 0xab, 0xee, 0xb6, 0xfc, 0x9e, 0xb0, 0xe6, 0x01, 0xe9, 0xe1, 0x2b, 0x32, 0x41, 0x35,
	0xe6, 0x3f, 0x20, 0x3d, 0x86, 0xe6, 0x41, 0xc5, 0x94, 0xf2, 0xb5, 0xd5, 0xc2, 0xc5, 0x92, 0xb2,
	0x34, 0x87, 0xe5, 0x93, 0x7e, 0x0f, 0xf2, 0xf7, 0x89, 0xe9, 0xf3, 0x26, 0x31, 0x79, 0x7c, 0x4c,
	0x67, 0xb2, 0x47, 0xdf, 0x84, 0xb7, 0x47, 0x32, 0x30, 0x8f, 0xba, 0x8c, 0xa0, 0xcf, 0x40, 0xf5,
	0x88, 0xef, 0x50, 0x4b, 0x1e, 0xf2, 0x55, 0x23, 0xaa, 0x16, 0x23, 0xae, 0x16, 0xa3, 0x26, 0xab,
	0xa5, 0x3a, 0x7b, 0x70, 0xb8, 0x90, 0xda, 0xff, 0x7d, 0x41, 0xc1, 0x92, 0xa2, 0xbf, 0x4c, 0xc3,
	0x3b, 0x4f, 0x3c, 0xcb, 0xe4, 0x64, 0xcb, 0x64, 0xed, 0xc7, 0xdc, 0xe4, 0x01, 0x3b, 0x97, 0x36,
	0xb4, 0x0d, 0x33, 0x81, 0x48, 0x14, 0x9f, 0xc5, 0xdd, 0x24, 0xff, 0x26, 0xec, 0x65, 0x0c, 0x23,
	0x11, 0x02, 0xc7, 0xc9, 0x34, 0x0a, 0xf9, 0xf1, 0x45, 0x74, 0x1d, 0x66, 0xb8, 0xc9, 0xda, 0x43,
	0x59, 0xd0, 0x3f, 0x5c, 0x50, 0x43, 0x58, 0xa3, 0x86, 0xd5, 0x70, 0xa9, 0x61, 0xa1, 0x4f, 0x40,
	0x65, 0x82, 0x24, 0xab, 0xa9, 0x98, 0xa4, 0x67, 0x44, 0x89, 0x44, 0xeb, 0x1a, 0x14, 0x8e, 0xab,
	0x8c, 0xbc, 0xd6, 0xff, 0x56, 0xe0, 0x6a, 0xb4, 0xb8, 0x4d, 0x3b, 0x41, 0x97, 0xfc, 0x1f, 0xc3,
	0xbe, 0x18, 0x1a, 0x96, 0x16, 0x86, 0xdd, 0x9b, 0x6c, 0x58, 0xc2, 0x6e, 0xc6, 0x68, 0x6c, 0xdc,
	0xb4, 0x0d, 0x40, 0xc7, 0x97, 0xd1, 0x3c, 0xa4, 0x07, 0xba, 0xd4, 0xfe, 0xe1, 0x42, 0xba, 0x51,
	0xc3, 0x69, 0xc7, 0x42, 0x25, 0xc8, 0x05, 0xae, 0x17, 0x34, 0x3b, 0x0e, 0xdb, 0x25, 0x51, 0x97,
	0xcf, 0xe2, 0xd1, 0x90, 0xfe, 0x2e, 0x68, 0x49, 0x42, 0xa4, 0x2b, 0x77, 0x61, 0x2e, 0xf4, 0xea,
	0x7c, 0x3e, 0xe8, 0x2b, 0x92, 0x1d, 0xdf, 0x18, 0x06, 0x5c, 0x0c, 0x4f, 0x90, 0x15, 0x14, 0xe1,
	0x4a, 0x61, 0xd2, 0xb1, 0xe1, 0x08, 0xa6, 0x57, 0x01, 0xad, 0x32, 0xe6, 0xd8, 0x6e, 0x97, 0xb8,
	0xfc, 0x9c, 0x1a, 0xfe, 0x52, 0x00, 0x86, 0x49, 0x90, 0x01, 0x99, 0x30, 0xb7, 0x6c, 0xa8, 0x89,
	0x0a, 0xee, 0xa7, 0xb0, 0xc0, 0xa1, 0x8f, 0x40, 0x65, 0xa4, 0xe5, 0x13, 0x2e, 0x4b, 0x4d, 0x4b,
	0x62, 0x3c, 0x16, 0x88, 0xfb, 0x29, 0x2c, 0xb1, 0x21, 0xab, 0x45, 0xdd, 0x67, 0x8e, 0x5d, 0xb8,
	0x30, 0x99, 0xb5, 0x26, 0x10, 0x21, 0x2b, 0xc2, 0xa2, 0x15, 0x50, 0xf7, 0xc4, 0x21, 0x14, 0x32,
	0x82, 0x75, 0x23, 0x89, 0x15, 0x1d, 0xd3, 0xf0, 0x8d, 0x42, 0x7e, 0xc4, 0xaa, 0xaa, 0x90, 0x71,
	0x38, 0xe9, 0xea, 0x2f, 0xd2, 0x90, 0x1f, 0x02, 0xd6, 0x76, 0x4d, 0xd7, 0x26, 0x68, 0x05, 0xc0,
	0x1c, 0xc4, 0xe4, 0xeb, 0x27, 0xf6, 0xcd, 0x90, 0x89, 0x47, 0x18, 0x68, 0x1d, 0x54, 0xb3, 0x25,
	0x06, 0x4e, 0x68, 0xc4, 0xe5, 0xca, 0xc7, 0x27, 0x73, 0xa3, 0x5d, 0x47, 0x02, 0xab, 0x82, 0x8c,
	0x65, 0x12, 0xbd, 0x39, 0x2a, 0x31, 0x5a, 0x43, 0x8b, 0xa0, 0x3e, 0xd9, 0xac, 0xad, 0x6e, 0xd5,
	0xf3, 0x29, 0x4d, 0xfb, 0xe1, 0xe7, 0xd2, 0xfc, 0x38, 0x42, 0x16, 0xfb, 0x22, 0xa8, 0xb8, 0xbe,
	0xfe, 0x68, 0xbb, 0x9e, 0x57, 0x92, 0x71, 0x98, 0x74, 0xe9, 0x1e, 0xd1, 0xff, 0x51, 0xfe, 0x53,
	0x3f, 0x71, 0x15, 0x7e, 0x0e, 0x99, 0x70, 0xfc, 0x0b, 0x0f, 0x2e, 0x57, 0x6e, 0x9d, 0xfc, 0x1e,
	0x31, 0xcb, 0xd8, 0xea, 0x79, 0x04, 0x0b, 0x22, 0xba, 0x06, 0x60, 0x7a, 0x5e, 0xc7, 0x21, 0x6c,
	0x87, 0xd3, 0x68, 0x72, 0xe2, 0xac, 0x8c, 0x6c, 0xd1, 0x70, 0xd9, 0x27, 0x2c, 0xe8, 0x70, 0xb6,
	0xe3, 0xb8, 0xa2, 0x00, 0xb2, 0x38, 0x2b, 0x23, 0x0d, 0x17, 0xad, 0xc0, 0x4c, 0x4b, 0x98, 0x13,
	0x4f, 0xa3, 0x1b, 0xd3, 0x38, 0x89, 0x63, 0x92, 0x7e, 0x13, 0x32, 0xa1, 0x16, 0x34, 0x07, 0xb3,
	0x6b, 0x8f, 0xd6, 0x37, 0x1f, 0xd6, 0x43, 0xbf, 0xd0, 0x5b, 0x90, 0x6b, 0x6c, 0xac, 0xe1, 0xfa,
	0x7a, 0x7d, 0x63, 0x6b, 0xf5, 0x61, 0x5e, 0xa9, 0xfc, 0xaa, 0x02, 0xd4, 0x06, 0x9f, 0x4a, 0xe8,
	0x6b, 0x98, 0x91, 0xed, 0x81, 0xf4, 0xe4, 0x12, 0x1e, 0xfd, 0xc6, 0xd0, 0x4e, 0xc2, 0x48, 0x47,
	0xf4, 0xeb, 0xbf, 0xfd, 0xf2, 0xe7, 0x7e, 0xfa, 0x1a, 0xcc, 0x09, 0xcc, 0xed, 0x70, 0x5a, 0x12,
	0x1f, 0x2e, 0x45, 0x4f, 0x72, 0x16, 0xdf, 0x51, 0xd0, 0x37, 0x90, 0x1d, 0x4c, 0x36, 0x94, 0xf8,
	0xae, 0xe3, 0xa3, 0x53, 0xbb, 0x79, 0x0a, 0x4a, 0x5e, 0x4e, 0xd3, 0x08, 0x40, 0x3f, 0x2a, 0x90,
	0x1f, 0xbf, 0xf4, 0xd1, 0xad, 0x33, 0x0c, 0x30, 0x6d, 0x79, 0x3a, 0xf0, 0x59, 0x44, 0xed, 0x2b,
	0x80, 0x8e, 0xdf, 0xba, 0xe8, 0xf6, 0x99, 0xc6, 0x84, 0x66, 0x4c, 0x0b, 0x3f, 0x8b, 0xb4, 0x00,
	0x2e, 0x8a, 0x3b, 0x1b, 0x95, 0x26, 0xdd, 0x8d, 0x83, 0xfd, 0x27, 0x23, 0xe2, 0x12, 0x59, 0x9c,
	0x62, 0xc7, 0xef, 0xd3, 0xca, 0x1d, 0x05, 0x7d, 0xa7, 0x40, 0x6e, 0xa4, 0xeb, 0xd0, 0xe2, 0x29,
	0x6d, 0x19, 0x6b, 0x58, 0x9c, 0xae, 0x7d, 0xa7, 0x2c, 0xd6, 0xea, 0x8d, 0x83, 0x37, 0xc5, 0xd4,
	0xeb, 0x37, 0xc5, 0xd4, 0xb7, 0xfd, 0xa2, 0x72, 0xd0, 0x2f, 0x2a, 0xaf, 0xfa, 0x45, 0xe5, 0x8f,
	0x7e, 0x51, 0x79, 0x79, 0x54, 0x4c, 0xbd, 0x3a, 0x2a, 0xa6, 0x5e, 0x1f, 0x15, 0x53, 0x4d, 0x55,
	0x7c, 0x7f, 0x7d, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x3b, 0xe2, 0x0b, 0xab, 0x0c,
	0x00, 0x00,
}

type authenticatedWrapperDispatcherServer struct {
	local     DispatcherServer
	authorize func(context.Context, []string) error
}

func NewAuthenticatedWrapperDispatcherServer(local DispatcherServer, authorize func(context.Context, []string) error) DispatcherServer {
	_ = "STUB: not implemented"
	return *new(DispatcherServer)
}

func (p *authenticatedWrapperDispatcherServer) Session(r *SessionRequest, stream Dispatcher_SessionServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (p *authenticatedWrapperDispatcherServer) Heartbeat(ctx context.Context, r *HeartbeatRequest) (*HeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *authenticatedWrapperDispatcherServer) UpdateTaskStatus(ctx context.Context, r *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *authenticatedWrapperDispatcherServer) UpdateVolumeStatus(ctx context.Context, r *UpdateVolumeStatusRequest) (*UpdateVolumeStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *authenticatedWrapperDispatcherServer) Tasks(r *TasksRequest, stream Dispatcher_TasksServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (p *authenticatedWrapperDispatcherServer) Assignments(r *AssignmentsRequest, stream Dispatcher_AssignmentsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SessionRequest) Copy() *SessionRequest { _ = "STUB: not implemented"; return nil }

func (m *SessionRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *SessionMessage) Copy() *SessionMessage { _ = "STUB: not implemented"; return nil }

func (m *SessionMessage) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *HeartbeatRequest) Copy() *HeartbeatRequest { _ = "STUB: not implemented"; return nil }

func (m *HeartbeatRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *HeartbeatResponse) Copy() *HeartbeatResponse { _ = "STUB: not implemented"; return nil }

func (m *HeartbeatResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *UpdateTaskStatusRequest) Copy() *UpdateTaskStatusRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) Copy() *UpdateTaskStatusRequest_TaskStatusUpdate {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) CopyFrom(src interface{}) {
	_ = "STUB: not implemented"
	return
}

func (m *UpdateTaskStatusResponse) Copy() *UpdateTaskStatusResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }
func (m *UpdateVolumeStatusRequest) Copy() *UpdateVolumeStatusRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) Copy() *UpdateVolumeStatusRequest_VolumeStatusUpdate {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) CopyFrom(src interface{}) {
	_ = "STUB: not implemented"
	return
}

func (m *UpdateVolumeStatusResponse) Copy() *UpdateVolumeStatusResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }
func (m *TasksRequest) Copy() *TasksRequest                    { _ = "STUB: not implemented"; return nil }

func (m *TasksRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *TasksMessage) Copy() *TasksMessage { _ = "STUB: not implemented"; return nil }

func (m *TasksMessage) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *AssignmentsRequest) Copy() *AssignmentsRequest { _ = "STUB: not implemented"; return nil }

func (m *AssignmentsRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Assignment) Copy() *Assignment { _ = "STUB: not implemented"; return nil }

func (m *Assignment) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *AssignmentChange) Copy() *AssignmentChange { _ = "STUB: not implemented"; return nil }

func (m *AssignmentChange) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *AssignmentsMessage) Copy() *AssignmentsMessage { _ = "STUB: not implemented"; return nil }

func (m *AssignmentsMessage) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DispatcherClient is the client API for Dispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DispatcherClient interface {
	// Session starts an agent session with the dispatcher. The session is
	// started after the first SessionMessage is received.
	//
	// Once started, the agent is controlled with a stream of SessionMessage.
	// Agents should list on the stream at all times for instructions.
	Session(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (Dispatcher_SessionClient, error)
	// Heartbeat is heartbeat method for nodes. It returns new TTL in response.
	// Node should send new heartbeat earlier than now + TTL, otherwise it will
	// be deregistered from dispatcher and its status will be updated to NodeStatus_DOWN
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// UpdateTaskStatus updates status of task. Node should send such updates
	// on every status change of its tasks.
	//
	// Whether receiving batch updates or single status updates, this method
	// should be accepting. Errors should only be returned if the entire update
	// should be retried, due to data loss or other problems.
	//
	// If a task is unknown the dispatcher, the status update should be
	// accepted regardless.
	UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*UpdateTaskStatusResponse, error)
	// UpdateVolumeStatus updates the status of a Volume. Like
	// UpdateTaskStatus, the node should send such updates on every status
	// change of its volumes.
	UpdateVolumeStatus(ctx context.Context, in *UpdateVolumeStatusRequest, opts ...grpc.CallOption) (*UpdateVolumeStatusResponse, error)
	// Tasks is a stream of tasks state for node. Each message contains full list
	// of tasks which should be run on node, if task is not present in that list,
	// it should be terminated.
	Tasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (Dispatcher_TasksClient, error)
	// Assignments is a stream of assignments such as tasks and secrets for node.
	// The first message in the stream contains all of the tasks and secrets
	// that are relevant to the node. Future messages in the stream are updates to
	// the set of assignments.
	Assignments(ctx context.Context, in *AssignmentsRequest, opts ...grpc.CallOption) (Dispatcher_AssignmentsClient, error)
}

type dispatcherClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherClient(cc *grpc.ClientConn) DispatcherClient {
	_ = "STUB: not implemented"
	return *new(DispatcherClient)
}

func (c *dispatcherClient) Session(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (Dispatcher_SessionClient, error) {
	_ = "STUB: not implemented"
	return *new(Dispatcher_SessionClient), nil
}

type Dispatcher_SessionClient interface {
	Recv() (*SessionMessage, error)
	grpc.ClientStream
}

type dispatcherSessionClient struct {
	grpc.ClientStream
}

func (x *dispatcherSessionClient) Recv() (*SessionMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *dispatcherClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *dispatcherClient) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*UpdateTaskStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *dispatcherClient) UpdateVolumeStatus(ctx context.Context, in *UpdateVolumeStatusRequest, opts ...grpc.CallOption) (*UpdateVolumeStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Deprecated: Do not use.
func (c *dispatcherClient) Tasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (Dispatcher_TasksClient, error) {
	_ = "STUB: not implemented"
	return *new(Dispatcher_TasksClient), nil
}

type Dispatcher_TasksClient interface {
	Recv() (*TasksMessage, error)
	grpc.ClientStream
}

type dispatcherTasksClient struct {
	grpc.ClientStream
}

func (x *dispatcherTasksClient) Recv() (*TasksMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *dispatcherClient) Assignments(ctx context.Context, in *AssignmentsRequest, opts ...grpc.CallOption) (Dispatcher_AssignmentsClient, error) {
	_ = "STUB: not implemented"
	return *new(Dispatcher_AssignmentsClient), nil
}

type Dispatcher_AssignmentsClient interface {
	Recv() (*AssignmentsMessage, error)
	grpc.ClientStream
}

type dispatcherAssignmentsClient struct {
	grpc.ClientStream
}

func (x *dispatcherAssignmentsClient) Recv() (*AssignmentsMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DispatcherServer is the server API for Dispatcher service.
type DispatcherServer interface {
	// Session starts an agent session with the dispatcher. The session is
	// started after the first SessionMessage is received.
	//
	// Once started, the agent is controlled with a stream of SessionMessage.
	// Agents should list on the stream at all times for instructions.
	Session(*SessionRequest, Dispatcher_SessionServer) error
	// Heartbeat is heartbeat method for nodes. It returns new TTL in response.
	// Node should send new heartbeat earlier than now + TTL, otherwise it will
	// be deregistered from dispatcher and its status will be updated to NodeStatus_DOWN
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// UpdateTaskStatus updates status of task. Node should send such updates
	// on every status change of its tasks.
	//
	// Whether receiving batch updates or single status updates, this method
	// should be accepting. Errors should only be returned if the entire update
	// should be retried, due to data loss or other problems.
	//
	// If a task is unknown the dispatcher, the status update should be
	// accepted regardless.
	UpdateTaskStatus(context.Context, *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error)
	// UpdateVolumeStatus updates the status of a Volume. Like
	// UpdateTaskStatus, the node should send such updates on every status
	// change of its volumes.
	UpdateVolumeStatus(context.Context, *UpdateVolumeStatusRequest) (*UpdateVolumeStatusResponse, error)
	// Tasks is a stream of tasks state for node. Each message contains full list
	// of tasks which should be run on node, if task is not present in that list,
	// it should be terminated.
	Tasks(*TasksRequest, Dispatcher_TasksServer) error
	// Assignments is a stream of assignments such as tasks and secrets for node.
	// The first message in the stream contains all of the tasks and secrets
	// that are relevant to the node. Future messages in the stream are updates to
	// the set of assignments.
	Assignments(*AssignmentsRequest, Dispatcher_AssignmentsServer) error
}

// UnimplementedDispatcherServer can be embedded to have forward compatible implementations.
type UnimplementedDispatcherServer struct {
}

func (*UnimplementedDispatcherServer) Session(req *SessionRequest, srv Dispatcher_SessionServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (*UnimplementedDispatcherServer) Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedDispatcherServer) UpdateTaskStatus(ctx context.Context, req *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedDispatcherServer) UpdateVolumeStatus(ctx context.Context, req *UpdateVolumeStatusRequest) (*UpdateVolumeStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedDispatcherServer) Tasks(req *TasksRequest, srv Dispatcher_TasksServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (*UnimplementedDispatcherServer) Assignments(req *AssignmentsRequest, srv Dispatcher_AssignmentsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	_ = "STUB: not implemented"
	return
}

func _Dispatcher_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Dispatcher_SessionServer interface {
	Send(*SessionMessage) error
	grpc.ServerStream
}

type dispatcherSessionServer struct {
	grpc.ServerStream
}

func (x *dispatcherSessionServer) Send(m *SessionMessage) error {
	_ = "STUB: not implemented"
	return nil
}

func _Dispatcher_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Dispatcher_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Dispatcher_UpdateVolumeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Dispatcher_Tasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Dispatcher_TasksServer interface {
	Send(*TasksMessage) error
	grpc.ServerStream
}

type dispatcherTasksServer struct {
	grpc.ServerStream
}

func (x *dispatcherTasksServer) Send(m *TasksMessage) error { _ = "STUB: not implemented"; return nil }

func _Dispatcher_Assignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Dispatcher_AssignmentsServer interface {
	Send(*AssignmentsMessage) error
	grpc.ServerStream
}

type dispatcherAssignmentsServer struct {
	grpc.ServerStream
}

func (x *dispatcherAssignmentsServer) Send(m *AssignmentsMessage) error {
	_ = "STUB: not implemented"
	return nil
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "docker.swarmkit.v1.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _Dispatcher_Heartbeat_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _Dispatcher_UpdateTaskStatus_Handler,
		},
		{
			MethodName: "UpdateVolumeStatus",
			Handler:    _Dispatcher_UpdateVolumeStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Dispatcher_Session_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Tasks",
			Handler:       _Dispatcher_Tasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Assignments",
			Handler:       _Dispatcher_Assignments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/docker/swarmkit/api/dispatcher.proto",
}

func (m *SessionRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SessionRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SessionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SessionMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SessionMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SessionMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HeartbeatRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HeartbeatRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HeartbeatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HeartbeatResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HeartbeatResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HeartbeatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateTaskStatusRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateTaskStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateTaskStatusResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateTaskStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateTaskStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateVolumeStatusRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateVolumeStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateVolumeStatusResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpdateVolumeStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpdateVolumeStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TasksRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TasksRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TasksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TasksMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TasksMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TasksMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AssignmentsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AssignmentsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AssignmentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Assignment) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Assignment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Task) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Secret) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Secret) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Config) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Volume) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Assignment_Volume) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AssignmentChange) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AssignmentChange) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AssignmentChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AssignmentsMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AssignmentsMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AssignmentsMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintDispatcher(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

type raftProxyDispatcherServer struct {
	local                       DispatcherServer
	connSelector                raftselector.ConnProvider
	localCtxMods, remoteCtxMods []func(context.Context) (context.Context, error)
}

func NewRaftProxyDispatcherServer(local DispatcherServer, connSelector raftselector.ConnProvider, localCtxMod, remoteCtxMod func(context.Context) (context.Context, error)) DispatcherServer {
	_ = "STUB: not implemented"
	return *new(DispatcherServer)
}

func (p *raftProxyDispatcherServer) runCtxMods(ctx context.Context, ctxMods []func(context.Context) (context.Context, error)) (context.Context, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), nil
}

func (p *raftProxyDispatcherServer) pollNewLeaderConn(ctx context.Context) (*grpc.ClientConn, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type Dispatcher_SessionServerWrapper struct {
	Dispatcher_SessionServer
	ctx context.Context
}

func (s Dispatcher_SessionServerWrapper) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (p *raftProxyDispatcherServer) Session(r *SessionRequest, stream Dispatcher_SessionServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (p *raftProxyDispatcherServer) Heartbeat(ctx context.Context, r *HeartbeatRequest) (*HeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *raftProxyDispatcherServer) UpdateTaskStatus(ctx context.Context, r *UpdateTaskStatusRequest) (*UpdateTaskStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *raftProxyDispatcherServer) UpdateVolumeStatus(ctx context.Context, r *UpdateVolumeStatusRequest) (*UpdateVolumeStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type Dispatcher_TasksServerWrapper struct {
	Dispatcher_TasksServer
	ctx context.Context
}

func (s Dispatcher_TasksServerWrapper) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (p *raftProxyDispatcherServer) Tasks(r *TasksRequest, stream Dispatcher_TasksServer) error {
	_ = "STUB: not implemented"
	return nil
}

type Dispatcher_AssignmentsServerWrapper struct {
	Dispatcher_AssignmentsServer
	ctx context.Context
}

func (s Dispatcher_AssignmentsServerWrapper) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (p *raftProxyDispatcherServer) Assignments(r *AssignmentsRequest, stream Dispatcher_AssignmentsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SessionRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SessionMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HeartbeatRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HeartbeatResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *UpdateTaskStatusRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) Size() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *UpdateTaskStatusResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *UpdateVolumeStatusRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) Size() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *UpdateVolumeStatusResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TasksRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TasksMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AssignmentsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Assignment) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Assignment_Task) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Assignment_Secret) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Assignment_Config) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Assignment_Volume) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AssignmentChange) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AssignmentsMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovDispatcher(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozDispatcher(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (this *SessionRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *SessionMessage) String() string { _ = "STUB: not implemented"; return "" }

func (this *HeartbeatRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *HeartbeatResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *UpdateTaskStatusRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *UpdateTaskStatusRequest_TaskStatusUpdate) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (this *UpdateTaskStatusResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *UpdateVolumeStatusRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *UpdateVolumeStatusRequest_VolumeStatusUpdate) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (this *UpdateVolumeStatusResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *TasksRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *TasksMessage) String() string { _ = "STUB: not implemented"; return "" }

func (this *AssignmentsRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *Assignment) String() string { _ = "STUB: not implemented"; return "" }

func (this *Assignment_Task) String() string { _ = "STUB: not implemented"; return "" }

func (this *Assignment_Secret) String() string { _ = "STUB: not implemented"; return "" }

func (this *Assignment_Config) String() string { _ = "STUB: not implemented"; return "" }

func (this *Assignment_Volume) String() string { _ = "STUB: not implemented"; return "" }

func (this *AssignmentChange) String() string { _ = "STUB: not implemented"; return "" }

func (this *AssignmentsMessage) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringDispatcher(v interface{}) string { _ = "STUB: not implemented"; return "" }

func (m *SessionRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SessionMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HeartbeatRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HeartbeatResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *UpdateTaskStatusRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusRequest_TaskStatusUpdate) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateTaskStatusResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusRequest_VolumeStatusUpdate) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *UpdateVolumeStatusResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *TasksRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TasksMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AssignmentsRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Assignment) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AssignmentChange) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AssignmentsMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipDispatcher(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthDispatcher        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDispatcher          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDispatcher = fmt.Errorf("proto: unexpected end of group")
)
