// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/swarmkit/api/objects.proto

package api

import (
	fmt "fmt"
	math "math"

	github_com_docker_go_events "github.com/docker/go-events"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/moby/swarmkit/v2/protobuf/plugin"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Meta contains metadata about objects. Every object contains a meta field.
type Meta struct {
	// Version tracks the current version of the object.
	Version Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	// Object timestamps.
	// Note: can't use stdtime because these fields are nullable.
	CreatedAt *types.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *types.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Meta) Reset()                    { _ = "STUB: not implemented"; return }
func (*Meta) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Meta) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Meta) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Meta) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Meta) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Meta) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Meta proto.InternalMessageInfo

// Node provides the internal node state as seen by the cluster.
type Node struct {
	// ID specifies the identity of the node.
	ID   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	// Spec defines the desired state of the node as specified by the user.
	// The system will honor this and will *never* modify it.
	Spec NodeSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// Description encapsulated the properties of the Node as reported by the
	// agent.
	Description *NodeDescription `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Status provides the current status of the node, as seen by the manager.
	Status NodeStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status"`
	// ManagerStatus provides the current status of the node's manager
	// component, if the node is a manager.
	ManagerStatus *ManagerStatus `protobuf:"bytes,6,opt,name=manager_status,json=managerStatus,proto3" json:"manager_status,omitempty"`
	// DEPRECATED: Use Attachments to find the ingress network
	// The node attachment to the ingress network.
	Attachment *NetworkAttachment `protobuf:"bytes,7,opt,name=attachment,proto3" json:"attachment,omitempty"` // Deprecated: Do not use.
	// Certificate is the TLS certificate issued for the node, if any.
	Certificate Certificate `protobuf:"bytes,8,opt,name=certificate,proto3" json:"certificate"`
	// Role is the *observed* role for this node. It differs from the
	// desired role set in Node.Spec.Role because the role here is only
	// updated after the Raft member list has been reconciled with the
	// desired role from the spec.
	//
	// This field represents the current reconciled state. If an action is
	// to be performed, first verify the role in the cert. This field only
	// shows the privilege level that the CA would currently grant when
	// issuing or renewing the node's certificate.
	Role NodeRole `protobuf:"varint,9,opt,name=role,proto3,enum=docker.swarmkit.v1.NodeRole" json:"role,omitempty"`
	// Attachments enumerates the network attachments for the node to set up an
	// endpoint on the node to be used for load balancing. Each overlay
	// network, including ingress network, will have an NetworkAttachment.
	Attachments []*NetworkAttachment `protobuf:"bytes,10,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// VXLANUDPPort specifies the UDP port for VXLAN traffic.
	// This information is passed from cluster object to individual nodes.
	VXLANUDPPort uint32 `protobuf:"varint,11,opt,name=VXLANUDPPort,proto3" json:"VXLANUDPPort,omitempty"`
}

func (m *Node) Reset()                    { _ = "STUB: not implemented"; return }
func (*Node) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Node) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Node) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Node) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Node) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Node) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Node proto.InternalMessageInfo

type Service struct {
	ID   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	Spec ServiceSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// SpecVersion versions Spec, to identify changes in the spec. Note that
	// this is not directly comparable to the service's Version.
	SpecVersion *Version `protobuf:"bytes,10,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	// PreviousSpec is the previous service spec that was in place before
	// "Spec".
	PreviousSpec *ServiceSpec `protobuf:"bytes,6,opt,name=previous_spec,json=previousSpec,proto3" json:"previous_spec,omitempty"`
	// PreviousSpecVersion versions PreviousSpec. Note that this is not
	// directly comparable to the service's Version.
	PreviousSpecVersion *Version `protobuf:"bytes,11,opt,name=previous_spec_version,json=previousSpecVersion,proto3" json:"previous_spec_version,omitempty"`
	// Runtime state of service endpoint. This may be different
	// from the spec version because the user may not have entered
	// the optional fields like node_port or virtual_ip and it
	// could be auto allocated by the system.
	Endpoint *Endpoint `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// UpdateStatus contains the status of an update, if one is in
	// progress.
	UpdateStatus *UpdateStatus `protobuf:"bytes,5,opt,name=update_status,json=updateStatus,proto3" json:"update_status,omitempty"`
	// JobStatus contains the status of a Service that is in one of the Job
	// modes. It is absent on Replicated and Global services.
	JobStatus *JobStatus `protobuf:"bytes,12,opt,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`
	// PendingDelete indicates that this service's deletion has been requested.
	// Services, as well as all service-level resources, can only be deleted
	// after all of the service's containers have properly shut down.
	// When a user requests a deletion, we just flip this flag
	// the deallocator will take it from there - it will start monitoring
	// this service's tasks, and proceed to delete the service itself (and
	// potentially its associated resources also marked for deletion) when
	// all of its tasks are gone
	PendingDelete bool `protobuf:"varint,7,opt,name=pending_delete,json=pendingDelete,proto3" json:"pending_delete,omitempty"`
}

func (m *Service) Reset()                    { _ = "STUB: not implemented"; return }
func (*Service) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Service) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Service) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Service) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Service) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Service) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Service proto.InternalMessageInfo

// Endpoint specified all the network parameters required to
// correctly discover and load balance a service
type Endpoint struct {
	Spec *EndpointSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Runtime state of the exposed ports which may carry
	// auto-allocated swarm ports in addition to the user
	// configured information.
	Ports []*PortConfig `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	// VirtualIPs specifies the IP addresses under which this endpoint will be
	// made available.
	VirtualIPs []*Endpoint_VirtualIP `protobuf:"bytes,3,rep,name=virtual_ips,json=virtualIps,proto3" json:"virtual_ips,omitempty"`
}

func (m *Endpoint) Reset()                    { _ = "STUB: not implemented"; return }
func (*Endpoint) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Endpoint) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Endpoint) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Endpoint) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Endpoint) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Endpoint) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

// VirtualIP specifies a set of networks this endpoint will be attached to
// and the IP addresses the target service will be made available under.
type Endpoint_VirtualIP struct {
	// NetworkID for which this endpoint attachment was created.
	NetworkID string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// A virtual IP is used to address this service in IP
	// layer that the client can use to send requests to
	// this service. A DNS A/AAAA query on the service
	// name might return this IP to the client. This is
	// strictly a logical IP and there may not be any
	// interfaces assigned this IP address or any route
	// created for this address.  More than one to
	// accommodate for both IPv4 and IPv6
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (m *Endpoint_VirtualIP) Reset()                    { _ = "STUB: not implemented"; return }
func (*Endpoint_VirtualIP) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Endpoint_VirtualIP) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Endpoint_VirtualIP) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Endpoint_VirtualIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Endpoint_VirtualIP) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Endpoint_VirtualIP) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Endpoint_VirtualIP) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Endpoint_VirtualIP proto.InternalMessageInfo

// Task specifies the parameters for implementing a Spec. A task is effectively
// immutable and idempotent. Once it is dispatched to a node, it will not be
// dispatched to another node.
type Task struct {
	ID   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	// Spec defines the desired state of the task as specified by the user.
	// The system will honor this and will *never* modify it.
	Spec TaskSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// SpecVersion is copied from Service, to identify which version of the
	// spec this task has. Note that this is not directly comparable to the
	// service's Version.
	SpecVersion *Version `protobuf:"bytes,14,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	// ServiceID indicates the service under which this task is orchestrated. This
	// should almost always be set.
	ServiceID string `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Slot is the service slot number for a task.
	// For example, if a replicated service has replicas = 2, there will be a
	// task with slot = 1, and another with slot = 2.
	Slot uint64 `protobuf:"varint,5,opt,name=slot,proto3" json:"slot,omitempty"`
	// NodeID indicates the node to which the task is assigned. If this field
	// is empty or not set, the task is unassigned.
	NodeID string `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Annotations defines the names and labels for the runtime, as set by
	// the cluster manager.
	//
	// As backup, if this field has an empty name, the runtime will
	// allocate a unique name for the actual container.
	//
	// NOTE(stevvooe): The preserves the ability for us to making naming
	// decisions for tasks in orchestrator, albeit, this is left empty for now.
	Annotations Annotations `protobuf:"bytes,7,opt,name=annotations,proto3" json:"annotations"`
	// ServiceAnnotations is a direct copy of the service name and labels when
	// this task is created.
	//
	// Labels set here will *not* be propagated to the runtime target, such as a
	// container. Use labels on the runtime target for that purpose.
	ServiceAnnotations Annotations `protobuf:"bytes,8,opt,name=service_annotations,json=serviceAnnotations,proto3" json:"service_annotations"`
	Status             TaskStatus  `protobuf:"bytes,9,opt,name=status,proto3" json:"status"`
	// DesiredState is the target state for the task. It is set to
	// TaskStateRunning when a task is first created, and changed to
	// TaskStateShutdown if the manager wants to terminate the task. This field
	// is only written by the manager.
	DesiredState TaskState `protobuf:"varint,10,opt,name=desired_state,json=desiredState,proto3,enum=docker.swarmkit.v1.TaskState" json:"desired_state,omitempty"`
	// List of network attachments by the task.
	Networks []*NetworkAttachment `protobuf:"bytes,11,rep,name=networks,proto3" json:"networks,omitempty"`
	// A copy of runtime state of service endpoint from Service
	// object to be distributed to agents as part of the task.
	Endpoint *Endpoint `protobuf:"bytes,12,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// LogDriver specifies the selected log driver to use for the task. Agent
	// processes should always favor the value in this field.
	//
	// If present in the TaskSpec, this will be a copy of that value. The
	// orchestrator may choose to insert a value here, which should be honored,
	// such a cluster default or policy-based value.
	//
	// If not present, the daemon's default will be used.
	LogDriver                *Driver            `protobuf:"bytes,13,opt,name=log_driver,json=logDriver,proto3" json:"log_driver,omitempty"`
	AssignedGenericResources []*GenericResource `protobuf:"bytes,15,rep,name=assigned_generic_resources,json=assignedGenericResources,proto3" json:"assigned_generic_resources,omitempty"`
	// JobIteration is the iteration number of the Job-mode Service that this
	// task belongs to.
	JobIteration *Version `protobuf:"bytes,16,opt,name=job_iteration,json=jobIteration,proto3" json:"job_iteration,omitempty"`
	// Volumes is a list of VolumeAttachments for this task. It specifies which
	// volumes this task is allocated.
	Volumes []*VolumeAttachment `protobuf:"bytes,17,rep,name=volumes,proto3" json:"volumes,omitempty"`
}

func (m *Task) Reset()                    { _ = "STUB: not implemented"; return }
func (*Task) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Task) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Task) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Task) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Task) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Task) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Task proto.InternalMessageInfo

// NetworkAttachment specifies the network parameters of attachment to
// a single network by an object such as task or node.
type NetworkAttachment struct {
	// Network state as a whole becomes part of the object so that
	// it always is available for use in agents so that agents
	// don't have any other dependency during execution.
	Network *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// List of IPv4/IPv6 addresses that are assigned to the object
	// as part of getting attached to this network.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// List of aliases by which a task is resolved in a network
	Aliases []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// Map of all the driver attachment options for this network
	DriverAttachmentOpts map[string]string `protobuf:"bytes,4,rep,name=driver_attachment_opts,json=driverAttachmentOpts,proto3" json:"driver_attachment_opts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *NetworkAttachment) Reset()                    { _ = "STUB: not implemented"; return }
func (*NetworkAttachment) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NetworkAttachment) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NetworkAttachment) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NetworkAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NetworkAttachment) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NetworkAttachment) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NetworkAttachment) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NetworkAttachment proto.InternalMessageInfo

type Network struct {
	ID   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	Spec NetworkSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// Driver specific operational state provided by the network driver.
	DriverState *Driver `protobuf:"bytes,4,opt,name=driver_state,json=driverState,proto3" json:"driver_state,omitempty"`
	// Runtime state of IPAM options. This may not reflect the
	// ipam options from NetworkSpec.
	IPAM *IPAMOptions `protobuf:"bytes,5,opt,name=ipam,proto3" json:"ipam,omitempty"`
	// PendingDelete indicates that this network's deletion has been requested.
	// Services, as well as all service-level resources, can only be deleted
	// after all the service's containers have properly shut down
	// when a user requests a deletion, we just flip this flag
	// the deallocator will take it from there
	// PendingDelete indicates that this network's deletion has been requested.
	// Services, as well as all service-level resources, can only be deleted
	// after all of the service's containers have properly shut down.
	// When a user requests a deletion of this network, we just flip this flag
	// the deallocator will take it from there - it will start monitoring
	// the services that still use this service, and proceed to delete
	// this network when all of these services are gone
	PendingDelete bool `protobuf:"varint,6,opt,name=pending_delete,json=pendingDelete,proto3" json:"pending_delete,omitempty"`
	// Extra encodes application-specific information about the live state
	// of the network. The syntax and semantics of the value are dictated by
	// the network allocator implementation.
	Extra *types.Any `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (m *Network) Reset()                    { _ = "STUB: not implemented"; return }
func (*Network) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Network) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Network) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Network) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Network) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Network) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Network proto.InternalMessageInfo

// Cluster provides global cluster settings.
type Cluster struct {
	ID   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	Spec ClusterSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// RootCA contains key material for the root CA.
	RootCA RootCA `protobuf:"bytes,4,opt,name=root_ca,json=rootCa,proto3" json:"root_ca"`
	// Symmetric encryption key distributed by the lead manager. Used by agents
	// for securing network bootstrapping and communication.
	NetworkBootstrapKeys []*EncryptionKey `protobuf:"bytes,5,rep,name=network_bootstrap_keys,json=networkBootstrapKeys,proto3" json:"network_bootstrap_keys,omitempty"`
	// Logical clock used to timestamp every key.  It allows other managers
	// and agents to unambiguously identify the older key to be deleted when
	// a new key is allocated on key rotation.
	EncryptionKeyLamportClock uint64 `protobuf:"varint,6,opt,name=encryption_key_lamport_clock,json=encryptionKeyLamportClock,proto3" json:"encryption_key_lamport_clock,omitempty"`
	// BlacklistedCertificates tracks certificates that should no longer
	// be honored. It's a mapping from CN -> BlacklistedCertificate.
	// swarm. Their certificates should effectively be blacklisted.
	BlacklistedCertificates map[string]*BlacklistedCertificate `protobuf:"bytes,8,rep,name=blacklisted_certificates,json=blacklistedCertificates,proto3" json:"blacklisted_certificates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// UnlockKeys defines the keys that lock node data at rest.  For example,
	// this would contain the key encrypting key (KEK) that will encrypt the
	// manager TLS keys at rest and the raft encryption keys at rest.
	// If the key is empty, the node will be unlocked (will not require a key
	// to start up from a shut down state).
	UnlockKeys []*EncryptionKey `protobuf:"bytes,9,rep,name=unlock_keys,json=unlockKeys,proto3" json:"unlock_keys,omitempty"`
	// FIPS specifies whether this cluster should be in FIPS mode.  This changes
	// the format of the join tokens, and nodes that are not FIPS-enabled should
	// reject joining the cluster.  Nodes that report themselves to be non-FIPS
	// should be rejected from the cluster.
	FIPS bool `protobuf:"varint,10,opt,name=fips,proto3" json:"fips,omitempty"`
	// This field specifies default subnet pools for global scope networks. If
	// unspecified, Docker will use the predefined subnets as it works on older releases.
	// Format Example : {"20.20.0.0/16",""20.20.0.0/16"}
	DefaultAddressPool []string `protobuf:"bytes,11,rep,name=defaultAddressPool,proto3" json:"defaultAddressPool,omitempty"`
	// This flag specifies the default subnet size of global scope networks by giving
	// the length of the subnet masks for every such network
	SubnetSize uint32 `protobuf:"varint,12,opt,name=subnetSize,proto3" json:"subnetSize,omitempty"`
	// VXLANUDPPort specifies the UDP port for VXLAN traffic.
	VXLANUDPPort uint32 `protobuf:"varint,13,opt,name=VXLANUDPPort,proto3" json:"VXLANUDPPort,omitempty"`
}

func (m *Cluster) Reset()                    { _ = "STUB: not implemented"; return }
func (*Cluster) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Cluster) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Cluster) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Cluster) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Cluster) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Cluster) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Cluster proto.InternalMessageInfo

// Secret represents a secret that should be passed to a container or a node,
// and is immutable.
type Secret struct {
	ID   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	// Spec contains the actual secret data, as well as any context around the
	// secret data that the user provides.
	Spec SecretSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// Whether the secret is an internal secret (not set by a user) or not.
	Internal bool `protobuf:"varint,4,opt,name=internal,proto3" json:"internal,omitempty"`
}

func (m *Secret) Reset()                    { _ = "STUB: not implemented"; return }
func (*Secret) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Secret) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Secret) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Secret) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Secret) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Secret) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Secret proto.InternalMessageInfo

// Config represents a set of configuration files that should be passed to a
// container.
type Config struct {
	ID   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	// Spec contains the actual config data, as well as any context around the
	// config data that the user provides.
	Spec ConfigSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
}

func (m *Config) Reset()                    { _ = "STUB: not implemented"; return }
func (*Config) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Config) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Config) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Config) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Config) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Config) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Config proto.InternalMessageInfo

// Resource is a top-level object with externally defined content and indexing.
// SwarmKit can serve as a store for these objects without understanding their
// meanings.
type Resource struct {
	ID          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta        Meta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	Annotations Annotations `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations"`
	// Kind identifies this class of object. It is essentially a namespace
	// to keep IDs or indices from colliding between unrelated Resource
	// objects. This must correspond to the name of an Extension.
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// Payload bytes. This data is not interpreted in any way by SwarmKit.
	// By convention, it should be a marshalled protocol buffers message.
	Payload *types.Any `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Resource) Reset()                    { _ = "STUB: not implemented"; return }
func (*Resource) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Resource) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Resource) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Resource) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Resource) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Resource) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Resource proto.InternalMessageInfo

// Extension declares a type of "resource" object. This message provides some
// metadata about the objects.
type Extension struct {
	ID          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta        Meta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	Annotations Annotations `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations"`
	Description string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *Extension) Reset()                    { _ = "STUB: not implemented"; return }
func (*Extension) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Extension) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Extension) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Extension) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Extension) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Extension) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Extension proto.InternalMessageInfo

// Volume is the top-level object describing a volume usable by Swarmkit. The
// Volume contains the user's VolumeSpec, the Volume's status, and the Volume
// object that was returned by the CSI Plugin when the volume was created.
type Volume struct {
	// ID is the swarmkit-internal ID for this volume object. This has no
	// relation to the CSI volume identifier provided by the CSI Plugin.
	ID   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta Meta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta"`
	// Spec is the desired state of the Volume, as provided by the user.
	Spec VolumeSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec"`
	// PublishStatus is the status of the volume as it pertains to the various
	// nodes it is in use on.
	PublishStatus []*VolumePublishStatus `protobuf:"bytes,4,rep,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	// VolumeInfo contains information about the volume originating from the
	// CSI plugin when the volume is created.
	VolumeInfo *VolumeInfo `protobuf:"bytes,5,opt,name=volume_info,json=volumeInfo,proto3" json:"volume_info,omitempty"`
	// PendingDelete indicates that this Volume is being removed from Swarm.
	// Before a Volume can be removed, we must call the DeleteVolume on the
	// Controller. Because of this, we cannot immediately remove the Volume
	// when a user wishes to delete it. Instead, we will mark a Volume with
	// PendingDelete = true, which instructs Swarm to go through the work of
	// removing the volume and then delete it when finished.
	PendingDelete bool `protobuf:"varint,6,opt,name=pending_delete,json=pendingDelete,proto3" json:"pending_delete,omitempty"`
}

func (m *Volume) Reset()                    { _ = "STUB: not implemented"; return }
func (*Volume) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Volume) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Volume) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Volume) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Volume) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Volume) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Volume proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Meta)(nil), "docker.swarmkit.v1.Meta")
	proto.RegisterType((*Node)(nil), "docker.swarmkit.v1.Node")
	proto.RegisterType((*Service)(nil), "docker.swarmkit.v1.Service")
	proto.RegisterType((*Endpoint)(nil), "docker.swarmkit.v1.Endpoint")
	proto.RegisterType((*Endpoint_VirtualIP)(nil), "docker.swarmkit.v1.Endpoint.VirtualIP")
	proto.RegisterType((*Task)(nil), "docker.swarmkit.v1.Task")
	proto.RegisterType((*NetworkAttachment)(nil), "docker.swarmkit.v1.NetworkAttachment")
	proto.RegisterMapType((map[string]string)(nil), "docker.swarmkit.v1.NetworkAttachment.DriverAttachmentOptsEntry")
	proto.RegisterType((*Network)(nil), "docker.swarmkit.v1.Network")
	proto.RegisterType((*Cluster)(nil), "docker.swarmkit.v1.Cluster")
	proto.RegisterMapType((map[string]*BlacklistedCertificate)(nil), "docker.swarmkit.v1.Cluster.BlacklistedCertificatesEntry")
	proto.RegisterType((*Secret)(nil), "docker.swarmkit.v1.Secret")
	proto.RegisterType((*Config)(nil), "docker.swarmkit.v1.Config")
	proto.RegisterType((*Resource)(nil), "docker.swarmkit.v1.Resource")
	proto.RegisterType((*Extension)(nil), "docker.swarmkit.v1.Extension")
	proto.RegisterType((*Volume)(nil), "docker.swarmkit.v1.Volume")
}

func init() {
	proto.RegisterFile("github.com/docker/swarmkit/api/objects.proto", fileDescriptor_6218a23329ef342d)
}

var fileDescriptor_6218a23329ef342d = []byte{
	// 1805 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x6f, 0x1b, 0xc7,
	0x15, 0xd7, 0x52, 0x2b, 0x7e, 0x3c, 0x7e, 0x54, 0x99, 0xa8, 0xea, 0x5a, 0x55, 0x29, 0x95, 0x49,
	0x5a, 0xc3, 0x30, 0xa8, 0xd4, 0x4d, 0x5b, 0x59, 0x4d, 0x62, 0x93, 0x92, 0xea, 0xb0, 0x89, 0x6d,
	0x61, 0x94, 0x38, 0xb9, 0x6d, 0x97, 0xbb, 0x23, 0x7a, 0xcd, 0xe5, 0xce, 0x62, 0x67, 0xc8, 0x84,
	0x3d, 0xf5, 0x6c, 0xa0, 0x40, 0x6f, 0xbe, 0xf5, 0x50, 0xf4, 0x9f, 0xe8, 0xa5, 0x87, 0x1e, 0x0a,
	0x1f, 0x73, 0x2a, 0x8c, 0x1e, 0x84, 0x9a, 0xfe, 0x1b, 0x7a, 0xe8, 0xad, 0x98, 0x8f, 0x25, 0x57,
	0xe6, 0xea, 0xab, 0x30, 0x84, 0x9e, 0xb8, 0x33, 0xf3, 0xfb, 0xbd, 0x79, 0xef, 0xcd, 0xbc, 0x8f,
	0x21, 0xdc, 0xec, 0xf9, 0xfc, 0xf1, 0xb0, 0xdb, 0x74, 0xe9, 0x60, 0xcb, 0xa3, 0x6e, 0x9f, 0xc4,
	0x5b, 0xec, 0x6b, 0x27, 0x1e, 0xf4, 0x7d, 0xbe, 0xe5, 0x44, 0xfe, 0x16, 0xed, 0x3e, 0x21, 0x2e,
	0x67, 0xcd, 0x28, 0xa6, 0x9c, 0x22, 0xa4, 0x20, 0xcd, 0x04, 0xd2, 0x1c, 0xfd, 0x64, 0xed, 0xc6,
	0x39, 0x12, 0xf8, 0x38, 0x22, 0x9a, 0x7f, 0x2e, 0x96, 0x45, 0xc4, 0x4d, 0xb0, 0x1b, 0x3d, 0x4a,
	0x7b, 0x01, 0xd9, 0x92, 0xa3, 0xee, 0xf0, 0x68, 0x8b, 0xfb, 0x03, 0xc2, 0xb8, 0x33, 0x88, 0x34,
	0x60, 0xa5, 0x47, 0x7b, 0x54, 0x7e, 0x6e, 0x89, 0x2f, 0x3d, 0x7b, 0xed, 0x75, 0x9a, 0x13, 0x8e,
	0xf5, 0xd2, 0x2f, 0xce, 0xd8, 0x7d, 0x0a, 0x8f, 0x82, 0x61, 0xcf, 0x0f, 0xf5, 0x8f, 0x22, 0x36,
	0xfe, 0x62, 0x80, 0x79, 0x9f, 0x70, 0x07, 0xfd, 0x12, 0x0a, 0x23, 0x12, 0x33, 0x9f, 0x86, 0x96,
	0xb1, 0x69, 0x5c, 0x2f, 0xdf, 0xfa, 0x7e, 0x73, 0xde, 0x23, 0xcd, 0x47, 0x0a, 0xd2, 0x36, 0x9f,
	0x1f, 0x6f, 0x2c, 0xe0, 0x84, 0x81, 0x6e, 0x03, 0xb8, 0x31, 0x71, 0x38, 0xf1, 0x6c, 0x87, 0x5b,
	0x39, 0xc9, 0x5f, 0x6b, 0x2a, 0x75, 0x9b, 0xc9, 0xfe, 0xcd, 0xcf, 0x13, 0x2b, 0x71, 0x49, 0xa3,
	0x5b, 0x5c, 0x50, 0x87, 0x91, 0x97, 0x50, 0x17, 0xcf, 0xa7, 0x6a, 0x74, 0x8b, 0x37, 0xfe, 0xbc,
	0x04, 0xe6, 0x03, 0xea, 0x11, 0xb4, 0x0a, 0x39, 0xdf, 0x93, 0x6a, 0x97, 0xda, 0xf9, 0xc9, 0xf1,
	0x46, 0xae, 0xb3, 0x87, 0x73, 0xbe, 0x87, 0x6e, 0x81, 0x39, 0x20, 0xdc, 0xd1, 0x0a, 0x59, 0x59,
	0x06, 0x09, 0xdb, 0xb5, 0x35, 0x12, 0x8b, 0x7e, 0x0e, 0xa6, 0x38, 0x2a, 0xad, 0xc9, 0x7a, 0x16,
	0x47, 0xec, 0x79, 0x18, 0x11, 0x37, 0xe1, 0x09, 0x3c, 0xda, 0x87, 0xb2, 0x47, 0x98, 0x1b, 0xfb,
	0x11, 0x17, 0x3e, 0x34, 0x25, 0xfd, 0x9d, 0xd3, 0xe8, 0x7b, 0x33, 0x28, 0x4e, 0xf3, 0xd0, 0x87,
	0x90, 0x67, 0xdc, 0xe1, 0x43, 0x66, 0x2d, 0x49, 0x09, 0xf5, 0x53, 0x15, 0x90, 0x28, 0xad, 0x82,
	0xe6, 0xa0, 0x4f, 0xa0, 0x36, 0x70, 0x42, 0xa7, 0x47, 0x62, 0x5b, 0x4b, 0xc9, 0x4b, 0x29, 0x3f,
	0xcc, 0x34, 0x5d, 0x21, 0x95, 0x20, 0x5c, 0x1d, 0xa4, 0x87, 0xa8, 0x03, 0xe0, 0x70, 0xee, 0xb8,
	0x8f, 0x07, 0x24, 0xe4, 0x56, 0x41, 0x4a, 0x79, 0x2f, 0x53, 0x17, 0xc2, 0xbf, 0xa6, 0x71, 0xbf,
	0x35, 0x05, 0xb7, 0x73, 0x96, 0x81, 0x53, 0x64, 0x74, 0x0f, 0xca, 0x2e, 0x89, 0xb9, 0x7f, 0xe4,
	0xbb, 0x0e, 0x27, 0x56, 0x51, 0xca, 0xda, 0xc8, 0x92, 0xb5, 0x3b, 0x83, 0x69, 0xc3, 0xd2, 0x4c,
	0xf4, 0x3e, 0x98, 0x31, 0x0d, 0x88, 0x55, 0xda, 0x34, 0xae, 0xd7, 0x4e, 0x3f, 0x1a, 0x4c, 0x03,
	0x82, 0x25, 0x52, 0x6c, 0x3d, 0x53, 0x84, 0x59, 0xb0, 0xb9, 0x78, 0x61, 0x33, 0x70, 0x9a, 0x89,
	0x1a, 0x50, 0x79, 0xf4, 0xd5, 0x67, 0xad, 0x07, 0x5f, 0xec, 0x1d, 0x1c, 0xd0, 0x98, 0x5b, 0xe5,
	0x4d, 0xe3, 0x7a, 0x15, 0x9f, 0x98, 0xdb, 0x59, 0x7d, 0xfa, 0xac, 0x81, 0x60, 0xb9, 0x68, 0x2c,
	0x1b, 0xf2, 0x2e, 0x1a, 0xef, 0x1b, 0x5f, 0x19, 0xbf, 0x31, 0x1a, 0x2f, 0x4d, 0x28, 0x1c, 0x92,
	0x78, 0xe4, 0xbb, 0x6f, 0xf6, 0xa6, 0xde, 0x3e, 0x71, 0x53, 0x33, 0x1d, 0xaa, 0xb7, 0x9d, 0xbb,
	0xac, 0x1f, 0x43, 0x45, 0xfc, 0xda, 0x49, 0xc4, 0xc3, 0xb9, 0x11, 0x8f, 0xcb, 0x82, 0xa0, 0x07,
	0x68, 0x0f, 0xaa, 0x51, 0x4c, 0x46, 0x3e, 0x1d, 0x32, 0x5b, 0xea, 0x90, 0xbf, 0x90, 0x0e, 0xb8,
	0x92, 0xb0, 0xc4, 0x08, 0x3d, 0x84, 0xef, 0x9e, 0x90, 0x32, 0x55, 0xa7, 0x7c, 0xbe, 0x3a, 0x6f,
	0xa7, 0x25, 0x25, 0x6a, 0x6d, 0x43, 0x91, 0x84, 0x5e, 0x44, 0xfd, 0x90, 0xeb, 0x00, 0xcc, 0xbc,
	0x24, 0xfb, 0x1a, 0x83, 0xa7, 0x68, 0xb4, 0x0f, 0x55, 0x95, 0x57, 0xec, 0x13, 0xd1, 0xb7, 0x99,
	0x45, 0xff, 0x42, 0x02, 0x75, 0xd8, 0x54, 0x86, 0xa9, 0x11, 0xfa, 0x10, 0xe0, 0x09, 0xed, 0x26,
	0x32, 0x2a, 0x52, 0xc6, 0x0f, 0xb2, 0x64, 0xfc, 0x9a, 0x76, 0xb5, 0x80, 0xd2, 0x93, 0xe4, 0x13,
	0xbd, 0x07, 0xb5, 0x88, 0x84, 0x9e, 0x1f, 0xf6, 0x6c, 0x8f, 0x04, 0x84, 0x13, 0x19, 0x77, 0x45,
	0x5c, 0xd5, 0xb3, 0x7b, 0x72, 0x72, 0x07, 0x3d, 0x7d, 0xd6, 0xa8, 0x41, 0x25, 0x7d, 0xcf, 0x1a,
	0x7f, 0xcc, 0x41, 0x31, 0x31, 0x0b, 0x7d, 0xa0, 0x2f, 0x86, 0x71, 0xba, 0x0d, 0x09, 0x56, 0x9e,
	0x8a, 0xba, 0x13, 0x1f, 0xc0, 0x52, 0x44, 0x63, 0xce, 0xac, 0x9c, 0x8c, 0x92, 0xcc, 0xc4, 0x23,
	0xee, 0xf9, 0x2e, 0x0d, 0x8f, 0xfc, 0x1e, 0x56, 0x60, 0xf4, 0x25, 0x94, 0x47, 0x7e, 0xcc, 0x87,
	0x4e, 0x60, 0xfb, 0x11, 0xb3, 0x16, 0x25, 0xf7, 0x47, 0x67, 0x6d, 0xd9, 0x7c, 0xa4, 0xf0, 0x9d,
	0x83, 0x76, 0x6d, 0x72, 0xbc, 0x01, 0xd3, 0x21, 0xc3, 0xa0, 0x45, 0x75, 0x22, 0xb6, 0x76, 0x1f,
	0x4a, 0xd3, 0x15, 0x74, 0x13, 0x20, 0x54, 0x01, 0x6a, 0x4f, 0xc3, 0xa7, 0x3a, 0x39, 0xde, 0x28,
	0xe9, 0xb0, 0xed, 0xec, 0xe1, 0x92, 0x06, 0x74, 0x3c, 0x84, 0xc0, 0x74, 0x3c, 0x2f, 0x96, 0xc1,
	0x54, 0xc2, 0xf2, 0xbb, 0xf1, 0xfb, 0x22, 0x98, 0x9f, 0x3b, 0xac, 0x7f, 0xd5, 0xb5, 0x42, 0xec,
	0x79, 0x6e, 0xf8, 0xd5, 0x2e, 0x19, 0x7e, 0x37, 0x01, 0x98, 0x8a, 0x2a, 0xe1, 0x0e, 0x73, 0xe6,
	0x0e, 0x1d, 0x6b, 0xc2, 0x1d, 0x1a, 0xa0, 0xdc, 0xc1, 0x02, 0xca, 0xe5, 0x95, 0x36, 0xb1, 0xfc,
	0x46, 0xef, 0x40, 0x21, 0xa4, 0x9e, 0xa4, 0xe7, 0x25, 0x1d, 0x26, 0xc7, 0x1b, 0x79, 0x91, 0x3d,
	0x3b, 0x7b, 0x38, 0x2f, 0x96, 0x3a, 0x9e, 0xcc, 0x9e, 0x61, 0x48, 0xb9, 0x23, 0x2a, 0x13, 0xd3,
	0x45, 0x20, 0x33, 0xc6, 0x5b, 0x33, 0x58, 0x92, 0xb8, 0x53, 0x4c, 0xf4, 0x08, 0xde, 0x4e, 0xf4,
	0x4d, 0x0b, 0x2c, 0x5e, 0x46, 0x20, 0xd2, 0x12, 0x52, 0x2b, 0xa9, 0x62, 0x59, 0x3a, 0xbd, 0x58,
	0xca, 0x13, 0xc8, 0x2a, 0x96, 0x6d, 0xa8, 0x7a, 0x84, 0xf9, 0x31, 0xf1, 0x64, 0xc0, 0x12, 0x99,
	0x05, 0x6b, 0xd9, 0xf1, 0x9a, 0x08, 0x21, 0xb8, 0xa2, 0x39, 0x72, 0x84, 0x5a, 0x50, 0xd4, 0xf7,
	0x8e, 0x59, 0xe5, 0xcb, 0x54, 0x97, 0x29, 0xed, 0x44, 0xd2, 0xaa, 0x5c, 0x2a, 0x69, 0xdd, 0x06,
	0x08, 0x68, 0xcf, 0xf6, 0x62, 0x7f, 0x44, 0x62, 0xab, 0xaa, 0x5b, 0xa7, 0x0c, 0xee, 0x9e, 0x44,
	0xe0, 0x52, 0x40, 0x7b, 0xea, 0x13, 0x39, 0xb0, 0xe6, 0x30, 0xe6, 0xf7, 0x42, 0xe2, 0xd9, 0x3d,
	0x12, 0x92, 0xd8, 0x77, 0xed, 0x98, 0x30, 0x3a, 0x8c, 0x5d, 0xc2, 0xac, 0xef, 0x48, 0x4b, 0x32,
	0x9b, 0x97, 0x7b, 0x0a, 0x8c, 0x35, 0x16, 0x5b, 0x89, 0x98, 0xd7, 0x16, 0x18, 0xba, 0x0b, 0x55,
	0x91, 0x0b, 0x7d, 0x4e, 0x62, 0x79, 0x5c, 0xd6, 0xf2, 0xf9, 0xb7, 0xbc, 0xf2, 0x84, 0x76, 0x3b,
	0x09, 0x01, 0x7d, 0x0c, 0x85, 0x11, 0x0d, 0x86, 0x03, 0xc2, 0xac, 0xb7, 0xa4, 0x46, 0xef, 0x66,
	0x72, 0x25, 0x24, 0xe5, 0xda, 0x84, 0xb4, 0xb3, 0xf6, 0xf4, 0x59, 0x63, 0x15, 0x56, 0xd2, 0x89,
	0x72, 0xdb, 0xb8, 0x6b, 0x7c, 0x62, 0x1c, 0x18, 0x8d, 0xbf, 0xe5, 0xe0, 0xad, 0xb9, 0x53, 0x41,
	0x3f, 0x83, 0x82, 0x3e, 0x97, 0xb3, 0x9a, 0x60, 0xcd, 0xc3, 0x09, 0x16, 0xad, 0x43, 0x49, 0x24,
	0x19, 0xc2, 0x18, 0x51, 0xe9, 0xb3, 0x84, 0x67, 0x13, 0xc8, 0x82, 0x82, 0x13, 0xf8, 0x8e, 0x58,
	0x5b, 0x94, 0x6b, 0xc9, 0x10, 0x0d, 0x61, 0x55, 0x1d, 0x9e, 0x3d, 0xeb, 0x35, 0x6c, 0x1a, 0x71,
	0x66, 0x99, 0xd2, 0xde, 0x3b, 0x17, 0xba, 0x4b, 0xfa, 0x78, 0x67, 0x13, 0x0f, 0x23, 0xce, 0xf6,
	0x43, 0x1e, 0x8f, 0xf1, 0x8a, 0x97, 0xb1, 0xb4, 0x76, 0x0f, 0xae, 0x9d, 0x4a, 0x41, 0xcb, 0xb0,
	0xd8, 0x27, 0x63, 0x95, 0x20, 0xb1, 0xf8, 0x44, 0x2b, 0xb0, 0x34, 0x72, 0x82, 0x21, 0xd1, 0xf9,
	0x54, 0x0d, 0x76, 0x72, 0xdb, 0x46, 0xe3, 0xdf, 0x39, 0x28, 0x68, 0x75, 0xae, 0xba, 0xb3, 0xd1,
	0xdb, 0xce, 0xa5, 0xd6, 0x8f, 0xa0, 0xa2, 0x5d, 0xaa, 0x62, 0xda, 0x3c, 0x37, 0x2a, 0xca, 0x0a,
	0xaf, 0xe2, 0xf9, 0x23, 0x30, 0xfd, 0xc8, 0x19, 0xe8, 0xf2, 0x9f, 0xb9, 0x73, 0xe7, 0xa0, 0x75,
	0xff, 0x61, 0xa4, 0x52, 0x53, 0x71, 0x72, 0xbc, 0x61, 0x8a, 0x09, 0x2c, 0x69, 0x19, 0x15, 0x3c,
	0x9f, 0x51, 0xc1, 0xd1, 0x0d, 0x58, 0x22, 0xdf, 0xf0, 0xd8, 0xd1, 0x29, 0x75, 0x65, 0xee, 0xb9,
	0xd3, 0x0a, 0xc7, 0x58, 0x41, 0x32, 0xab, 0xfd, 0xdf, 0xf3, 0x50, 0xd8, 0x0d, 0x86, 0x8c, 0x93,
	0xf8, 0xaa, 0xfd, 0xae, 0xb7, 0x9d, 0xf3, 0xfb, 0x2e, 0x14, 0x62, 0x4a, 0xb9, 0xed, 0x3a, 0x67,
	0xb9, 0x1c, 0x53, 0xca, 0x77, 0x5b, 0xed, 0x9a, 0x20, 0x8a, 0x82, 0xa3, 0xc6, 0x38, 0x2f, 0xa8,
	0xbb, 0x0e, 0xfa, 0x12, 0x56, 0x93, 0x32, 0xdf, 0xa5, 0x94, 0x33, 0x1e, 0x3b, 0x91, 0xdd, 0x27,
	0x63, 0xd1, 0x8e, 0x2d, 0x9e, 0xf6, 0x8c, 0xd9, 0x0f, 0xdd, 0x78, 0x2c, 0xcf, 0xe3, 0x53, 0x32,
	0xc6, 0x2b, 0x5a, 0x40, 0x3b, 0xe1, 0x7f, 0x4a, 0xc6, 0x0c, 0xdd, 0x81, 0x75, 0x32, 0x85, 0x09,
	0x89, 0x76, 0xe0, 0x0c, 0x44, 0x03, 0x63, 0xbb, 0x01, 0x75, 0xfb, 0xf2, 0x94, 0x4c, 0x7c, 0x8d,
	0xa4, 0x45, 0x7d, 0xa6, 0x10, 0xbb, 0x02, 0x80, 0x18, 0x58, 0xdd, 0xc0, 0x71, 0xfb, 0x81, 0xcf,
	0xc4, 0x4b, 0x35, 0xf5, 0x2a, 0x11, 0x65, 0x4c, 0xe8, 0xb6, 0x7d, 0x86, 0xb7, 0x9a, 0xed, 0x19,
	0x37, 0xf5, 0xc6, 0xd1, 0x41, 0xfa, 0xbd, 0x6e, 0xf6, 0x2a, 0x6a, 0x43, 0x79, 0x18, 0x8a, 0xed,
	0x95, 0x0f, 0x4a, 0x17, 0xf5, 0x01, 0x28, 0x96, 0xb4, 0x7c, 0x1d, 0xcc, 0x23, 0xd1, 0x98, 0x89,
	0xda, 0x56, 0x54, 0xf7, 0xf5, 0x57, 0x9d, 0x83, 0x43, 0x2c, 0x67, 0x51, 0x13, 0x90, 0x47, 0x8e,
	0x9c, 0x61, 0xc0, 0x5b, 0x2a, 0x5d, 0x1d, 0x50, 0x1a, 0xc8, 0x42, 0x56, 0xc2, 0x19, 0x2b, 0xa8,
	0x0e, 0xc0, 0x86, 0xdd, 0x90, 0xf0, 0x43, 0xff, 0xb7, 0x44, 0x56, 0xab, 0x2a, 0x4e, 0xcd, 0xcc,
	0x3d, 0x93, 0xaa, 0xf3, 0xcf, 0xa4, 0xb5, 0x11, 0xac, 0x9f, 0xe5, 0x8e, 0x8c, 0x04, 0x74, 0x37,
	0x9d, 0x80, 0xca, 0xb7, 0x6e, 0x64, 0x79, 0x20, 0x5b, 0x64, 0x2a, 0x59, 0x65, 0x06, 0xd2, 0x5f,
	0x0d, 0xc8, 0x1f, 0x12, 0x37, 0x26, 0xfc, 0x8d, 0xc6, 0xd1, 0xf6, 0x89, 0x38, 0xaa, 0x67, 0xbf,
	0x8a, 0xc4, 0xae, 0x73, 0x61, 0xb4, 0x06, 0x45, 0x3f, 0xe4, 0x24, 0x0e, 0x9d, 0x40, 0xc6, 0x51,
	0x11, 0x4f, 0xc7, 0x99, 0x06, 0xfc, 0xc9, 0x80, 0xbc, 0x6a, 0xc8, 0xaf, 0xda, 0x00, 0xb5, 0xeb,
	0xeb, 0x06, 0x64, 0x2a, 0xf9, 0x1f, 0x03, 0x8a, 0x49, 0x5f, 0xf0, 0x46, 0xd5, 0x7c, 0xad, 0x41,
	0x5d, 0xfc, 0x9f, 0x1b, 0x54, 0x04, 0x66, 0xdf, 0x0f, 0x75, 0x2b, 0x8d, 0xe5, 0x37, 0x6a, 0x42,
	0x21, 0x72, 0xc6, 0x01, 0x75, 0x3c, 0x5d, 0x0d, 0xb2, 0xd3, 0x74, 0x02, 0xda, 0x59, 0x79, 0xfa,
	0xac, 0xb1, 0x0c, 0xb5, 0xb4, 0xe5, 0x8f, 0x8d, 0xc6, 0x3f, 0x0c, 0x28, 0xed, 0x7f, 0xc3, 0x49,
	0x28, 0x1b, 0xf7, 0xff, 0x4b, 0xe3, 0x37, 0xe7, 0xff, 0xb9, 0x2a, 0x9d, 0xf8, 0x53, 0x2a, 0xf3,
	0x50, 0xff, 0x99, 0x83, 0xbc, 0x6a, 0xbd, 0xae, 0xfa, 0xe6, 0xa9, 0x5d, 0xe7, 0x42, 0xe7, 0x01,
	0xd4, 0xa2, 0x61, 0x37, 0xf0, 0xd9, 0xe3, 0xe4, 0xfd, 0xad, 0x9a, 0xa8, 0x1f, 0x9f, 0x2e, 0xe3,
	0x40, 0xe1, 0x93, 0x7f, 0xc0, 0xa2, 0xf4, 0x10, 0xdd, 0x81, 0xb2, 0x6a, 0x24, 0x6d, 0x3f, 0x3c,
	0xa2, 0x67, 0xfd, 0x1d, 0xa7, 0x84, 0x75, 0xc2, 0x23, 0x8a, 0x61, 0x34, 0xfd, 0xbe, 0x60, 0x33,
	0x90, 0xe5, 0xdc, 0xf6, 0xbb, 0xcf, 0x5f, 0xd6, 0x17, 0x5e, 0xbc, 0xac, 0x2f, 0xfc, 0x6e, 0x52,
	0x37, 0x9e, 0x4f, 0xea, 0xc6, 0xb7, 0x93, 0xba, 0xf1, 0xaf, 0x49, 0xdd, 0xf8, 0xc3, 0xab, 0xfa,
	0xc2, 0xb7, 0xaf, 0xea, 0x0b, 0x2f, 0x5e, 0xd5, 0x17, 0xba, 0x79, 0x79, 0x11, 0x7f, 0xfa, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xcf, 0x42, 0x61, 0xe9, 0x16, 0x00, 0x00,
}

func (m *Meta) Copy() *Meta { _ = "STUB: not implemented"; return nil }

func (m *Meta) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Node) Copy() *Node { _ = "STUB: not implemented"; return nil }

func (m *Node) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Service) Copy() *Service { _ = "STUB: not implemented"; return nil }

func (m *Service) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Endpoint) Copy() *Endpoint { _ = "STUB: not implemented"; return nil }

func (m *Endpoint) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Endpoint_VirtualIP) Copy() *Endpoint_VirtualIP { _ = "STUB: not implemented"; return nil }

func (m *Endpoint_VirtualIP) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Task) Copy() *Task { _ = "STUB: not implemented"; return nil }

func (m *Task) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *NetworkAttachment) Copy() *NetworkAttachment { _ = "STUB: not implemented"; return nil }

func (m *NetworkAttachment) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Network) Copy() *Network { _ = "STUB: not implemented"; return nil }

func (m *Network) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Cluster) Copy() *Cluster { _ = "STUB: not implemented"; return nil }

func (m *Cluster) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Secret) Copy() *Secret { _ = "STUB: not implemented"; return nil }

func (m *Secret) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Config) Copy() *Config { _ = "STUB: not implemented"; return nil }

func (m *Config) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Resource) Copy() *Resource { _ = "STUB: not implemented"; return nil }

func (m *Resource) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Extension) Copy() *Extension { _ = "STUB: not implemented"; return nil }

func (m *Extension) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Volume) Copy() *Volume { _ = "STUB: not implemented"; return nil }

func (m *Volume) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *Meta) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Meta) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Meta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Node) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Node) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Node) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Service) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Service) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Service) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Endpoint) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Endpoint) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Endpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Endpoint_VirtualIP) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Endpoint_VirtualIP) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Endpoint_VirtualIP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Task) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Task) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NetworkAttachment) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NetworkAttachment) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NetworkAttachment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Network) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Network) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Network) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Cluster) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Cluster) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Cluster) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Secret) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Secret) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Secret) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Config) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Config) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Resource) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Resource) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Resource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Extension) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Extension) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Extension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Volume) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Volume) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Volume) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintObjects(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Meta) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Node) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Service) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Endpoint) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Endpoint_VirtualIP) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Task) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NetworkAttachment) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Network) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Cluster) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Secret) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Config) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Resource) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Extension) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Volume) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovObjects(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozObjects(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

type NodeCheckFunc func(t1, t2 *Node) bool

type EventNode interface {
	IsEventNode() bool
}

type EventCreateNode struct {
	Node   *Node
	Checks []NodeCheckFunc
}

func (e EventCreateNode) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateNode) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateNode) IsEventNode() bool { _ = "STUB: not implemented"; return false }

type EventUpdateNode struct {
	Node    *Node
	OldNode *Node
	Checks  []NodeCheckFunc
}

func (e EventUpdateNode) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateNode) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateNode) IsEventNode() bool { _ = "STUB: not implemented"; return false }

type EventDeleteNode struct {
	Node   *Node
	Checks []NodeCheckFunc
}

func (e EventDeleteNode) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteNode) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteNode) IsEventNode() bool { _ = "STUB: not implemented"; return false }

func (m *Node) CopyStoreObject() StoreObject { _ = "STUB: not implemented"; return *new(StoreObject) }

func (m *Node) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Node) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Node) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Node) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Node) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Node) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func NodeCheckID(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckIDPrefix(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckName(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckNamePrefix(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckCustom(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckCustomPrefix(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckRole(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func NodeCheckMembership(v1, v2 *Node) bool { _ = "STUB: not implemented"; return false }

func ConvertNodeWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type NodeIndexerByID struct{}

func (indexer NodeIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NodeIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NodeIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type NodeIndexerByName struct{}

func (indexer NodeIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NodeIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NodeIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type NodeCustomIndexer struct{}

func (indexer NodeCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NodeCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NodeCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ServiceCheckFunc func(t1, t2 *Service) bool

type EventService interface {
	IsEventService() bool
}

type EventCreateService struct {
	Service *Service
	Checks  []ServiceCheckFunc
}

func (e EventCreateService) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateService) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateService) IsEventService() bool { _ = "STUB: not implemented"; return false }

type EventUpdateService struct {
	Service    *Service
	OldService *Service
	Checks     []ServiceCheckFunc
}

func (e EventUpdateService) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateService) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateService) IsEventService() bool { _ = "STUB: not implemented"; return false }

type EventDeleteService struct {
	Service *Service
	Checks  []ServiceCheckFunc
}

func (e EventDeleteService) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteService) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteService) IsEventService() bool { _ = "STUB: not implemented"; return false }

func (m *Service) CopyStoreObject() StoreObject {
	_ = "STUB: not implemented"
	return *new(StoreObject)
}

func (m *Service) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Service) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Service) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Service) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Service) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Service) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func ServiceCheckID(v1, v2 *Service) bool { _ = "STUB: not implemented"; return false }

func ServiceCheckIDPrefix(v1, v2 *Service) bool { _ = "STUB: not implemented"; return false }

func ServiceCheckName(v1, v2 *Service) bool { _ = "STUB: not implemented"; return false }

func ServiceCheckNamePrefix(v1, v2 *Service) bool { _ = "STUB: not implemented"; return false }

func ServiceCheckCustom(v1, v2 *Service) bool { _ = "STUB: not implemented"; return false }

func ServiceCheckCustomPrefix(v1, v2 *Service) bool { _ = "STUB: not implemented"; return false }

func ConvertServiceWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ServiceIndexerByID struct{}

func (indexer ServiceIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ServiceIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ServiceIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ServiceIndexerByName struct{}

func (indexer ServiceIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ServiceIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ServiceIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ServiceCustomIndexer struct{}

func (indexer ServiceCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ServiceCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ServiceCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type TaskCheckFunc func(t1, t2 *Task) bool

type EventTask interface {
	IsEventTask() bool
}

type EventCreateTask struct {
	Task   *Task
	Checks []TaskCheckFunc
}

func (e EventCreateTask) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateTask) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateTask) IsEventTask() bool { _ = "STUB: not implemented"; return false }

type EventUpdateTask struct {
	Task    *Task
	OldTask *Task
	Checks  []TaskCheckFunc
}

func (e EventUpdateTask) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateTask) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateTask) IsEventTask() bool { _ = "STUB: not implemented"; return false }

type EventDeleteTask struct {
	Task   *Task
	Checks []TaskCheckFunc
}

func (e EventDeleteTask) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteTask) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteTask) IsEventTask() bool { _ = "STUB: not implemented"; return false }

func (m *Task) CopyStoreObject() StoreObject { _ = "STUB: not implemented"; return *new(StoreObject) }

func (m *Task) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Task) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Task) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Task) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Task) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Task) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func TaskCheckID(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckIDPrefix(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckName(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckNamePrefix(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckCustom(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckCustomPrefix(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckNodeID(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckServiceID(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckSlot(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func TaskCheckDesiredState(v1, v2 *Task) bool { _ = "STUB: not implemented"; return false }

func ConvertTaskWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type TaskIndexerByID struct{}

func (indexer TaskIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer TaskIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer TaskIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type TaskIndexerByName struct{}

func (indexer TaskIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer TaskIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer TaskIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type TaskCustomIndexer struct{}

func (indexer TaskCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer TaskCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer TaskCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type NetworkCheckFunc func(t1, t2 *Network) bool

type EventNetwork interface {
	IsEventNetwork() bool
}

type EventCreateNetwork struct {
	Network *Network
	Checks  []NetworkCheckFunc
}

func (e EventCreateNetwork) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateNetwork) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateNetwork) IsEventNetwork() bool { _ = "STUB: not implemented"; return false }

type EventUpdateNetwork struct {
	Network    *Network
	OldNetwork *Network
	Checks     []NetworkCheckFunc
}

func (e EventUpdateNetwork) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateNetwork) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateNetwork) IsEventNetwork() bool { _ = "STUB: not implemented"; return false }

type EventDeleteNetwork struct {
	Network *Network
	Checks  []NetworkCheckFunc
}

func (e EventDeleteNetwork) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteNetwork) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteNetwork) IsEventNetwork() bool { _ = "STUB: not implemented"; return false }

func (m *Network) CopyStoreObject() StoreObject {
	_ = "STUB: not implemented"
	return *new(StoreObject)
}

func (m *Network) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Network) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Network) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Network) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Network) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Network) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func NetworkCheckID(v1, v2 *Network) bool { _ = "STUB: not implemented"; return false }

func NetworkCheckIDPrefix(v1, v2 *Network) bool { _ = "STUB: not implemented"; return false }

func NetworkCheckName(v1, v2 *Network) bool { _ = "STUB: not implemented"; return false }

func NetworkCheckNamePrefix(v1, v2 *Network) bool { _ = "STUB: not implemented"; return false }

func NetworkCheckCustom(v1, v2 *Network) bool { _ = "STUB: not implemented"; return false }

func NetworkCheckCustomPrefix(v1, v2 *Network) bool { _ = "STUB: not implemented"; return false }

func ConvertNetworkWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type NetworkIndexerByID struct{}

func (indexer NetworkIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NetworkIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NetworkIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type NetworkIndexerByName struct{}

func (indexer NetworkIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NetworkIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NetworkIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type NetworkCustomIndexer struct{}

func (indexer NetworkCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NetworkCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer NetworkCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ClusterCheckFunc func(t1, t2 *Cluster) bool

type EventCluster interface {
	IsEventCluster() bool
}

type EventCreateCluster struct {
	Cluster *Cluster
	Checks  []ClusterCheckFunc
}

func (e EventCreateCluster) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateCluster) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateCluster) IsEventCluster() bool { _ = "STUB: not implemented"; return false }

type EventUpdateCluster struct {
	Cluster    *Cluster
	OldCluster *Cluster
	Checks     []ClusterCheckFunc
}

func (e EventUpdateCluster) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateCluster) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateCluster) IsEventCluster() bool { _ = "STUB: not implemented"; return false }

type EventDeleteCluster struct {
	Cluster *Cluster
	Checks  []ClusterCheckFunc
}

func (e EventDeleteCluster) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteCluster) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteCluster) IsEventCluster() bool { _ = "STUB: not implemented"; return false }

func (m *Cluster) CopyStoreObject() StoreObject {
	_ = "STUB: not implemented"
	return *new(StoreObject)
}

func (m *Cluster) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Cluster) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Cluster) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Cluster) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Cluster) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Cluster) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func ClusterCheckID(v1, v2 *Cluster) bool { _ = "STUB: not implemented"; return false }

func ClusterCheckIDPrefix(v1, v2 *Cluster) bool { _ = "STUB: not implemented"; return false }

func ClusterCheckName(v1, v2 *Cluster) bool { _ = "STUB: not implemented"; return false }

func ClusterCheckNamePrefix(v1, v2 *Cluster) bool { _ = "STUB: not implemented"; return false }

func ClusterCheckCustom(v1, v2 *Cluster) bool { _ = "STUB: not implemented"; return false }

func ClusterCheckCustomPrefix(v1, v2 *Cluster) bool { _ = "STUB: not implemented"; return false }

func ConvertClusterWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ClusterIndexerByID struct{}

func (indexer ClusterIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ClusterIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ClusterIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ClusterIndexerByName struct{}

func (indexer ClusterIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ClusterIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ClusterIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ClusterCustomIndexer struct{}

func (indexer ClusterCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ClusterCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ClusterCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type SecretCheckFunc func(t1, t2 *Secret) bool

type EventSecret interface {
	IsEventSecret() bool
}

type EventCreateSecret struct {
	Secret *Secret
	Checks []SecretCheckFunc
}

func (e EventCreateSecret) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateSecret) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateSecret) IsEventSecret() bool { _ = "STUB: not implemented"; return false }

type EventUpdateSecret struct {
	Secret    *Secret
	OldSecret *Secret
	Checks    []SecretCheckFunc
}

func (e EventUpdateSecret) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateSecret) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateSecret) IsEventSecret() bool { _ = "STUB: not implemented"; return false }

type EventDeleteSecret struct {
	Secret *Secret
	Checks []SecretCheckFunc
}

func (e EventDeleteSecret) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteSecret) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteSecret) IsEventSecret() bool { _ = "STUB: not implemented"; return false }

func (m *Secret) CopyStoreObject() StoreObject { _ = "STUB: not implemented"; return *new(StoreObject) }

func (m *Secret) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Secret) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Secret) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Secret) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Secret) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Secret) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func SecretCheckID(v1, v2 *Secret) bool { _ = "STUB: not implemented"; return false }

func SecretCheckIDPrefix(v1, v2 *Secret) bool { _ = "STUB: not implemented"; return false }

func SecretCheckName(v1, v2 *Secret) bool { _ = "STUB: not implemented"; return false }

func SecretCheckNamePrefix(v1, v2 *Secret) bool { _ = "STUB: not implemented"; return false }

func SecretCheckCustom(v1, v2 *Secret) bool { _ = "STUB: not implemented"; return false }

func SecretCheckCustomPrefix(v1, v2 *Secret) bool { _ = "STUB: not implemented"; return false }

func ConvertSecretWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type SecretIndexerByID struct{}

func (indexer SecretIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer SecretIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer SecretIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type SecretIndexerByName struct{}

func (indexer SecretIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer SecretIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer SecretIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type SecretCustomIndexer struct{}

func (indexer SecretCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer SecretCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer SecretCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ConfigCheckFunc func(t1, t2 *Config) bool

type EventConfig interface {
	IsEventConfig() bool
}

type EventCreateConfig struct {
	Config *Config
	Checks []ConfigCheckFunc
}

func (e EventCreateConfig) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateConfig) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateConfig) IsEventConfig() bool { _ = "STUB: not implemented"; return false }

type EventUpdateConfig struct {
	Config    *Config
	OldConfig *Config
	Checks    []ConfigCheckFunc
}

func (e EventUpdateConfig) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateConfig) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateConfig) IsEventConfig() bool { _ = "STUB: not implemented"; return false }

type EventDeleteConfig struct {
	Config *Config
	Checks []ConfigCheckFunc
}

func (e EventDeleteConfig) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteConfig) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteConfig) IsEventConfig() bool { _ = "STUB: not implemented"; return false }

func (m *Config) CopyStoreObject() StoreObject { _ = "STUB: not implemented"; return *new(StoreObject) }

func (m *Config) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Config) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Config) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Config) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Config) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Config) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func ConfigCheckID(v1, v2 *Config) bool { _ = "STUB: not implemented"; return false }

func ConfigCheckIDPrefix(v1, v2 *Config) bool { _ = "STUB: not implemented"; return false }

func ConfigCheckName(v1, v2 *Config) bool { _ = "STUB: not implemented"; return false }

func ConfigCheckNamePrefix(v1, v2 *Config) bool { _ = "STUB: not implemented"; return false }

func ConfigCheckCustom(v1, v2 *Config) bool { _ = "STUB: not implemented"; return false }

func ConfigCheckCustomPrefix(v1, v2 *Config) bool { _ = "STUB: not implemented"; return false }

func ConvertConfigWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ConfigIndexerByID struct{}

func (indexer ConfigIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ConfigIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ConfigIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ConfigIndexerByName struct{}

func (indexer ConfigIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ConfigIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ConfigIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ConfigCustomIndexer struct{}

func (indexer ConfigCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ConfigCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ConfigCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ResourceCheckFunc func(t1, t2 *Resource) bool

type EventResource interface {
	IsEventResource() bool
}

type EventCreateResource struct {
	Resource *Resource
	Checks   []ResourceCheckFunc
}

func (e EventCreateResource) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateResource) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateResource) IsEventResource() bool { _ = "STUB: not implemented"; return false }

type EventUpdateResource struct {
	Resource    *Resource
	OldResource *Resource
	Checks      []ResourceCheckFunc
}

func (e EventUpdateResource) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateResource) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateResource) IsEventResource() bool { _ = "STUB: not implemented"; return false }

type EventDeleteResource struct {
	Resource *Resource
	Checks   []ResourceCheckFunc
}

func (e EventDeleteResource) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteResource) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteResource) IsEventResource() bool { _ = "STUB: not implemented"; return false }

func (m *Resource) CopyStoreObject() StoreObject {
	_ = "STUB: not implemented"
	return *new(StoreObject)
}

func (m *Resource) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Resource) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Resource) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Resource) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Resource) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Resource) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func ResourceCheckID(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ResourceCheckIDPrefix(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ResourceCheckName(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ResourceCheckNamePrefix(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ResourceCheckCustom(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ResourceCheckCustomPrefix(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ResourceCheckKind(v1, v2 *Resource) bool { _ = "STUB: not implemented"; return false }

func ConvertResourceWatch(action WatchActionKind, filters []*SelectBy, kind string) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ResourceIndexerByID struct{}

func (indexer ResourceIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ResourceIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ResourceIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ResourceIndexerByName struct{}

func (indexer ResourceIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ResourceIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ResourceIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ResourceCustomIndexer struct{}

func (indexer ResourceCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ResourceCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ResourceCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ExtensionCheckFunc func(t1, t2 *Extension) bool

type EventExtension interface {
	IsEventExtension() bool
}

type EventCreateExtension struct {
	Extension *Extension
	Checks    []ExtensionCheckFunc
}

func (e EventCreateExtension) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateExtension) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateExtension) IsEventExtension() bool { _ = "STUB: not implemented"; return false }

type EventUpdateExtension struct {
	Extension    *Extension
	OldExtension *Extension
	Checks       []ExtensionCheckFunc
}

func (e EventUpdateExtension) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateExtension) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateExtension) IsEventExtension() bool { _ = "STUB: not implemented"; return false }

type EventDeleteExtension struct {
	Extension *Extension
	Checks    []ExtensionCheckFunc
}

func (e EventDeleteExtension) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteExtension) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteExtension) IsEventExtension() bool { _ = "STUB: not implemented"; return false }

func (m *Extension) CopyStoreObject() StoreObject {
	_ = "STUB: not implemented"
	return *new(StoreObject)
}

func (m *Extension) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Extension) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Extension) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Extension) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Extension) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Extension) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func ExtensionCheckID(v1, v2 *Extension) bool { _ = "STUB: not implemented"; return false }

func ExtensionCheckIDPrefix(v1, v2 *Extension) bool { _ = "STUB: not implemented"; return false }

func ExtensionCheckName(v1, v2 *Extension) bool { _ = "STUB: not implemented"; return false }

func ExtensionCheckNamePrefix(v1, v2 *Extension) bool { _ = "STUB: not implemented"; return false }

func ExtensionCheckCustom(v1, v2 *Extension) bool { _ = "STUB: not implemented"; return false }

func ExtensionCheckCustomPrefix(v1, v2 *Extension) bool { _ = "STUB: not implemented"; return false }

func ConvertExtensionWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ExtensionIndexerByID struct{}

func (indexer ExtensionIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ExtensionIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ExtensionIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ExtensionIndexerByName struct{}

func (indexer ExtensionIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ExtensionIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ExtensionIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type ExtensionCustomIndexer struct{}

func (indexer ExtensionCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ExtensionCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer ExtensionCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type VolumeCheckFunc func(t1, t2 *Volume) bool

type EventVolume interface {
	IsEventVolume() bool
}

type EventCreateVolume struct {
	Volume *Volume
	Checks []VolumeCheckFunc
}

func (e EventCreateVolume) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventCreateVolume) IsEventCreate() bool { _ = "STUB: not implemented"; return false }

func (e EventCreateVolume) IsEventVolume() bool { _ = "STUB: not implemented"; return false }

type EventUpdateVolume struct {
	Volume    *Volume
	OldVolume *Volume
	Checks    []VolumeCheckFunc
}

func (e EventUpdateVolume) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventUpdateVolume) IsEventUpdate() bool { _ = "STUB: not implemented"; return false }

func (e EventUpdateVolume) IsEventVolume() bool { _ = "STUB: not implemented"; return false }

type EventDeleteVolume struct {
	Volume *Volume
	Checks []VolumeCheckFunc
}

func (e EventDeleteVolume) Matches(apiEvent github_com_docker_go_events.Event) bool {
	_ = "STUB: not implemented"
	return false
}

func (e EventDeleteVolume) IsEventDelete() bool { _ = "STUB: not implemented"; return false }

func (e EventDeleteVolume) IsEventVolume() bool { _ = "STUB: not implemented"; return false }

func (m *Volume) CopyStoreObject() StoreObject { _ = "STUB: not implemented"; return *new(StoreObject) }

func (m *Volume) GetMeta() Meta { _ = "STUB: not implemented"; return *new(Meta) }

func (m *Volume) SetMeta(meta Meta) { _ = "STUB: not implemented"; return }

func (m *Volume) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *Volume) EventCreate() Event { _ = "STUB: not implemented"; return *new(Event) }

func (m *Volume) EventUpdate(oldObject StoreObject) Event {
	_ = "STUB: not implemented"
	return *new(Event)
}

func (m *Volume) EventDelete() Event { _ = "STUB: not implemented"; return *new(Event) }

func VolumeCheckID(v1, v2 *Volume) bool { _ = "STUB: not implemented"; return false }

func VolumeCheckIDPrefix(v1, v2 *Volume) bool { _ = "STUB: not implemented"; return false }

func VolumeCheckName(v1, v2 *Volume) bool { _ = "STUB: not implemented"; return false }

func VolumeCheckNamePrefix(v1, v2 *Volume) bool { _ = "STUB: not implemented"; return false }

func VolumeCheckCustom(v1, v2 *Volume) bool { _ = "STUB: not implemented"; return false }

func VolumeCheckCustomPrefix(v1, v2 *Volume) bool { _ = "STUB: not implemented"; return false }

func ConvertVolumeWatch(action WatchActionKind, filters []*SelectBy) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type VolumeIndexerByID struct{}

func (indexer VolumeIndexerByID) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer VolumeIndexerByID) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer VolumeIndexerByID) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type VolumeIndexerByName struct{}

func (indexer VolumeIndexerByName) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer VolumeIndexerByName) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer VolumeIndexerByName) FromObject(obj interface{}) (bool, []byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

type VolumeCustomIndexer struct{}

func (indexer VolumeCustomIndexer) FromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer VolumeCustomIndexer) PrefixFromArgs(args ...interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (indexer VolumeCustomIndexer) FromObject(obj interface{}) (bool, [][]byte, error) {
	_ = "STUB: not implemented"
	return false, nil, nil
}

func NewStoreAction(c Event) (StoreAction, error) {
	_ = "STUB: not implemented"
	return *new(StoreAction), nil
}

func EventFromStoreAction(sa StoreAction, oldObject StoreObject) (Event, error) {
	_ = "STUB: not implemented"
	return *new(Event), nil
}

func WatchMessageEvent(c Event) *WatchMessage_Event { _ = "STUB: not implemented"; return nil }

func ConvertWatchArgs(entries []*WatchRequest_WatchEntry) ([]Event, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (this *Meta) String() string { _ = "STUB: not implemented"; return "" }

func (this *Node) String() string { _ = "STUB: not implemented"; return "" }

func (this *Service) String() string { _ = "STUB: not implemented"; return "" }

func (this *Endpoint) String() string { _ = "STUB: not implemented"; return "" }

func (this *Endpoint_VirtualIP) String() string { _ = "STUB: not implemented"; return "" }

func (this *Task) String() string { _ = "STUB: not implemented"; return "" }

func (this *NetworkAttachment) String() string { _ = "STUB: not implemented"; return "" }

func (this *Network) String() string { _ = "STUB: not implemented"; return "" }

func (this *Cluster) String() string { _ = "STUB: not implemented"; return "" }

func (this *Secret) String() string { _ = "STUB: not implemented"; return "" }

func (this *Config) String() string { _ = "STUB: not implemented"; return "" }

func (this *Resource) String() string { _ = "STUB: not implemented"; return "" }

func (this *Extension) String() string { _ = "STUB: not implemented"; return "" }

func (this *Volume) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringObjects(v interface{}) string { _ = "STUB: not implemented"; return "" }

func (m *Meta) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Node) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Service) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Endpoint) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Endpoint_VirtualIP) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Task) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NetworkAttachment) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Network) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Cluster) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Secret) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Config) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Resource) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Extension) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Volume) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipObjects(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthObjects        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowObjects          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupObjects = fmt.Errorf("proto: unexpected end of group")
)
