// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/swarmkit/api/raft.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	raftselector "github.com/moby/swarmkit/v2/manager/raftselector"
	raftpb "go.etcd.io/raft/v3/raftpb"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StoreActionKind defines the operation to take on the store for the target of
// a storage action.
type StoreActionKind int32

const (
	StoreActionKindUnknown StoreActionKind = 0
	StoreActionKindCreate  StoreActionKind = 1
	StoreActionKindUpdate  StoreActionKind = 2
	StoreActionKindRemove  StoreActionKind = 3
)

var StoreActionKind_name = map[int32]string{
	0: "UNKNOWN",
	1: "STORE_ACTION_CREATE",
	2: "STORE_ACTION_UPDATE",
	3: "STORE_ACTION_REMOVE",
}

var StoreActionKind_value = map[string]int32{
	"UNKNOWN":             0,
	"STORE_ACTION_CREATE": 1,
	"STORE_ACTION_UPDATE": 2,
	"STORE_ACTION_REMOVE": 3,
}

func (x StoreActionKind) String() string { _ = "STUB: not implemented"; return "" }

func (StoreActionKind) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type RaftMember struct {
	// RaftID specifies the internal ID used by the manager in a raft context, it can never be modified
	// and is used only for information purposes
	RaftID uint64 `protobuf:"varint,1,opt,name=raft_id,json=raftId,proto3" json:"raft_id,omitempty"`
	// NodeID is the node's ID.
	NodeID string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Addr specifies the address of the member
	Addr string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	// Status provides the current status of the manager from the perspective of another manager.
	Status RaftMemberStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status"`
}

func (m *RaftMember) Reset()                    { _ = "STUB: not implemented"; return }
func (*RaftMember) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RaftMember) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftMember) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RaftMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftMember) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RaftMember) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RaftMember) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RaftMember proto.InternalMessageInfo

type JoinRequest struct {
	// Addr specifies the address of the member
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (m *JoinRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*JoinRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*JoinRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *JoinRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *JoinRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *JoinRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *JoinRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

type JoinResponse struct {
	// RaftID is the ID assigned to the new member.
	RaftID uint64 `protobuf:"varint,1,opt,name=raft_id,json=raftId,proto3" json:"raft_id,omitempty"`
	// Members is the membership set of the cluster.
	Members []*RaftMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	// RemovedMembers is a list of members that have been removed from
	// the cluster, so the new node can avoid communicating with them.
	RemovedMembers []uint64 `protobuf:"varint,3,rep,name=removed_members,json=removedMembers,proto3" json:"removed_members,omitempty"`
}

func (m *JoinResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (*JoinResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*JoinResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *JoinResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *JoinResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *JoinResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *JoinResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

type LeaveRequest struct {
	Node *RaftMember `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (m *LeaveRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*LeaveRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*LeaveRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *LeaveRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LeaveRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LeaveRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LeaveRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LeaveRequest proto.InternalMessageInfo

type LeaveResponse struct {
}

func (m *LeaveResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (*LeaveResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*LeaveResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *LeaveResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LeaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LeaveResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LeaveResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LeaveResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LeaveResponse proto.InternalMessageInfo

type ProcessRaftMessageRequest struct {
	Message *raftpb.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *ProcessRaftMessageRequest) Reset()      { _ = "STUB: not implemented"; return }
func (*ProcessRaftMessageRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*ProcessRaftMessageRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProcessRaftMessageRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProcessRaftMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProcessRaftMessageRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProcessRaftMessageRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProcessRaftMessageRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProcessRaftMessageRequest proto.InternalMessageInfo

type ProcessRaftMessageResponse struct {
}

func (m *ProcessRaftMessageResponse) Reset()      { _ = "STUB: not implemented"; return }
func (*ProcessRaftMessageResponse) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*ProcessRaftMessageResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProcessRaftMessageResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProcessRaftMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProcessRaftMessageResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *ProcessRaftMessageResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProcessRaftMessageResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProcessRaftMessageResponse proto.InternalMessageInfo

// Raft message streaming request.
type StreamRaftMessageRequest struct {
	Message *raftpb.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *StreamRaftMessageRequest) Reset()      { _ = "STUB: not implemented"; return }
func (*StreamRaftMessageRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*StreamRaftMessageRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamRaftMessageRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *StreamRaftMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamRaftMessageRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StreamRaftMessageRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StreamRaftMessageRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StreamRaftMessageRequest proto.InternalMessageInfo

// Raft message streaming response.
type StreamRaftMessageResponse struct {
}

func (m *StreamRaftMessageResponse) Reset()      { _ = "STUB: not implemented"; return }
func (*StreamRaftMessageResponse) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*StreamRaftMessageResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamRaftMessageResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *StreamRaftMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamRaftMessageResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StreamRaftMessageResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StreamRaftMessageResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StreamRaftMessageResponse proto.InternalMessageInfo

type ResolveAddressRequest struct {
	// raft_id is the ID to resolve to an address.
	RaftID uint64 `protobuf:"varint,1,opt,name=raft_id,json=raftId,proto3" json:"raft_id,omitempty"`
}

func (m *ResolveAddressRequest) Reset()      { _ = "STUB: not implemented"; return }
func (*ResolveAddressRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*ResolveAddressRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResolveAddressRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResolveAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResolveAddressRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ResolveAddressRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ResolveAddressRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ResolveAddressRequest proto.InternalMessageInfo

type ResolveAddressResponse struct {
	// Addr specifies the address of the member
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (m *ResolveAddressResponse) Reset()      { _ = "STUB: not implemented"; return }
func (*ResolveAddressResponse) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*ResolveAddressResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResolveAddressResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResolveAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResolveAddressResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ResolveAddressResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ResolveAddressResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ResolveAddressResponse proto.InternalMessageInfo

// Contains one of many protobuf encoded objects to replicate
// over the raft backend with a request ID to track when the
// action is effectively applied
type InternalRaftRequest struct {
	ID     uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action []StoreAction `protobuf:"bytes,2,rep,name=action,proto3" json:"action"`
}

func (m *InternalRaftRequest) Reset()      { _ = "STUB: not implemented"; return }
func (*InternalRaftRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*InternalRaftRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InternalRaftRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InternalRaftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InternalRaftRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *InternalRaftRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *InternalRaftRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_InternalRaftRequest proto.InternalMessageInfo

// StoreAction defines a target and operation to apply on the storage system.
type StoreAction struct {
	Action StoreActionKind `protobuf:"varint,1,opt,name=action,proto3,enum=docker.swarmkit.v1.StoreActionKind" json:"action,omitempty"`
	// Types that are valid to be assigned to Target:
	//	*StoreAction_Node
	//	*StoreAction_Service
	//	*StoreAction_Task
	//	*StoreAction_Network
	//	*StoreAction_Cluster
	//	*StoreAction_Secret
	//	*StoreAction_Resource
	//	*StoreAction_Extension
	//	*StoreAction_Config
	//	*StoreAction_Volume
	Target isStoreAction_Target `protobuf_oneof:"target"`
}

func (m *StoreAction) Reset()                    { _ = "STUB: not implemented"; return }
func (*StoreAction) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*StoreAction) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *StoreAction) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StoreAction) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StoreAction) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StoreAction proto.InternalMessageInfo

type isStoreAction_Target interface {
	isStoreAction_Target()
	MarshalTo([]byte) (int, error)
	Size() int
}

type StoreAction_Node struct {
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3,oneof" json:"node,omitempty"`
}
type StoreAction_Service struct {
	Service *Service `protobuf:"bytes,3,opt,name=service,proto3,oneof" json:"service,omitempty"`
}
type StoreAction_Task struct {
	Task *Task `protobuf:"bytes,4,opt,name=task,proto3,oneof" json:"task,omitempty"`
}
type StoreAction_Network struct {
	Network *Network `protobuf:"bytes,5,opt,name=network,proto3,oneof" json:"network,omitempty"`
}
type StoreAction_Cluster struct {
	Cluster *Cluster `protobuf:"bytes,6,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
}
type StoreAction_Secret struct {
	Secret *Secret `protobuf:"bytes,7,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
}
type StoreAction_Resource struct {
	Resource *Resource `protobuf:"bytes,8,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
}
type StoreAction_Extension struct {
	Extension *Extension `protobuf:"bytes,9,opt,name=extension,proto3,oneof" json:"extension,omitempty"`
}
type StoreAction_Config struct {
	Config *Config `protobuf:"bytes,10,opt,name=config,proto3,oneof" json:"config,omitempty"`
}
type StoreAction_Volume struct {
	Volume *Volume `protobuf:"bytes,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
}

func (*StoreAction_Node) isStoreAction_Target()      { _ = "STUB: not implemented"; return }
func (*StoreAction_Service) isStoreAction_Target()   { _ = "STUB: not implemented"; return }
func (*StoreAction_Task) isStoreAction_Target()      { _ = "STUB: not implemented"; return }
func (*StoreAction_Network) isStoreAction_Target()   { _ = "STUB: not implemented"; return }
func (*StoreAction_Cluster) isStoreAction_Target()   { _ = "STUB: not implemented"; return }
func (*StoreAction_Secret) isStoreAction_Target()    { _ = "STUB: not implemented"; return }
func (*StoreAction_Resource) isStoreAction_Target()  { _ = "STUB: not implemented"; return }
func (*StoreAction_Extension) isStoreAction_Target() { _ = "STUB: not implemented"; return }
func (*StoreAction_Config) isStoreAction_Target()    { _ = "STUB: not implemented"; return }
func (*StoreAction_Volume) isStoreAction_Target()    { _ = "STUB: not implemented"; return }

func (m *StoreAction) GetTarget() isStoreAction_Target {
	_ = "STUB: not implemented"
	return *new(isStoreAction_Target)
}

func (m *StoreAction) GetNode() *Node { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetService() *Service { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetTask() *Task { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetNetwork() *Network { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetCluster() *Cluster { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetSecret() *Secret { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetResource() *Resource { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetExtension() *Extension { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetConfig() *Config { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) GetVolume() *Volume { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StoreAction) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterEnum("docker.swarmkit.v1.StoreActionKind", StoreActionKind_name, StoreActionKind_value)
	proto.RegisterType((*RaftMember)(nil), "docker.swarmkit.v1.RaftMember")
	proto.RegisterType((*JoinRequest)(nil), "docker.swarmkit.v1.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "docker.swarmkit.v1.JoinResponse")
	proto.RegisterType((*LeaveRequest)(nil), "docker.swarmkit.v1.LeaveRequest")
	proto.RegisterType((*LeaveResponse)(nil), "docker.swarmkit.v1.LeaveResponse")
	proto.RegisterType((*ProcessRaftMessageRequest)(nil), "docker.swarmkit.v1.ProcessRaftMessageRequest")
	proto.RegisterType((*ProcessRaftMessageResponse)(nil), "docker.swarmkit.v1.ProcessRaftMessageResponse")
	proto.RegisterType((*StreamRaftMessageRequest)(nil), "docker.swarmkit.v1.StreamRaftMessageRequest")
	proto.RegisterType((*StreamRaftMessageResponse)(nil), "docker.swarmkit.v1.StreamRaftMessageResponse")
	proto.RegisterType((*ResolveAddressRequest)(nil), "docker.swarmkit.v1.ResolveAddressRequest")
	proto.RegisterType((*ResolveAddressResponse)(nil), "docker.swarmkit.v1.ResolveAddressResponse")
	proto.RegisterType((*InternalRaftRequest)(nil), "docker.swarmkit.v1.InternalRaftRequest")
	proto.RegisterType((*StoreAction)(nil), "docker.swarmkit.v1.StoreAction")
}

func init() {
	proto.RegisterFile("github.com/docker/swarmkit/api/raft.proto", fileDescriptor_d2c32e1e3c930c15)
}

var fileDescriptor_d2c32e1e3c930c15 = []byte{
	// 1044 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x73, 0xdb, 0x44,
	0x14, 0xc7, 0x25, 0x5b, 0x75, 0x9a, 0xe7, 0x36, 0x09, 0x5b, 0x12, 0x14, 0xb5, 0x28, 0xae, 0x9b,
	0x19, 0x9c, 0x90, 0xc8, 0x83, 0xcb, 0x4c, 0x99, 0x42, 0x0f, 0x71, 0xe2, 0x99, 0x98, 0xb4, 0x4e,
	0x47, 0x49, 0x4a, 0x6f, 0x41, 0x96, 0x36, 0xae, 0xb0, 0xad, 0x35, 0xbb, 0x6b, 0x07, 0x2e, 0x4c,
	0x8f, 0x90, 0x13, 0x37, 0x18, 0x66, 0x3a, 0x1c, 0xe0, 0xdc, 0x0f, 0xc0, 0x27, 0xc8, 0x70, 0xea,
	0x8d, 0x9e, 0x32, 0xd4, 0xb9, 0xc3, 0x17, 0xe0, 0xc0, 0xec, 0x4a, 0x4a, 0x42, 0x22, 0x3b, 0x3e,
	0x70, 0xf2, 0x8e, 0xf7, 0xf7, 0x7f, 0xff, 0xb7, 0xbb, 0x6f, 0xdf, 0x0a, 0x16, 0x1a, 0x3e, 0x7f,
	0xd6, 0xad, 0x5b, 0x2e, 0x69, 0x17, 0x3d, 0xe2, 0x36, 0x31, 0x2d, 0xb2, 0x7d, 0x87, 0xb6, 0x9b,
	0x3e, 0x2f, 0x3a, 0x1d, 0xbf, 0x48, 0x9d, 0x3d, 0x6e, 0x75, 0x28, 0xe1, 0x04, 0xa1, 0x70, 0xde,
	0x8a, 0xe7, 0xad, 0xde, 0x07, 0xc6, 0xd2, 0x25, 0x72, 0x52, 0xff, 0x02, 0xbb, 0x9c, 0x85, 0x11,
	0x8c, 0xc5, 0x4b, 0x68, 0xfe, 0x75, 0x07, 0xc7, 0xec, 0x7c, 0x83, 0x58, 0x98, 0xbb, 0x9e, 0xe5,
	0x13, 0x99, 0x44, 0xb1, 0x77, 0x57, 0xfe, 0x76, 0xea, 0x67, 0x72, 0x32, 0xde, 0x6e, 0x90, 0x06,
	0x91, 0xc3, 0xa2, 0x18, 0x45, 0xff, 0xde, 0x1b, 0xe2, 0x23, 0x89, 0x7a, 0x77, 0xaf, 0xd8, 0x69,
	0x75, 0x1b, 0x7e, 0x10, 0xfd, 0x84, 0xc2, 0xfc, 0x4b, 0x15, 0xc0, 0x76, 0xf6, 0xf8, 0x23, 0xdc,
	0xae, 0x63, 0x8a, 0xee, 0xc0, 0x98, 0xf0, 0xda, 0xf5, 0x3d, 0x5d, 0xcd, 0xa9, 0x05, 0xad, 0x0c,
	0xfd, 0xa3, 0xb9, 0x8c, 0x00, 0xaa, 0x6b, 0x76, 0x46, 0x4c, 0x55, 0x3d, 0x01, 0x05, 0xc4, 0xc3,
	0x02, 0x4a, 0xe5, 0xd4, 0xc2, 0x78, 0x08, 0xd5, 0x88, 0x87, 0x05, 0x24, 0xa6, 0xaa, 0x1e, 0x42,
	0xa0, 0x39, 0x9e, 0x47, 0xf5, 0xb4, 0x20, 0x6c, 0x39, 0x46, 0x65, 0xc8, 0x30, 0xee, 0xf0, 0x2e,
	0xd3, 0xb5, 0x9c, 0x5a, 0xc8, 0x96, 0xe6, 0xad, 0x8b, 0x1b, 0x6c, 0x9d, 0x66, 0xb3, 0x25, 0xd9,
	0xb2, 0x76, 0x78, 0x34, 0xa7, 0xd8, 0x91, 0x32, 0x7f, 0x1b, 0xb2, 0x9f, 0x12, 0x3f, 0xb0, 0xf1,
	0x97, 0x5d, 0xcc, 0xf8, 0x89, 0x8d, 0x7a, 0x6a, 0x93, 0xff, 0x49, 0x85, 0x6b, 0x21, 0xc3, 0x3a,
	0x24, 0x60, 0x78, 0xb4, 0x55, 0x7d, 0x04, 0x63, 0x6d, 0x69, 0xcb, 0xf4, 0x54, 0x2e, 0x5d, 0xc8,
	0x96, 0xcc, 0xe1, 0xd9, 0xd9, 0x31, 0x8e, 0xde, 0x87, 0x49, 0x8a, 0xdb, 0xa4, 0x87, 0xbd, 0xdd,
	0x38, 0x42, 0x3a, 0x97, 0x2e, 0x68, 0xe5, 0xd4, 0x94, 0x62, 0x4f, 0x44, 0x53, 0xa1, 0x88, 0xe5,
	0xcb, 0x70, 0xed, 0x21, 0x76, 0x7a, 0x38, 0x5e, 0x40, 0x09, 0x34, 0xb1, 0x63, 0x32, 0xb1, 0xcb,
	0x3d, 0x25, 0x9b, 0x9f, 0x84, 0xeb, 0x51, 0x8c, 0x70, 0x81, 0xf9, 0x87, 0x30, 0xfb, 0x98, 0x12,
	0x17, 0x33, 0x16, 0xb2, 0x8c, 0x39, 0x8d, 0x13, 0x87, 0x05, 0xb1, 0x30, 0xf9, 0x4f, 0x64, 0x32,
	0x69, 0x85, 0x65, 0x65, 0xc5, 0x60, 0x3c, 0x7f, 0x5f, 0x7b, 0xfe, 0x43, 0x5e, 0xc9, 0xdf, 0x02,
	0x23, 0x29, 0x5a, 0xe4, 0xb5, 0x01, 0xfa, 0x16, 0xa7, 0xd8, 0x69, 0xff, 0x1f, 0x56, 0x37, 0x61,
	0x36, 0x21, 0x58, 0xe4, 0xf4, 0x09, 0x4c, 0xdb, 0x98, 0x91, 0x56, 0x0f, 0xaf, 0x78, 0x1e, 0x15,
	0xe9, 0x44, 0x36, 0xa3, 0x9c, 0x67, 0x7e, 0x09, 0x66, 0xce, 0xab, 0xa3, 0x72, 0x48, 0xaa, 0x99,
	0x16, 0xdc, 0xa8, 0x06, 0x1c, 0xd3, 0xc0, 0x69, 0x89, 0x38, 0xb1, 0xd3, 0x0c, 0xa4, 0x4e, 0x4c,
	0x32, 0xfd, 0xa3, 0xb9, 0x54, 0x75, 0xcd, 0x4e, 0xf9, 0x1e, 0x7a, 0x00, 0x19, 0xc7, 0xe5, 0x3e,
	0x09, 0xa2, 0x5a, 0x99, 0x4b, 0x3a, 0xb7, 0x2d, 0x4e, 0x28, 0x5e, 0x91, 0x58, 0x5c, 0xc4, 0xa1,
	0x28, 0xff, 0x8f, 0x06, 0xd9, 0x33, 0xb3, 0xe8, 0xe3, 0x93, 0x70, 0xc2, 0x6a, 0xa2, 0x74, 0xe7,
	0x92, 0x70, 0x1b, 0x7e, 0xe0, 0xc5, 0xc1, 0x90, 0x15, 0x55, 0x50, 0x4a, 0xee, 0xb8, 0x9e, 0x24,
	0x15, 0x77, 0x73, 0x5d, 0x09, 0xab, 0x07, 0xdd, 0x83, 0x31, 0x86, 0x69, 0xcf, 0x77, 0xb1, 0xbc,
	0x9c, 0xd9, 0xd2, 0xcd, 0x44, 0xb7, 0x10, 0x59, 0x57, 0xec, 0x98, 0x16, 0x46, 0xdc, 0x61, 0xcd,
	0xe8, 0xf2, 0x26, 0x1a, 0x6d, 0x3b, 0xac, 0x29, 0x8c, 0x04, 0x27, 0x8c, 0x02, 0xcc, 0xf7, 0x09,
	0x6d, 0xea, 0x57, 0x06, 0x1b, 0xd5, 0x42, 0x44, 0x18, 0x45, 0xb4, 0x10, 0xba, 0xad, 0x2e, 0xe3,
	0x98, 0xea, 0x99, 0xc1, 0xc2, 0xd5, 0x10, 0x11, 0xc2, 0x88, 0x46, 0x1f, 0x42, 0x86, 0x61, 0x97,
	0x62, 0xae, 0x8f, 0x49, 0x9d, 0x91, 0xbc, 0x32, 0x41, 0xac, 0x8b, 0x96, 0x22, 0x47, 0xe8, 0x3e,
	0x5c, 0xa5, 0x98, 0x91, 0x2e, 0x75, 0xb1, 0x7e, 0x55, 0xea, 0x6e, 0x25, 0x5e, 0xc3, 0x88, 0x59,
	0x57, 0xec, 0x13, 0x1e, 0x3d, 0x80, 0x71, 0xfc, 0x15, 0xc7, 0x01, 0x13, 0x87, 0x37, 0x2e, 0xc5,
	0xef, 0x26, 0x89, 0x2b, 0x31, 0xb4, 0xae, 0xd8, 0xa7, 0x0a, 0x91, 0xb0, 0x4b, 0x82, 0x3d, 0xbf,
	0xa1, 0xc3, 0xe0, 0x84, 0x57, 0x25, 0x21, 0x12, 0x0e, 0x59, 0xa1, 0xea, 0x91, 0x56, 0xb7, 0x8d,
	0xf5, 0xec, 0x60, 0xd5, 0x13, 0x49, 0x08, 0x55, 0xc8, 0x96, 0xaf, 0x42, 0x86, 0x3b, 0xb4, 0x81,
	0xf9, 0xe2, 0xdf, 0x2a, 0x4c, 0x9e, 0xab, 0x26, 0xf4, 0x1e, 0x8c, 0xed, 0xd4, 0x36, 0x6a, 0x9b,
	0x9f, 0xd5, 0xa6, 0x14, 0xc3, 0x38, 0x78, 0x91, 0x9b, 0x39, 0x47, 0xec, 0x04, 0xcd, 0x80, 0xec,
	0x07, 0xa8, 0x04, 0x37, 0xb6, 0xb6, 0x37, 0xed, 0xca, 0xee, 0xca, 0xea, 0x76, 0x75, 0xb3, 0xb6,
	0xbb, 0x6a, 0x57, 0x56, 0xb6, 0x2b, 0x53, 0xaa, 0x31, 0x7b, 0xf0, 0x22, 0x37, 0x7d, 0x4e, 0xb4,
	0x4a, 0xb1, 0xc3, 0xf1, 0x05, 0xcd, 0xce, 0xe3, 0x35, 0xa1, 0x49, 0x25, 0x6a, 0x76, 0x3a, 0x5e,
	0x92, 0xc6, 0xae, 0x3c, 0xda, 0x7c, 0x52, 0x99, 0x4a, 0x27, 0x6a, 0x6c, 0xd9, 0x64, 0x8d, 0x77,
	0xbe, 0xfd, 0xc5, 0x54, 0x7e, 0xfb, 0xd5, 0x3c, 0xbf, 0xba, 0xd2, 0xcf, 0x69, 0xd0, 0xc4, 0xbd,
	0x46, 0x07, 0x2a, 0xa0, 0x8b, 0xcd, 0x0d, 0x2d, 0x27, 0xed, 0xe0, 0xc0, 0x96, 0x6a, 0x58, 0xa3,
	0xe2, 0x51, 0x27, 0x9b, 0xfe, 0xfd, 0xe5, 0x5f, 0x3f, 0xa6, 0x26, 0xe1, 0xba, 0xe4, 0x97, 0xdb,
	0x4e, 0xe0, 0x34, 0x30, 0x45, 0xdf, 0xa9, 0xf0, 0xd6, 0x85, 0xf6, 0x87, 0x96, 0x92, 0x2f, 0x7f,
	0x72, 0xcb, 0x35, 0x96, 0x47, 0xa4, 0x87, 0x66, 0x52, 0x50, 0xd1, 0x37, 0x30, 0xf1, 0xdf, 0x76,
	0x89, 0x16, 0x06, 0x5d, 0x82, 0x0b, 0x0d, 0xd9, 0x58, 0x1c, 0x05, 0x1d, 0x9a, 0x41, 0xe9, 0x0f,
	0x15, 0x26, 0x4e, 0x1f, 0x3a, 0xf6, 0xcc, 0xef, 0xa0, 0xcf, 0x41, 0x13, 0xcf, 0x38, 0x4a, 0x6c,
	0xae, 0x67, 0x3e, 0x02, 0x8c, 0xdc, 0x60, 0x60, 0xf8, 0x01, 0xb8, 0x70, 0x45, 0x3e, 0xa4, 0x28,
	0x31, 0xc2, 0xd9, 0x77, 0xda, 0xb8, 0x3d, 0x84, 0x18, 0x6a, 0x52, 0x9e, 0x3f, 0x7c, 0x63, 0x2a,
	0xaf, 0xdf, 0x98, 0xca, 0xf3, 0xbe, 0xa9, 0x1e, 0xf6, 0x4d, 0xf5, 0x55, 0xdf, 0x54, 0xff, 0xec,
	0x9b, 0xea, 0xf7, 0xc7, 0xa6, 0xf2, 0xea, 0xd8, 0x54, 0x5e, 0x1f, 0x9b, 0xca, 0xd3, 0xf4, 0x53,
	0xad, 0x9e, 0x91, 0xdf, 0x64, 0x77, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x32, 0xf6, 0xf1, 0xe7,
	0xa3, 0x0a, 0x00, 0x00,
}

type authenticatedWrapperRaftServer struct {
	local     RaftServer
	authorize func(context.Context, []string) error
}

func NewAuthenticatedWrapperRaftServer(local RaftServer, authorize func(context.Context, []string) error) RaftServer {
	_ = "STUB: not implemented"
	return *new(RaftServer)
}

func (p *authenticatedWrapperRaftServer) ProcessRaftMessage(ctx context.Context, r *ProcessRaftMessageRequest) (*ProcessRaftMessageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *authenticatedWrapperRaftServer) StreamRaftMessage(stream Raft_StreamRaftMessageServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (p *authenticatedWrapperRaftServer) ResolveAddress(ctx context.Context, r *ResolveAddressRequest) (*ResolveAddressResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type authenticatedWrapperRaftMembershipServer struct {
	local     RaftMembershipServer
	authorize func(context.Context, []string) error
}

func NewAuthenticatedWrapperRaftMembershipServer(local RaftMembershipServer, authorize func(context.Context, []string) error) RaftMembershipServer {
	_ = "STUB: not implemented"
	return *new(RaftMembershipServer)
}

func (p *authenticatedWrapperRaftMembershipServer) Join(ctx context.Context, r *JoinRequest) (*JoinResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *authenticatedWrapperRaftMembershipServer) Leave(ctx context.Context, r *LeaveRequest) (*LeaveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftMember) Copy() *RaftMember { _ = "STUB: not implemented"; return nil }

func (m *RaftMember) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *JoinRequest) Copy() *JoinRequest { _ = "STUB: not implemented"; return nil }

func (m *JoinRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *JoinResponse) Copy() *JoinResponse { _ = "STUB: not implemented"; return nil }

func (m *JoinResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *LeaveRequest) Copy() *LeaveRequest { _ = "STUB: not implemented"; return nil }

func (m *LeaveRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *LeaveResponse) Copy() *LeaveResponse { _ = "STUB: not implemented"; return nil }

func (m *LeaveResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }
func (m *ProcessRaftMessageResponse) Copy() *ProcessRaftMessageResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProcessRaftMessageResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }
func (m *StreamRaftMessageResponse) Copy() *StreamRaftMessageResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *StreamRaftMessageResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }
func (m *ResolveAddressRequest) Copy() *ResolveAddressRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResolveAddressRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *ResolveAddressResponse) Copy() *ResolveAddressResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResolveAddressResponse) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *InternalRaftRequest) Copy() *InternalRaftRequest { _ = "STUB: not implemented"; return nil }

func (m *InternalRaftRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *StoreAction) Copy() *StoreAction { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	// ProcessRaftMessage sends a raft message to be processed on a raft member, it is
	// called from the RaftMember willing to send a message to its destination ('To' field)
	ProcessRaftMessage(ctx context.Context, in *ProcessRaftMessageRequest, opts ...grpc.CallOption) (*ProcessRaftMessageResponse, error)
	// StreamRaftMessage accepts a stream of raft messages of type StreamRaftMessageRequest
	// to be processed on a raft member, returning a StreamRaftMessageResponse
	// when processing of the streamed messages is complete. A single stream corresponds
	// to a single raft message, which may be disassembled and streamed as individual messages.
	// It is called from the Raft leader, which uses it to stream messages to a raft member.
	StreamRaftMessage(ctx context.Context, opts ...grpc.CallOption) (Raft_StreamRaftMessageClient, error)
	// ResolveAddress returns the address where the node with the given ID can be reached.
	ResolveAddress(ctx context.Context, in *ResolveAddressRequest, opts ...grpc.CallOption) (*ResolveAddressResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	_ = "STUB: not implemented"
	return *new(RaftClient)
}

func (c *raftClient) ProcessRaftMessage(ctx context.Context, in *ProcessRaftMessageRequest, opts ...grpc.CallOption) (*ProcessRaftMessageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *raftClient) StreamRaftMessage(ctx context.Context, opts ...grpc.CallOption) (Raft_StreamRaftMessageClient, error) {
	_ = "STUB: not implemented"
	return *new(Raft_StreamRaftMessageClient), nil
}

type Raft_StreamRaftMessageClient interface {
	Send(*StreamRaftMessageRequest) error
	CloseAndRecv() (*StreamRaftMessageResponse, error)
	grpc.ClientStream
}

type raftStreamRaftMessageClient struct {
	grpc.ClientStream
}

func (x *raftStreamRaftMessageClient) Send(m *StreamRaftMessageRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *raftStreamRaftMessageClient) CloseAndRecv() (*StreamRaftMessageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *raftClient) ResolveAddress(ctx context.Context, in *ResolveAddressRequest, opts ...grpc.CallOption) (*ResolveAddressResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	// ProcessRaftMessage sends a raft message to be processed on a raft member, it is
	// called from the RaftMember willing to send a message to its destination ('To' field)
	ProcessRaftMessage(context.Context, *ProcessRaftMessageRequest) (*ProcessRaftMessageResponse, error)
	// StreamRaftMessage accepts a stream of raft messages of type StreamRaftMessageRequest
	// to be processed on a raft member, returning a StreamRaftMessageResponse
	// when processing of the streamed messages is complete. A single stream corresponds
	// to a single raft message, which may be disassembled and streamed as individual messages.
	// It is called from the Raft leader, which uses it to stream messages to a raft member.
	StreamRaftMessage(Raft_StreamRaftMessageServer) error
	// ResolveAddress returns the address where the node with the given ID can be reached.
	ResolveAddress(context.Context, *ResolveAddressRequest) (*ResolveAddressResponse, error)
}

// UnimplementedRaftServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) ProcessRaftMessage(ctx context.Context, req *ProcessRaftMessageRequest) (*ProcessRaftMessageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedRaftServer) StreamRaftMessage(srv Raft_StreamRaftMessageServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (*UnimplementedRaftServer) ResolveAddress(ctx context.Context, req *ResolveAddressRequest) (*ResolveAddressResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) { _ = "STUB: not implemented"; return }

func _Raft_ProcessRaftMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Raft_StreamRaftMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Raft_StreamRaftMessageServer interface {
	SendAndClose(*StreamRaftMessageResponse) error
	Recv() (*StreamRaftMessageRequest, error)
	grpc.ServerStream
}

type raftStreamRaftMessageServer struct {
	grpc.ServerStream
}

func (x *raftStreamRaftMessageServer) SendAndClose(m *StreamRaftMessageResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *raftStreamRaftMessageServer) Recv() (*StreamRaftMessageRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Raft_ResolveAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "docker.swarmkit.v1.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessRaftMessage",
			Handler:    _Raft_ProcessRaftMessage_Handler,
		},
		{
			MethodName: "ResolveAddress",
			Handler:    _Raft_ResolveAddress_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRaftMessage",
			Handler:       _Raft_StreamRaftMessage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/docker/swarmkit/api/raft.proto",
}

// RaftMembershipClient is the client API for RaftMembership service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftMembershipClient interface {
	// Join adds a RaftMember to the raft cluster.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// Leave removes a RaftMember from the raft cluster.
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
}

type raftMembershipClient struct {
	cc *grpc.ClientConn
}

func NewRaftMembershipClient(cc *grpc.ClientConn) RaftMembershipClient {
	_ = "STUB: not implemented"
	return *new(RaftMembershipClient)
}

func (c *raftMembershipClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *raftMembershipClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RaftMembershipServer is the server API for RaftMembership service.
type RaftMembershipServer interface {
	// Join adds a RaftMember to the raft cluster.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// Leave removes a RaftMember from the raft cluster.
	Leave(context.Context, *LeaveRequest) (*LeaveResponse, error)
}

// UnimplementedRaftMembershipServer can be embedded to have forward compatible implementations.
type UnimplementedRaftMembershipServer struct {
}

func (*UnimplementedRaftMembershipServer) Join(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedRaftMembershipServer) Leave(ctx context.Context, req *LeaveRequest) (*LeaveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterRaftMembershipServer(s *grpc.Server, srv RaftMembershipServer) {
	_ = "STUB: not implemented"
	return
}

func _RaftMembership_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _RaftMembership_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _RaftMembership_serviceDesc = grpc.ServiceDesc{
	ServiceName: "docker.swarmkit.v1.RaftMembership",
	HandlerType: (*RaftMembershipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _RaftMembership_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _RaftMembership_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/docker/swarmkit/api/raft.proto",
}

func (m *RaftMember) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *RaftMember) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *RaftMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *JoinRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *JoinRequest) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *JoinRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *JoinResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *JoinResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *JoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LeaveRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LeaveRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LeaveRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LeaveResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LeaveResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LeaveResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProcessRaftMessageRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProcessRaftMessageRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProcessRaftMessageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProcessRaftMessageResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProcessRaftMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProcessRaftMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StreamRaftMessageRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamRaftMessageRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StreamRaftMessageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StreamRaftMessageResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamRaftMessageResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StreamRaftMessageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResolveAddressRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResolveAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResolveAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResolveAddressResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ResolveAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ResolveAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InternalRaftRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InternalRaftRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InternalRaftRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StoreAction) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *StoreAction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Node) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Node) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Service) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Service) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Task) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Network) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Network) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Cluster) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Cluster) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Secret) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Secret) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Resource) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Resource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Extension) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Extension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Config) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Volume) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreAction_Volume) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintRaft(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

type raftProxyRaftServer struct {
	local                       RaftServer
	connSelector                raftselector.ConnProvider
	localCtxMods, remoteCtxMods []func(context.Context) (context.Context, error)
}

func NewRaftProxyRaftServer(local RaftServer, connSelector raftselector.ConnProvider, localCtxMod, remoteCtxMod func(context.Context) (context.Context, error)) RaftServer {
	_ = "STUB: not implemented"
	return *new(RaftServer)
}

func (p *raftProxyRaftServer) runCtxMods(ctx context.Context, ctxMods []func(context.Context) (context.Context, error)) (context.Context, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), nil
}

func (p *raftProxyRaftServer) pollNewLeaderConn(ctx context.Context) (*grpc.ClientConn, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *raftProxyRaftServer) ProcessRaftMessage(ctx context.Context, r *ProcessRaftMessageRequest) (*ProcessRaftMessageResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type Raft_StreamRaftMessageServerWrapper struct {
	Raft_StreamRaftMessageServer
	ctx context.Context
}

func (s Raft_StreamRaftMessageServerWrapper) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (p *raftProxyRaftServer) StreamRaftMessage(stream Raft_StreamRaftMessageServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (p *raftProxyRaftServer) ResolveAddress(ctx context.Context, r *ResolveAddressRequest) (*ResolveAddressResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type raftProxyRaftMembershipServer struct {
	local                       RaftMembershipServer
	connSelector                raftselector.ConnProvider
	localCtxMods, remoteCtxMods []func(context.Context) (context.Context, error)
}

func NewRaftProxyRaftMembershipServer(local RaftMembershipServer, connSelector raftselector.ConnProvider, localCtxMod, remoteCtxMod func(context.Context) (context.Context, error)) RaftMembershipServer {
	_ = "STUB: not implemented"
	return *new(RaftMembershipServer)
}

func (p *raftProxyRaftMembershipServer) runCtxMods(ctx context.Context, ctxMods []func(context.Context) (context.Context, error)) (context.Context, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), nil
}

func (p *raftProxyRaftMembershipServer) pollNewLeaderConn(ctx context.Context) (*grpc.ClientConn, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *raftProxyRaftMembershipServer) Join(ctx context.Context, r *JoinRequest) (*JoinResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (p *raftProxyRaftMembershipServer) Leave(ctx context.Context, r *LeaveRequest) (*LeaveResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RaftMember) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *JoinRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *JoinResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LeaveRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LeaveResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProcessRaftMessageRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProcessRaftMessageResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StreamRaftMessageRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StreamRaftMessageResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ResolveAddressRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ResolveAddressResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InternalRaftRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Node) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Service) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Task) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Network) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Cluster) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Secret) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Resource) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Extension) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Config) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreAction_Volume) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovRaft(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozRaft(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (this *RaftMember) String() string { _ = "STUB: not implemented"; return "" }

func (this *JoinRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *JoinResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *LeaveRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *LeaveResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *ProcessRaftMessageRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *ProcessRaftMessageResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *StreamRaftMessageRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *StreamRaftMessageResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *ResolveAddressRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *ResolveAddressResponse) String() string { _ = "STUB: not implemented"; return "" }

func (this *InternalRaftRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Node) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Service) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Task) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Network) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Cluster) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Secret) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Resource) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Extension) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Config) String() string { _ = "STUB: not implemented"; return "" }

func (this *StoreAction_Volume) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringRaft(v interface{}) string { _ = "STUB: not implemented"; return "" }

func (m *RaftMember) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *JoinRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *JoinResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LeaveRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LeaveResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProcessRaftMessageRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProcessRaftMessageResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *StreamRaftMessageRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *StreamRaftMessageResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ResolveAddressRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ResolveAddressResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InternalRaftRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreAction) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipRaft(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthRaft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRaft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRaft = fmt.Errorf("proto: unexpected end of group")
)
