// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/swarmkit/api/watch.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	raftselector "github.com/moby/swarmkit/v2/manager/raftselector"
	_ "github.com/moby/swarmkit/v2/protobuf/plugin"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WatchActionKind distinguishes between creations, updates, and removals. It
// is structured as a bitmap so multiple kinds of events can be requested with
// a mask.
type WatchActionKind int32

const (
	WatchActionKindUnknown WatchActionKind = 0
	WatchActionKindCreate  WatchActionKind = 1
	WatchActionKindUpdate  WatchActionKind = 2
	WatchActionKindRemove  WatchActionKind = 4
)

var WatchActionKind_name = map[int32]string{
	0: "WATCH_ACTION_UNKNOWN",
	1: "WATCH_ACTION_CREATE",
	2: "WATCH_ACTION_UPDATE",
	4: "WATCH_ACTION_REMOVE",
}

var WatchActionKind_value = map[string]int32{
	"WATCH_ACTION_UNKNOWN": 0,
	"WATCH_ACTION_CREATE":  1,
	"WATCH_ACTION_UPDATE":  2,
	"WATCH_ACTION_REMOVE":  4,
}

func (x WatchActionKind) String() string { _ = "STUB: not implemented"; return "" }

func (WatchActionKind) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type Object struct {
	// Types that are valid to be assigned to Object:
	//	*Object_Node
	//	*Object_Service
	//	*Object_Network
	//	*Object_Task
	//	*Object_Cluster
	//	*Object_Secret
	//	*Object_Resource
	//	*Object_Extension
	//	*Object_Config
	//	*Object_Volume
	Object isObject_Object `protobuf_oneof:"Object"`
}

func (m *Object) Reset()                    { _ = "STUB: not implemented"; return }
func (*Object) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Object) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Object) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Object) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Object) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Object) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Object proto.InternalMessageInfo

type isObject_Object interface {
	isObject_Object()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Object_Node struct {
	Node *Node `protobuf:"bytes,1,opt,name=node,proto3,oneof" json:"node,omitempty"`
}
type Object_Service struct {
	Service *Service `protobuf:"bytes,2,opt,name=service,proto3,oneof" json:"service,omitempty"`
}
type Object_Network struct {
	Network *Network `protobuf:"bytes,3,opt,name=network,proto3,oneof" json:"network,omitempty"`
}
type Object_Task struct {
	Task *Task `protobuf:"bytes,4,opt,name=task,proto3,oneof" json:"task,omitempty"`
}
type Object_Cluster struct {
	Cluster *Cluster `protobuf:"bytes,5,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
}
type Object_Secret struct {
	Secret *Secret `protobuf:"bytes,6,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
}
type Object_Resource struct {
	Resource *Resource `protobuf:"bytes,7,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
}
type Object_Extension struct {
	Extension *Extension `protobuf:"bytes,8,opt,name=extension,proto3,oneof" json:"extension,omitempty"`
}
type Object_Config struct {
	Config *Config `protobuf:"bytes,9,opt,name=config,proto3,oneof" json:"config,omitempty"`
}
type Object_Volume struct {
	Volume *Volume `protobuf:"bytes,10,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
}

func (*Object_Node) isObject_Object()      { _ = "STUB: not implemented"; return }
func (*Object_Service) isObject_Object()   { _ = "STUB: not implemented"; return }
func (*Object_Network) isObject_Object()   { _ = "STUB: not implemented"; return }
func (*Object_Task) isObject_Object()      { _ = "STUB: not implemented"; return }
func (*Object_Cluster) isObject_Object()   { _ = "STUB: not implemented"; return }
func (*Object_Secret) isObject_Object()    { _ = "STUB: not implemented"; return }
func (*Object_Resource) isObject_Object()  { _ = "STUB: not implemented"; return }
func (*Object_Extension) isObject_Object() { _ = "STUB: not implemented"; return }
func (*Object_Config) isObject_Object()    { _ = "STUB: not implemented"; return }
func (*Object_Volume) isObject_Object()    { _ = "STUB: not implemented"; return }

func (m *Object) GetObject() isObject_Object {
	_ = "STUB: not implemented"
	return *new(isObject_Object)
}

func (m *Object) GetNode() *Node { _ = "STUB: not implemented"; return nil }

func (m *Object) GetService() *Service { _ = "STUB: not implemented"; return nil }

func (m *Object) GetNetwork() *Network { _ = "STUB: not implemented"; return nil }

func (m *Object) GetTask() *Task { _ = "STUB: not implemented"; return nil }

func (m *Object) GetCluster() *Cluster { _ = "STUB: not implemented"; return nil }

func (m *Object) GetSecret() *Secret { _ = "STUB: not implemented"; return nil }

func (m *Object) GetResource() *Resource { _ = "STUB: not implemented"; return nil }

func (m *Object) GetExtension() *Extension { _ = "STUB: not implemented"; return nil }

func (m *Object) GetConfig() *Config { _ = "STUB: not implemented"; return nil }

func (m *Object) GetVolume() *Volume { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Object) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

// FIXME(aaronl): These messages should ideally be embedded in SelectBy, but
// protoc generates bad code for that.
type SelectBySlot struct {
	ServiceID string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Slot      uint64 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (m *SelectBySlot) Reset()                    { _ = "STUB: not implemented"; return }
func (*SelectBySlot) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SelectBySlot) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SelectBySlot) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectBySlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SelectBySlot) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SelectBySlot) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SelectBySlot) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SelectBySlot proto.InternalMessageInfo

type SelectByCustom struct {
	Kind  string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SelectByCustom) Reset()                    { _ = "STUB: not implemented"; return }
func (*SelectByCustom) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SelectByCustom) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SelectByCustom) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectByCustom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SelectByCustom) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SelectByCustom) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SelectByCustom) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SelectByCustom proto.InternalMessageInfo

type SelectBy struct {
	// TODO(aaronl): Are all of these things we want to expose in
	// the API? Exposing them may commit us to maintaining those
	// internal indices going forward.
	//
	// Types that are valid to be assigned to By:
	//	*SelectBy_ID
	//	*SelectBy_IDPrefix
	//	*SelectBy_Name
	//	*SelectBy_NamePrefix
	//	*SelectBy_Custom
	//	*SelectBy_CustomPrefix
	//	*SelectBy_ServiceID
	//	*SelectBy_NodeID
	//	*SelectBy_Slot
	//	*SelectBy_DesiredState
	//	*SelectBy_Role
	//	*SelectBy_Membership
	//	*SelectBy_ReferencedNetworkID
	//	*SelectBy_ReferencedSecretID
	//	*SelectBy_ReferencedConfigID
	//	*SelectBy_Kind
	By isSelectBy_By `protobuf_oneof:"By"`
}

func (m *SelectBy) Reset()                    { _ = "STUB: not implemented"; return }
func (*SelectBy) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SelectBy) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SelectBy) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SelectBy) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SelectBy) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SelectBy proto.InternalMessageInfo

type isSelectBy_By interface {
	isSelectBy_By()
	MarshalTo([]byte) (int, error)
	Size() int
}

type SelectBy_ID struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
}
type SelectBy_IDPrefix struct {
	IDPrefix string `protobuf:"bytes,2,opt,name=id_prefix,json=idPrefix,proto3,oneof" json:"id_prefix,omitempty"`
}
type SelectBy_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
}
type SelectBy_NamePrefix struct {
	NamePrefix string `protobuf:"bytes,4,opt,name=name_prefix,json=namePrefix,proto3,oneof" json:"name_prefix,omitempty"`
}
type SelectBy_Custom struct {
	Custom *SelectByCustom `protobuf:"bytes,5,opt,name=custom,proto3,oneof" json:"custom,omitempty"`
}
type SelectBy_CustomPrefix struct {
	CustomPrefix *SelectByCustom `protobuf:"bytes,6,opt,name=custom_prefix,json=customPrefix,proto3,oneof" json:"custom_prefix,omitempty"`
}
type SelectBy_ServiceID struct {
	ServiceID string `protobuf:"bytes,7,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
}
type SelectBy_NodeID struct {
	NodeID string `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
}
type SelectBy_Slot struct {
	Slot *SelectBySlot `protobuf:"bytes,9,opt,name=slot,proto3,oneof" json:"slot,omitempty"`
}
type SelectBy_DesiredState struct {
	DesiredState TaskState `protobuf:"varint,10,opt,name=desired_state,json=desiredState,proto3,enum=docker.swarmkit.v1.TaskState,oneof" json:"desired_state,omitempty"`
}
type SelectBy_Role struct {
	Role NodeRole `protobuf:"varint,11,opt,name=role,proto3,enum=docker.swarmkit.v1.NodeRole,oneof" json:"role,omitempty"`
}
type SelectBy_Membership struct {
	Membership NodeSpec_Membership `protobuf:"varint,12,opt,name=membership,proto3,enum=docker.swarmkit.v1.NodeSpec_Membership,oneof" json:"membership,omitempty"`
}
type SelectBy_ReferencedNetworkID struct {
	ReferencedNetworkID string `protobuf:"bytes,13,opt,name=referenced_network_id,json=referencedNetworkId,proto3,oneof" json:"referenced_network_id,omitempty"`
}
type SelectBy_ReferencedSecretID struct {
	ReferencedSecretID string `protobuf:"bytes,14,opt,name=referenced_secret_id,json=referencedSecretId,proto3,oneof" json:"referenced_secret_id,omitempty"`
}
type SelectBy_ReferencedConfigID struct {
	ReferencedConfigID string `protobuf:"bytes,16,opt,name=referenced_config_id,json=referencedConfigId,proto3,oneof" json:"referenced_config_id,omitempty"`
}
type SelectBy_Kind struct {
	Kind string `protobuf:"bytes,15,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
}

func (*SelectBy_ID) isSelectBy_By()                  { _ = "STUB: not implemented"; return }
func (*SelectBy_IDPrefix) isSelectBy_By()            { _ = "STUB: not implemented"; return }
func (*SelectBy_Name) isSelectBy_By()                { _ = "STUB: not implemented"; return }
func (*SelectBy_NamePrefix) isSelectBy_By()          { _ = "STUB: not implemented"; return }
func (*SelectBy_Custom) isSelectBy_By()              { _ = "STUB: not implemented"; return }
func (*SelectBy_CustomPrefix) isSelectBy_By()        { _ = "STUB: not implemented"; return }
func (*SelectBy_ServiceID) isSelectBy_By()           { _ = "STUB: not implemented"; return }
func (*SelectBy_NodeID) isSelectBy_By()              { _ = "STUB: not implemented"; return }
func (*SelectBy_Slot) isSelectBy_By()                { _ = "STUB: not implemented"; return }
func (*SelectBy_DesiredState) isSelectBy_By()        { _ = "STUB: not implemented"; return }
func (*SelectBy_Role) isSelectBy_By()                { _ = "STUB: not implemented"; return }
func (*SelectBy_Membership) isSelectBy_By()          { _ = "STUB: not implemented"; return }
func (*SelectBy_ReferencedNetworkID) isSelectBy_By() { _ = "STUB: not implemented"; return }
func (*SelectBy_ReferencedSecretID) isSelectBy_By()  { _ = "STUB: not implemented"; return }
func (*SelectBy_ReferencedConfigID) isSelectBy_By()  { _ = "STUB: not implemented"; return }
func (*SelectBy_Kind) isSelectBy_By()                { _ = "STUB: not implemented"; return }

func (m *SelectBy) GetBy() isSelectBy_By { _ = "STUB: not implemented"; return *new(isSelectBy_By) }

func (m *SelectBy) GetID() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetIDPrefix() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetNamePrefix() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetCustom() *SelectByCustom { _ = "STUB: not implemented"; return nil }

func (m *SelectBy) GetCustomPrefix() *SelectByCustom { _ = "STUB: not implemented"; return nil }

func (m *SelectBy) GetServiceID() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetNodeID() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetSlot() *SelectBySlot { _ = "STUB: not implemented"; return nil }

func (m *SelectBy) GetDesiredState() TaskState { _ = "STUB: not implemented"; return *new(TaskState) }

func (m *SelectBy) GetRole() NodeRole { _ = "STUB: not implemented"; return *new(NodeRole) }

func (m *SelectBy) GetMembership() NodeSpec_Membership {
	_ = "STUB: not implemented"
	return *new(NodeSpec_Membership)
}

func (m *SelectBy) GetReferencedNetworkID() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetReferencedSecretID() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetReferencedConfigID() string { _ = "STUB: not implemented"; return "" }

func (m *SelectBy) GetKind() string { _ = "STUB: not implemented"; return "" }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SelectBy) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

type WatchRequest struct {
	// Multiple entries are combined using OR logic - i.e. if an event
	// matches all of the selectors specified in any single watch entry,
	// the event will be sent to the client.
	Entries []*WatchRequest_WatchEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// ResumeFrom provides an version to resume the watch from, if non-nil.
	// The watch will return changes since this version, and continue to
	// return new changes afterwards. Watch will return an error if the
	// server has compacted its log and no longer has complete history to
	// this point.
	ResumeFrom *Version `protobuf:"bytes,2,opt,name=resume_from,json=resumeFrom,proto3" json:"resume_from,omitempty"`
	// IncludeOldObject causes WatchMessages to include a copy of the
	// previous version of the object on updates. Note that only live
	// changes will include the old object (not historical changes
	// retrieved using ResumeFrom).
	IncludeOldObject bool `protobuf:"varint,3,opt,name=include_old_object,json=includeOldObject,proto3" json:"include_old_object,omitempty"`
}

func (m *WatchRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (*WatchRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WatchRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *WatchRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WatchRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WatchRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

type WatchRequest_WatchEntry struct {
	// Kind can contain a builtin type such as "node", "secret", etc. or
	// the kind specified by a custom-defined object.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Action (create/update/delete)
	// This is a bitmask, so multiple actions may be OR'd together
	Action WatchActionKind `protobuf:"varint,2,opt,name=action,proto3,enum=docker.swarmkit.v1.WatchActionKind" json:"action,omitempty"`
	// Filters are combined using AND logic - an event must match
	// all of them to pass the filter.
	Filters []*SelectBy `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (m *WatchRequest_WatchEntry) Reset()      { _ = "STUB: not implemented"; return }
func (*WatchRequest_WatchEntry) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*WatchRequest_WatchEntry) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchRequest_WatchEntry) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WatchRequest_WatchEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchRequest_WatchEntry) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WatchRequest_WatchEntry) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WatchRequest_WatchEntry) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WatchRequest_WatchEntry proto.InternalMessageInfo

// WatchMessage is the type of the stream that's returned to the client by
// Watch. Note that the first item of this stream will always be a WatchMessage
// with a nil Object, to signal that the stream has started.
type WatchMessage struct {
	Events []*WatchMessage_Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Index versions this change to the data store. It can be used to
	// resume the watch from this point.
	Version *Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *WatchMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (*WatchMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WatchMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *WatchMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WatchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WatchMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WatchMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WatchMessage proto.InternalMessageInfo

type WatchMessage_Event struct {
	// Action (create/update/delete)
	// Note that WatchMessage does not expose "commit" events that
	// mark transaction boundaries.
	Action WatchActionKind `protobuf:"varint,1,opt,name=action,proto3,enum=docker.swarmkit.v1.WatchActionKind" json:"action,omitempty"`
	// Matched object
	Object *Object `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// For updates, OldObject will optionally be included in the
	// watch message, containing the previous version of the
	// object, if IncludeOldObject was set in WatchRequest.
	OldObject *Object `protobuf:"bytes,3,opt,name=old_object,json=oldObject,proto3" json:"old_object,omitempty"`
}

func (m *WatchMessage_Event) Reset()                    { _ = "STUB: not implemented"; return }
func (*WatchMessage_Event) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WatchMessage_Event) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *WatchMessage_Event) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WatchMessage_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchMessage_Event) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WatchMessage_Event) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WatchMessage_Event) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WatchMessage_Event proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("docker.swarmkit.v1.WatchActionKind", WatchActionKind_name, WatchActionKind_value)
	proto.RegisterType((*Object)(nil), "docker.swarmkit.v1.Object")
	proto.RegisterType((*SelectBySlot)(nil), "docker.swarmkit.v1.SelectBySlot")
	proto.RegisterType((*SelectByCustom)(nil), "docker.swarmkit.v1.SelectByCustom")
	proto.RegisterType((*SelectBy)(nil), "docker.swarmkit.v1.SelectBy")
	proto.RegisterType((*WatchRequest)(nil), "docker.swarmkit.v1.WatchRequest")
	proto.RegisterType((*WatchRequest_WatchEntry)(nil), "docker.swarmkit.v1.WatchRequest.WatchEntry")
	proto.RegisterType((*WatchMessage)(nil), "docker.swarmkit.v1.WatchMessage")
	proto.RegisterType((*WatchMessage_Event)(nil), "docker.swarmkit.v1.WatchMessage.Event")
}

func init() {
	proto.RegisterFile("github.com/docker/swarmkit/api/watch.proto", fileDescriptor_da25266013800cd9)
}

var fileDescriptor_da25266013800cd9 = []byte{
	// 1210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xcd, 0x73, 0xdb, 0xc4,
	0x1b, 0xc7, 0x25, 0xd7, 0x51, 0xec, 0x27, 0x49, 0x9b, 0xd9, 0xa6, 0xad, 0x7e, 0xfe, 0x15, 0xc7,
	0x98, 0xb7, 0x4e, 0x5b, 0x1c, 0x08, 0xa5, 0x1d, 0xa0, 0x30, 0x13, 0x3b, 0x66, 0x6c, 0x3a, 0x79,
	0x99, 0x4d, 0xd2, 0x1e, 0x3d, 0x8a, 0xf4, 0xc4, 0x15, 0x91, 0xb4, 0x66, 0x25, 0x3b, 0xcd, 0x8d,
	0x23, 0xd3, 0x13, 0x17, 0x66, 0xb8, 0xf4, 0x04, 0x67, 0x2e, 0xdc, 0xca, 0x3f, 0xd0, 0xe1, 0xd4,
	0x63, 0xb9, 0x64, 0xa8, 0x7b, 0xe3, 0xc0, 0x5f, 0xc0, 0x81, 0xd9, 0x17, 0x25, 0xa9, 0x2b, 0x27,
	0xf4, 0xe4, 0xd5, 0xea, 0xf3, 0x7d, 0xf6, 0xd9, 0xe7, 0x4d, 0x86, 0xab, 0x5d, 0x3f, 0xb9, 0xdf,
	0xdf, 0xae, 0xb9, 0x2c, 0x5c, 0xf0, 0x98, 0xbb, 0x8b, 0x7c, 0x21, 0xde, 0x73, 0x78, 0xb8, 0xeb,
	0x27, 0x0b, 0x4e, 0xcf, 0x5f, 0xd8, 0x73, 0x12, 0xf7, 0x7e, 0xad, 0xc7, 0x59, 0xc2, 0x08, 0x51,
	0x40, 0x2d, 0x05, 0x6a, 0x83, 0x0f, 0x4b, 0xa7, 0xe9, 0xe3, 0x1e, 0xba, 0xb1, 0xd2, 0x97, 0xae,
	0x9f, 0xc2, 0xb2, 0xed, 0xaf, 0xd1, 0x4d, 0x52, 0xfa, 0x34, 0xcb, 0xc9, 0x7e, 0x0f, 0x53, 0x76,
	0xae, 0xcb, 0xba, 0x4c, 0x2e, 0x17, 0xc4, 0x4a, 0xef, 0xde, 0x3a, 0xc1, 0x82, 0x24, 0xb6, 0xfb,
	0x3b, 0x0b, 0xbd, 0xa0, 0xdf, 0xf5, 0x23, 0xfd, 0xa3, 0x84, 0xd5, 0xc7, 0x79, 0xb0, 0xd6, 0xa4,
	0x33, 0xa4, 0x06, 0xf9, 0x88, 0x79, 0x68, 0x9b, 0x15, 0xf3, 0xca, 0xd4, 0xa2, 0x5d, 0x7b, 0x35,
	0x04, 0xb5, 0x55, 0xe6, 0x61, 0xcb, 0xa0, 0x92, 0x23, 0xb7, 0x60, 0x32, 0x46, 0x3e, 0xf0, 0x5d,
	0xb4, 0x73, 0x52, 0xf2, 0xff, 0x2c, 0xc9, 0x86, 0x42, 0x5a, 0x06, 0x4d, 0x69, 0x21, 0x8c, 0x30,
	0xd9, 0x63, 0x7c, 0xd7, 0x3e, 0x33, 0x5e, 0xb8, 0xaa, 0x10, 0x21, 0xd4, 0xb4, 0xf0, 0x30, 0x71,
	0xe2, 0x5d, 0x3b, 0x3f, 0xde, 0xc3, 0x4d, 0x27, 0x16, 0x12, 0xc9, 0x89, 0x83, 0xdc, 0xa0, 0x1f,
	0x27, 0xc8, 0xed, 0x89, 0xf1, 0x07, 0x35, 0x14, 0x22, 0x0e, 0xd2, 0x34, 0xb9, 0x01, 0x56, 0x8c,
	0x2e, 0xc7, 0xc4, 0xb6, 0xa4, 0xae, 0x94, 0x7d, 0x33, 0x41, 0xb4, 0x0c, 0xaa, 0x59, 0xf2, 0x29,
	0x14, 0x38, 0xc6, 0xac, 0xcf, 0x5d, 0xb4, 0x27, 0xa5, 0xee, 0x72, 0x96, 0x8e, 0x6a, 0xa6, 0x65,
	0xd0, 0x43, 0x9e, 0x7c, 0x0e, 0x45, 0x7c, 0x90, 0x60, 0x14, 0xfb, 0x2c, 0xb2, 0x0b, 0x52, 0xfc,
	0x46, 0x96, 0xb8, 0x99, 0x42, 0x2d, 0x83, 0x1e, 0x29, 0x84, 0xc3, 0x2e, 0x8b, 0x76, 0xfc, 0xae,
	0x5d, 0x1c, 0xef, 0x70, 0x43, 0x12, 0xc2, 0x61, 0xc5, 0x0a, 0xd5, 0x80, 0x05, 0xfd, 0x10, 0x6d,
	0x18, 0xaf, 0xba, 0x2b, 0x09, 0xa1, 0x52, 0x6c, 0xbd, 0x90, 0x56, 0x4c, 0x75, 0x1d, 0xa6, 0x37,
	0x30, 0x40, 0x37, 0xa9, 0xef, 0x6f, 0x04, 0x2c, 0x21, 0xd7, 0x01, 0x74, 0x8e, 0x3b, 0xbe, 0x27,
	0xeb, 0xa8, 0x58, 0x9f, 0x19, 0x1e, 0xcc, 0x17, 0x75, 0x11, 0xb4, 0x97, 0x69, 0x51, 0x03, 0x6d,
	0x8f, 0x10, 0xc8, 0xc7, 0x01, 0x4b, 0x64, 0xf1, 0xe4, 0xa9, 0x5c, 0x57, 0xd7, 0xe1, 0x6c, 0x6a,
	0xb1, 0xd1, 0x8f, 0x13, 0x16, 0x0a, 0x6a, 0xd7, 0x8f, 0xb4, 0x35, 0x2a, 0xd7, 0x64, 0x0e, 0x26,
	0xfc, 0xc8, 0xc3, 0x07, 0x52, 0x5a, 0xa4, 0xea, 0x41, 0xec, 0x0e, 0x9c, 0xa0, 0x8f, 0xb2, 0xa8,
	0x8a, 0x54, 0x3d, 0x54, 0xff, 0xb2, 0xa0, 0x90, 0x9a, 0x24, 0x36, 0xe4, 0x0e, 0x1d, 0xb3, 0x86,
	0x07, 0xf3, 0xb9, 0xf6, 0x72, 0xcb, 0xa0, 0x39, 0xdf, 0x23, 0xd7, 0xa0, 0xe8, 0x7b, 0x9d, 0x1e,
	0xc7, 0x1d, 0x5f, 0x9b, 0xad, 0x4f, 0x0f, 0x0f, 0xe6, 0x0b, 0xed, 0xe5, 0x75, 0xb9, 0x27, 0x92,
	0xe5, 0x7b, 0x6a, 0x4d, 0xe6, 0x20, 0x1f, 0x39, 0xa1, 0x3e, 0x48, 0xf6, 0x83, 0x13, 0x22, 0x79,
	0x13, 0xa6, 0xc4, 0x6f, 0x6a, 0x24, 0xaf, 0x5f, 0x82, 0xd8, 0xd4, 0xc2, 0xdb, 0x60, 0xb9, 0xf2,
	0x5a, 0xba, 0x1e, 0xab, 0xd9, 0x75, 0x75, 0x3c, 0x00, 0x32, 0x5d, 0x2a, 0x14, 0x6d, 0x98, 0x51,
	0xab, 0xf4, 0x08, 0xeb, 0x35, 0x8c, 0x4c, 0x2b, 0xa9, 0x76, 0xa4, 0xf6, 0x52, 0xa6, 0x26, 0x33,
	0x32, 0x25, 0xea, 0xeb, 0x28, 0x57, 0xef, 0xc0, 0xa4, 0xe8, 0x79, 0x01, 0x17, 0x24, 0x0c, 0xc3,
	0x83, 0x79, 0x4b, 0x8c, 0x03, 0x49, 0x5a, 0xe2, 0x65, 0xdb, 0x23, 0x37, 0x75, 0x4a, 0x55, 0x11,
	0x56, 0x4e, 0x72, 0x4c, 0x14, 0x8c, 0x08, 0x9d, 0xe0, 0xc9, 0x32, 0xcc, 0x78, 0x18, 0xfb, 0x1c,
	0xbd, 0x4e, 0x9c, 0x38, 0x89, 0xaa, 0xc7, 0xb3, 0xd9, 0x1d, 0x20, 0x3a, 0x7c, 0x43, 0x40, 0xe2,
	0x52, 0x5a, 0x25, 0x9f, 0xc9, 0x22, 0xe4, 0x39, 0x0b, 0xd0, 0x9e, 0x92, 0xe2, 0xcb, 0xe3, 0x06,
	0x18, 0x65, 0x81, 0x1c, 0x62, 0x82, 0x25, 0x6d, 0x80, 0x10, 0xc3, 0x6d, 0xe4, 0xf1, 0x7d, 0xbf,
	0x67, 0x4f, 0x4b, 0xe5, 0x7b, 0xe3, 0x94, 0x1b, 0x3d, 0x74, 0x6b, 0x2b, 0x87, 0xb8, 0x48, 0xee,
	0x91, 0x98, 0xac, 0xc0, 0x05, 0x8e, 0x3b, 0xc8, 0x31, 0x72, 0xd1, 0xeb, 0xe8, 0x99, 0x25, 0x22,
	0x36, 0x23, 0x23, 0x76, 0x69, 0x78, 0x30, 0x7f, 0x9e, 0x1e, 0x02, 0x7a, 0xbc, 0xc9, 0xf0, 0x9d,
	0xe7, 0xaf, 0x6c, 0x7b, 0xe4, 0x2b, 0x98, 0x3b, 0x66, 0x4e, 0x8d, 0x18, 0x61, 0xed, 0xac, 0xb4,
	0x76, 0x71, 0x78, 0x30, 0x4f, 0x8e, 0xac, 0xa9, 0x59, 0x24, 0x8d, 0x11, 0x3e, 0xba, 0x3b, 0x6a,
	0x4b, 0x75, 0xbf, 0xb0, 0x35, 0x9b, 0x65, 0x4b, 0x8d, 0x89, 0x51, 0x5b, 0x7a, 0x57, 0x34, 0x9f,
	0x6a, 0xc8, 0x73, 0x69, 0xf1, 0x8b, 0xa7, 0x7a, 0x1e, 0x72, 0xf5, 0xfd, 0xea, 0x1f, 0x39, 0x98,
	0xbe, 0x27, 0x3e, 0xa3, 0x14, 0xbf, 0xe9, 0x63, 0x9c, 0x90, 0x26, 0x4c, 0x62, 0x94, 0x70, 0x1f,
	0x63, 0xdb, 0xac, 0x9c, 0xb9, 0x32, 0xb5, 0x78, 0x2d, 0x2b, 0xb6, 0xc7, 0x25, 0xea, 0xa1, 0x19,
	0x25, 0x7c, 0x9f, 0xa6, 0x5a, 0x72, 0x1b, 0xa6, 0x38, 0xc6, 0xfd, 0x10, 0x3b, 0x3b, 0x9c, 0x85,
	0x27, 0x7d, 0x6e, 0xee, 0x22, 0x17, 0x03, 0x91, 0x82, 0xe2, 0xbf, 0xe4, 0x2c, 0x24, 0xd7, 0x81,
	0xf8, 0x91, 0x1b, 0xf4, 0x3d, 0xec, 0xb0, 0xc0, 0xeb, 0xa8, 0x6f, 0xaf, 0x6c, 0xde, 0x02, 0x9d,
	0xd5, 0x6f, 0xd6, 0x02, 0x4f, 0x0d, 0xb5, 0xd2, 0x0f, 0x26, 0xc0, 0x91, 0x0f, 0x99, 0xf3, 0xe7,
	0x33, 0xb0, 0x1c, 0x37, 0x11, 0x93, 0x3a, 0x27, 0x0b, 0xe6, 0xad, 0xb1, 0x97, 0x5a, 0x92, 0xd8,
	0x1d, 0x3f, 0xf2, 0xa8, 0x96, 0x90, 0x9b, 0x30, 0xb9, 0xe3, 0x07, 0x09, 0xf2, 0xd8, 0x3e, 0x23,
	0x43, 0x72, 0xf9, 0xa4, 0x36, 0xa1, 0x29, 0x5c, 0xfd, 0x2d, 0x8d, 0xed, 0x0a, 0xc6, 0xb1, 0xd3,
	0x45, 0xf2, 0x05, 0x58, 0x38, 0xc0, 0x28, 0x49, 0x43, 0xfb, 0xee, 0x58, 0x2f, 0xb4, 0xa2, 0xd6,
	0x14, 0x38, 0xd5, 0x2a, 0xf2, 0x31, 0x4c, 0x0e, 0x54, 0xb4, 0xfe, 0x4b, 0x40, 0x53, 0xb6, 0xf4,
	0xab, 0x09, 0x13, 0xd2, 0xd0, 0xb1, 0x30, 0x98, 0xaf, 0x1f, 0x86, 0x45, 0xb0, 0x74, 0x22, 0x72,
	0xe3, 0xbf, 0x3d, 0x2a, 0x25, 0x54, 0x93, 0xe4, 0x13, 0x80, 0x91, 0x04, 0x9e, 0xac, 0x2b, 0xb2,
	0x34, 0xab, 0x57, 0xff, 0x31, 0xe1, 0xdc, 0x88, 0x2b, 0xe4, 0x06, 0xcc, 0xdd, 0x5b, 0xda, 0x6c,
	0xb4, 0x3a, 0x4b, 0x8d, 0xcd, 0xf6, 0xda, 0x6a, 0x67, 0x6b, 0xf5, 0xce, 0xea, 0xda, 0xbd, 0xd5,
	0x59, 0xa3, 0x54, 0x7a, 0xf8, 0xa8, 0x72, 0x71, 0x04, 0xdf, 0x8a, 0x76, 0x23, 0xb6, 0x27, 0x1c,
	0x3f, 0xff, 0x92, 0xaa, 0x41, 0x9b, 0x4b, 0x9b, 0xcd, 0x59, 0xb3, 0xf4, 0xbf, 0x87, 0x8f, 0x2a,
	0x17, 0x46, 0x44, 0x0d, 0x8e, 0x6a, 0x32, 0xbd, 0xac, 0xd9, 0x5a, 0x5f, 0x16, 0x9a, 0x5c, 0xa6,
	0x66, 0xab, 0xe7, 0x65, 0x69, 0x68, 0x73, 0x65, 0xed, 0x6e, 0x73, 0x36, 0x9f, 0xa9, 0xa1, 0x18,
	0xb2, 0x01, 0x96, 0x2e, 0x7d, 0xf7, 0x53, 0xd9, 0x78, 0xfc, 0x73, 0x79, 0xf4, 0xaa, 0x8b, 0x21,
	0x4c, 0xc8, 0x2d, 0xe2, 0xa5, 0x8b, 0xca, 0x69, 0x8d, 0x58, 0xaa, 0x9c, 0x56, 0x4f, 0xd5, 0x0b,
	0xbf, 0xff, 0xf2, 0xf7, 0x8f, 0xb9, 0x73, 0x30, 0x23, 0x89, 0xf7, 0x43, 0x27, 0x72, 0xba, 0xc8,
	0x3f, 0x30, 0xeb, 0x6f, 0x3f, 0x79, 0x5e, 0x36, 0x9e, 0x3d, 0x2f, 0x1b, 0xdf, 0x0e, 0xcb, 0xe6,
	0x93, 0x61, 0xd9, 0x7c, 0x3a, 0x2c, 0x9b, 0x7f, 0x0e, 0xcb, 0xe6, 0xf7, 0x2f, 0xca, 0xc6, 0xd3,
	0x17, 0x65, 0xe3, 0xd9, 0x8b, 0xb2, 0xb1, 0x6d, 0xc9, 0xbf, 0xa0, 0x1f, 0xfd, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x36, 0x4b, 0xa7, 0x78, 0x99, 0x0b, 0x00, 0x00,
}

type authenticatedWrapperWatchServer struct {
	local     WatchServer
	authorize func(context.Context, []string) error
}

func NewAuthenticatedWrapperWatchServer(local WatchServer, authorize func(context.Context, []string) error) WatchServer {
	_ = "STUB: not implemented"
	return *new(WatchServer)
}

func (p *authenticatedWrapperWatchServer) Watch(r *WatchRequest, stream Watch_WatchServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Object) Copy() *Object { _ = "STUB: not implemented"; return nil }

func (m *Object) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *SelectBySlot) Copy() *SelectBySlot { _ = "STUB: not implemented"; return nil }

func (m *SelectBySlot) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *SelectByCustom) Copy() *SelectByCustom { _ = "STUB: not implemented"; return nil }

func (m *SelectByCustom) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *SelectBy) Copy() *SelectBy { _ = "STUB: not implemented"; return nil }

func (m *SelectBy) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *WatchRequest) Copy() *WatchRequest { _ = "STUB: not implemented"; return nil }

func (m *WatchRequest) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *WatchRequest_WatchEntry) Copy() *WatchRequest_WatchEntry {
	_ = "STUB: not implemented"
	return nil
}

func (m *WatchRequest_WatchEntry) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *WatchMessage) Copy() *WatchMessage { _ = "STUB: not implemented"; return nil }

func (m *WatchMessage) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *WatchMessage_Event) Copy() *WatchMessage_Event { _ = "STUB: not implemented"; return nil }

func (m *WatchMessage_Event) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WatchClient is the client API for Watch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WatchClient interface {
	// Watch starts a stream that returns any changes to objects that match
	// the specified selectors. When the stream begins, it immediately sends
	// an empty message back to the client. It is important to wait for
	// this message before taking any actions that depend on an established
	// stream of changes for consistency.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Watch_WatchClient, error)
}

type watchClient struct {
	cc *grpc.ClientConn
}

func NewWatchClient(cc *grpc.ClientConn) WatchClient {
	_ = "STUB: not implemented"
	return *new(WatchClient)
}

func (c *watchClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Watch_WatchClient, error) {
	_ = "STUB: not implemented"
	return *new(Watch_WatchClient), nil
}

type Watch_WatchClient interface {
	Recv() (*WatchMessage, error)
	grpc.ClientStream
}

type watchWatchClient struct {
	grpc.ClientStream
}

func (x *watchWatchClient) Recv() (*WatchMessage, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WatchServer is the server API for Watch service.
type WatchServer interface {
	// Watch starts a stream that returns any changes to objects that match
	// the specified selectors. When the stream begins, it immediately sends
	// an empty message back to the client. It is important to wait for
	// this message before taking any actions that depend on an established
	// stream of changes for consistency.
	Watch(*WatchRequest, Watch_WatchServer) error
}

// UnimplementedWatchServer can be embedded to have forward compatible implementations.
type UnimplementedWatchServer struct {
}

func (*UnimplementedWatchServer) Watch(req *WatchRequest, srv Watch_WatchServer) error {
	_ = "STUB: not implemented"
	return nil
}

func RegisterWatchServer(s *grpc.Server, srv WatchServer) { _ = "STUB: not implemented"; return }

func _Watch_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type Watch_WatchServer interface {
	Send(*WatchMessage) error
	grpc.ServerStream
}

type watchWatchServer struct {
	grpc.ServerStream
}

func (x *watchWatchServer) Send(m *WatchMessage) error { _ = "STUB: not implemented"; return nil }

var _Watch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "docker.swarmkit.v1.Watch",
	HandlerType: (*WatchServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Watch_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/docker/swarmkit/api/watch.proto",
}

func (m *Object) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Object) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Object) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Node) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Object_Node) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Service) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Service) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Network) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Network) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Task) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Object_Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Cluster) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Cluster) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Secret) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Secret) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Resource) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Resource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Extension) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Extension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Config) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Volume) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Object_Volume) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBySlot) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SelectBySlot) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBySlot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectByCustom) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SelectByCustom) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectByCustom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *SelectBy) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SelectBy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ID) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SelectBy_ID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_IDPrefix) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_IDPrefix) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Name) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Name) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_NamePrefix) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_NamePrefix) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Custom) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Custom) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_CustomPrefix) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_CustomPrefix) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ServiceID) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ServiceID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_NodeID) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_NodeID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Slot) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Slot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_DesiredState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_DesiredState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Role) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Role) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Membership) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Membership) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ReferencedNetworkID) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ReferencedNetworkID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ReferencedSecretID) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ReferencedSecretID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Kind) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_Kind) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ReferencedConfigID) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SelectBy_ReferencedConfigID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchRequest_WatchEntry) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchRequest_WatchEntry) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchRequest_WatchEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchMessage_Event) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WatchMessage_Event) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WatchMessage_Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintWatch(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

type raftProxyWatchServer struct {
	local                       WatchServer
	connSelector                raftselector.ConnProvider
	localCtxMods, remoteCtxMods []func(context.Context) (context.Context, error)
}

func NewRaftProxyWatchServer(local WatchServer, connSelector raftselector.ConnProvider, localCtxMod, remoteCtxMod func(context.Context) (context.Context, error)) WatchServer {
	_ = "STUB: not implemented"
	return *new(WatchServer)
}

func (p *raftProxyWatchServer) runCtxMods(ctx context.Context, ctxMods []func(context.Context) (context.Context, error)) (context.Context, error) {
	_ = "STUB: not implemented"
	return *new(context.Context), nil
}

func (p *raftProxyWatchServer) pollNewLeaderConn(ctx context.Context) (*grpc.ClientConn, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

type Watch_WatchServerWrapper struct {
	Watch_WatchServer
	ctx context.Context
}

func (s Watch_WatchServerWrapper) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

func (p *raftProxyWatchServer) Watch(r *WatchRequest, stream Watch_WatchServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Object) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Node) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Service) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Network) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Task) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Cluster) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Secret) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Resource) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Extension) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Config) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Object_Volume) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBySlot) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectByCustom) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_ID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_IDPrefix) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_Name) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_NamePrefix) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_Custom) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_CustomPrefix) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_ServiceID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_NodeID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_Slot) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_DesiredState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_Role) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_Membership) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_ReferencedNetworkID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_ReferencedSecretID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_Kind) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SelectBy_ReferencedConfigID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WatchRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WatchRequest_WatchEntry) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WatchMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WatchMessage_Event) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovWatch(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozWatch(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (this *Object) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Node) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Service) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Network) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Task) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Cluster) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Secret) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Resource) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Extension) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Config) String() string { _ = "STUB: not implemented"; return "" }

func (this *Object_Volume) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBySlot) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectByCustom) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_ID) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_IDPrefix) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_Name) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_NamePrefix) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_Custom) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_CustomPrefix) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_ServiceID) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_NodeID) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_Slot) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_DesiredState) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_Role) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_Membership) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_ReferencedNetworkID) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_ReferencedSecretID) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_Kind) String() string { _ = "STUB: not implemented"; return "" }

func (this *SelectBy_ReferencedConfigID) String() string { _ = "STUB: not implemented"; return "" }

func (this *WatchRequest) String() string { _ = "STUB: not implemented"; return "" }

func (this *WatchRequest_WatchEntry) String() string { _ = "STUB: not implemented"; return "" }

func (this *WatchMessage) String() string { _ = "STUB: not implemented"; return "" }

func (this *WatchMessage_Event) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringWatch(v interface{}) string { _ = "STUB: not implemented"; return "" }

func (m *Object) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectBySlot) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectByCustom) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SelectBy) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WatchRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WatchRequest_WatchEntry) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WatchMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WatchMessage_Event) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipWatch(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthWatch        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWatch          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWatch = fmt.Errorf("proto: unexpected end of group")
)
