// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/docker/swarmkit/protobuf/plugin/deepcopy/test/deepcopy.proto

package test

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BasicScalar struct {
	Field1  float64 `protobuf:"fixed64,1,opt,name=Field1,proto3" json:"Field1,omitempty"`
	Field2  float32 `protobuf:"fixed32,2,opt,name=Field2,proto3" json:"Field2,omitempty"`
	Field3  int32   `protobuf:"varint,3,opt,name=Field3,proto3" json:"Field3,omitempty"`
	Field4  int64   `protobuf:"varint,4,opt,name=Field4,proto3" json:"Field4,omitempty"`
	Field5  uint32  `protobuf:"varint,5,opt,name=Field5,proto3" json:"Field5,omitempty"`
	Field6  uint64  `protobuf:"varint,6,opt,name=Field6,proto3" json:"Field6,omitempty"`
	Field7  int32   `protobuf:"zigzag32,7,opt,name=Field7,proto3" json:"Field7,omitempty"`
	Field8  int64   `protobuf:"zigzag64,8,opt,name=Field8,proto3" json:"Field8,omitempty"`
	Field9  uint32  `protobuf:"fixed32,9,opt,name=Field9,proto3" json:"Field9,omitempty"`
	Field10 int32   `protobuf:"fixed32,10,opt,name=Field10,proto3" json:"Field10,omitempty"`
	Field11 uint64  `protobuf:"fixed64,11,opt,name=Field11,proto3" json:"Field11,omitempty"`
	Field12 int64   `protobuf:"fixed64,12,opt,name=Field12,proto3" json:"Field12,omitempty"`
	Field13 bool    `protobuf:"varint,13,opt,name=Field13,proto3" json:"Field13,omitempty"`
	Field14 string  `protobuf:"bytes,14,opt,name=Field14,proto3" json:"Field14,omitempty"`
	Field15 []byte  `protobuf:"bytes,15,opt,name=Field15,proto3" json:"Field15,omitempty"`
}

func (m *BasicScalar) Reset()                    { _ = "STUB: not implemented"; return }
func (*BasicScalar) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BasicScalar) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BasicScalar) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BasicScalar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BasicScalar) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BasicScalar) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BasicScalar) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BasicScalar proto.InternalMessageInfo

type RepeatedScalar struct {
	Field1  []float64 `protobuf:"fixed64,1,rep,packed,name=Field1,proto3" json:"Field1,omitempty"`
	Field2  []float32 `protobuf:"fixed32,2,rep,packed,name=Field2,proto3" json:"Field2,omitempty"`
	Field3  []int32   `protobuf:"varint,3,rep,packed,name=Field3,proto3" json:"Field3,omitempty"`
	Field4  []int64   `protobuf:"varint,4,rep,packed,name=Field4,proto3" json:"Field4,omitempty"`
	Field5  []uint32  `protobuf:"varint,5,rep,packed,name=Field5,proto3" json:"Field5,omitempty"`
	Field6  []uint64  `protobuf:"varint,6,rep,packed,name=Field6,proto3" json:"Field6,omitempty"`
	Field7  []int32   `protobuf:"zigzag32,7,rep,packed,name=Field7,proto3" json:"Field7,omitempty"`
	Field8  []int64   `protobuf:"zigzag64,8,rep,packed,name=Field8,proto3" json:"Field8,omitempty"`
	Field9  []uint32  `protobuf:"fixed32,9,rep,packed,name=Field9,proto3" json:"Field9,omitempty"`
	Field10 []int32   `protobuf:"fixed32,10,rep,packed,name=Field10,proto3" json:"Field10,omitempty"`
	Field11 []uint64  `protobuf:"fixed64,11,rep,packed,name=Field11,proto3" json:"Field11,omitempty"`
	Field12 []int64   `protobuf:"fixed64,12,rep,packed,name=Field12,proto3" json:"Field12,omitempty"`
	Field13 []bool    `protobuf:"varint,13,rep,packed,name=Field13,proto3" json:"Field13,omitempty"`
	Field14 []string  `protobuf:"bytes,14,rep,name=Field14,proto3" json:"Field14,omitempty"`
	Field15 [][]byte  `protobuf:"bytes,15,rep,name=Field15,proto3" json:"Field15,omitempty"`
}

func (m *RepeatedScalar) Reset()                    { _ = "STUB: not implemented"; return }
func (*RepeatedScalar) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RepeatedScalar) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RepeatedScalar) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RepeatedScalar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedScalar) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RepeatedScalar) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RepeatedScalar) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RepeatedScalar proto.InternalMessageInfo

type RepeatedScalarPacked struct {
	Field1  []float64 `protobuf:"fixed64,1,rep,packed,name=Field1,proto3" json:"Field1,omitempty"`
	Field2  []float32 `protobuf:"fixed32,2,rep,packed,name=Field2,proto3" json:"Field2,omitempty"`
	Field3  []int32   `protobuf:"varint,3,rep,packed,name=Field3,proto3" json:"Field3,omitempty"`
	Field4  []int64   `protobuf:"varint,4,rep,packed,name=Field4,proto3" json:"Field4,omitempty"`
	Field5  []uint32  `protobuf:"varint,5,rep,packed,name=Field5,proto3" json:"Field5,omitempty"`
	Field6  []uint64  `protobuf:"varint,6,rep,packed,name=Field6,proto3" json:"Field6,omitempty"`
	Field7  []int32   `protobuf:"zigzag32,7,rep,packed,name=Field7,proto3" json:"Field7,omitempty"`
	Field8  []int64   `protobuf:"zigzag64,8,rep,packed,name=Field8,proto3" json:"Field8,omitempty"`
	Field9  []uint32  `protobuf:"fixed32,9,rep,packed,name=Field9,proto3" json:"Field9,omitempty"`
	Field10 []int32   `protobuf:"fixed32,10,rep,packed,name=Field10,proto3" json:"Field10,omitempty"`
	Field11 []uint64  `protobuf:"fixed64,11,rep,packed,name=Field11,proto3" json:"Field11,omitempty"`
	Field12 []int64   `protobuf:"fixed64,12,rep,packed,name=Field12,proto3" json:"Field12,omitempty"`
	Field13 []bool    `protobuf:"varint,13,rep,packed,name=Field13,proto3" json:"Field13,omitempty"`
}

func (m *RepeatedScalarPacked) Reset()      { _ = "STUB: not implemented"; return }
func (*RepeatedScalarPacked) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*RepeatedScalarPacked) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedScalarPacked) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RepeatedScalarPacked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedScalarPacked) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RepeatedScalarPacked) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RepeatedScalarPacked) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RepeatedScalarPacked proto.InternalMessageInfo

type ExternalStruct struct {
	Field1 *BasicScalar          `protobuf:"bytes,1,opt,name=Field1,proto3" json:"Field1,omitempty"`
	Field2 *RepeatedScalar       `protobuf:"bytes,2,opt,name=Field2,proto3" json:"Field2,omitempty"`
	Field3 *RepeatedScalarPacked `protobuf:"bytes,3,opt,name=Field3,proto3" json:"Field3,omitempty"`
}

func (m *ExternalStruct) Reset()                    { _ = "STUB: not implemented"; return }
func (*ExternalStruct) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ExternalStruct) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ExternalStruct) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ExternalStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExternalStruct) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ExternalStruct) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ExternalStruct) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ExternalStruct proto.InternalMessageInfo

type RepeatedExternalStruct struct {
	Field1 []*BasicScalar          `protobuf:"bytes,1,rep,name=Field1,proto3" json:"Field1,omitempty"`
	Field2 []*RepeatedScalar       `protobuf:"bytes,2,rep,name=Field2,proto3" json:"Field2,omitempty"`
	Field3 []*RepeatedScalarPacked `protobuf:"bytes,3,rep,name=Field3,proto3" json:"Field3,omitempty"`
}

func (m *RepeatedExternalStruct) Reset()      { _ = "STUB: not implemented"; return }
func (*RepeatedExternalStruct) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*RepeatedExternalStruct) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedExternalStruct) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RepeatedExternalStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedExternalStruct) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RepeatedExternalStruct) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RepeatedExternalStruct) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RepeatedExternalStruct proto.InternalMessageInfo

type NonNullableExternalStruct struct {
	Field1 BasicScalar          `protobuf:"bytes,1,opt,name=Field1,proto3" json:"Field1"`
	Field2 RepeatedScalar       `protobuf:"bytes,2,opt,name=Field2,proto3" json:"Field2"`
	Field3 RepeatedScalarPacked `protobuf:"bytes,3,opt,name=Field3,proto3" json:"Field3"`
}

func (m *NonNullableExternalStruct) Reset()      { _ = "STUB: not implemented"; return }
func (*NonNullableExternalStruct) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*NonNullableExternalStruct) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NonNullableExternalStruct) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *NonNullableExternalStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NonNullableExternalStruct) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NonNullableExternalStruct) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NonNullableExternalStruct) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NonNullableExternalStruct proto.InternalMessageInfo

type RepeatedNonNullableExternalStruct struct {
	Field1 []BasicScalar          `protobuf:"bytes,1,rep,name=Field1,proto3" json:"Field1"`
	Field2 []RepeatedScalar       `protobuf:"bytes,2,rep,name=Field2,proto3" json:"Field2"`
	Field3 []RepeatedScalarPacked `protobuf:"bytes,3,rep,name=Field3,proto3" json:"Field3"`
}

func (m *RepeatedNonNullableExternalStruct) Reset()      { _ = "STUB: not implemented"; return }
func (*RepeatedNonNullableExternalStruct) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*RepeatedNonNullableExternalStruct) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedNonNullableExternalStruct) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RepeatedNonNullableExternalStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RepeatedNonNullableExternalStruct) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *RepeatedNonNullableExternalStruct) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RepeatedNonNullableExternalStruct) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RepeatedNonNullableExternalStruct proto.InternalMessageInfo

type MapStruct struct {
	NullableMap    map[string]*BasicScalar `protobuf:"bytes,1,rep,name=nullable_map,json=nullableMap,proto3" json:"nullable_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NonnullableMap map[string]BasicScalar  `protobuf:"bytes,2,rep,name=nonnullable_map,json=nonnullableMap,proto3" json:"nonnullable_map" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *MapStruct) Reset()                    { _ = "STUB: not implemented"; return }
func (*MapStruct) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MapStruct) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MapStruct) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MapStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MapStruct) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MapStruct) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MapStruct) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MapStruct proto.InternalMessageInfo

type OneOf struct {
	// Types that are valid to be assigned to Fields:
	//
	//	*OneOf_Field1
	//	*OneOf_Field2
	//	*OneOf_Field3
	//	*OneOf_Field4
	//	*OneOf_Field5
	//	*OneOf_Field6
	//	*OneOf_Field7
	//	*OneOf_Field8
	//	*OneOf_Field9
	Fields isOneOf_Fields `protobuf_oneof:"fields"`
	// Types that are valid to be assigned to FieldsTwo:
	//
	//	*OneOf_Field10
	//	*OneOf_Field11
	FieldsTwo isOneOf_FieldsTwo `protobuf_oneof:"fieldsTwo"`
}

func (m *OneOf) Reset()                    { _ = "STUB: not implemented"; return }
func (*OneOf) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*OneOf) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *OneOf) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *OneOf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *OneOf) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *OneOf) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *OneOf) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_OneOf proto.InternalMessageInfo

type isOneOf_Fields interface {
	isOneOf_Fields()
	Equal(interface{}) bool
}
type isOneOf_FieldsTwo interface {
	isOneOf_FieldsTwo()
	Equal(interface{}) bool
}

type OneOf_Field1 struct {
	Field1 float64 `protobuf:"fixed64,1,opt,name=Field1,proto3,oneof" json:"Field1,omitempty"`
}
type OneOf_Field2 struct {
	Field2 float32 `protobuf:"fixed32,2,opt,name=Field2,proto3,oneof" json:"Field2,omitempty"`
}
type OneOf_Field3 struct {
	Field3 int32 `protobuf:"varint,3,opt,name=Field3,proto3,oneof" json:"Field3,omitempty"`
}
type OneOf_Field4 struct {
	Field4 int64 `protobuf:"varint,4,opt,name=Field4,proto3,oneof" json:"Field4,omitempty"`
}
type OneOf_Field5 struct {
	Field5 uint32 `protobuf:"varint,5,opt,name=Field5,proto3,oneof" json:"Field5,omitempty"`
}
type OneOf_Field6 struct {
	Field6 string `protobuf:"bytes,6,opt,name=Field6,proto3,oneof" json:"Field6,omitempty"`
}
type OneOf_Field7 struct {
	Field7 []byte `protobuf:"bytes,7,opt,name=Field7,proto3,oneof" json:"Field7,omitempty"`
}
type OneOf_Field8 struct {
	Field8 *MapStruct `protobuf:"bytes,8,opt,name=Field8,proto3,oneof" json:"Field8,omitempty"`
}
type OneOf_Field9 struct {
	Field9 *RepeatedNonNullableExternalStruct `protobuf:"bytes,9,opt,name=Field9,proto3,oneof" json:"Field9,omitempty"`
}
type OneOf_Field10 struct {
	Field10 *NonNullableExternalStruct `protobuf:"bytes,10,opt,name=Field10,proto3,oneof" json:"Field10,omitempty"`
}
type OneOf_Field11 struct {
	Field11 *RepeatedExternalStruct `protobuf:"bytes,11,opt,name=Field11,proto3,oneof" json:"Field11,omitempty"`
}

func (*OneOf_Field1) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field2) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field3) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field4) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field5) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field6) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field7) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field8) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field9) isOneOf_Fields()     { _ = "STUB: not implemented"; return }
func (*OneOf_Field10) isOneOf_FieldsTwo() { _ = "STUB: not implemented"; return }
func (*OneOf_Field11) isOneOf_FieldsTwo() { _ = "STUB: not implemented"; return }

func (m *OneOf) GetFields() isOneOf_Fields { _ = "STUB: not implemented"; return *new(isOneOf_Fields) }

func (m *OneOf) GetFieldsTwo() isOneOf_FieldsTwo {
	_ = "STUB: not implemented"
	return *new(isOneOf_FieldsTwo)
}

func (m *OneOf) GetField1() float64 { _ = "STUB: not implemented"; return 0 }

func (m *OneOf) GetField2() float32 { _ = "STUB: not implemented"; return 0 }

func (m *OneOf) GetField3() int32 { _ = "STUB: not implemented"; return 0 }

func (m *OneOf) GetField4() int64 { _ = "STUB: not implemented"; return 0 }

func (m *OneOf) GetField5() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *OneOf) GetField6() string { _ = "STUB: not implemented"; return "" }

func (m *OneOf) GetField7() []byte { _ = "STUB: not implemented"; return nil }

func (m *OneOf) GetField8() *MapStruct { _ = "STUB: not implemented"; return nil }

func (m *OneOf) GetField9() *RepeatedNonNullableExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func (m *OneOf) GetField10() *NonNullableExternalStruct { _ = "STUB: not implemented"; return nil }

func (m *OneOf) GetField11() *RepeatedExternalStruct { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneOf) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*BasicScalar)(nil), "test.BasicScalar")
	proto.RegisterType((*RepeatedScalar)(nil), "test.RepeatedScalar")
	proto.RegisterType((*RepeatedScalarPacked)(nil), "test.RepeatedScalarPacked")
	proto.RegisterType((*ExternalStruct)(nil), "test.ExternalStruct")
	proto.RegisterType((*RepeatedExternalStruct)(nil), "test.RepeatedExternalStruct")
	proto.RegisterType((*NonNullableExternalStruct)(nil), "test.NonNullableExternalStruct")
	proto.RegisterType((*RepeatedNonNullableExternalStruct)(nil), "test.RepeatedNonNullableExternalStruct")
	proto.RegisterType((*MapStruct)(nil), "test.MapStruct")
	proto.RegisterMapType((map[string]BasicScalar)(nil), "test.MapStruct.NonnullableMapEntry")
	proto.RegisterMapType((map[string]*BasicScalar)(nil), "test.MapStruct.NullableMapEntry")
	proto.RegisterType((*OneOf)(nil), "test.OneOf")
}

func init() {
	proto.RegisterFile("github.com/docker/swarmkit/protobuf/plugin/deepcopy/test/deepcopy.proto", fileDescriptor_32a357b2839a6c60)
}

var fileDescriptor_32a357b2839a6c60 = []byte{
	// 915 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0x3f, 0x6f, 0x23, 0x45,
	0x18, 0x87, 0x67, 0x3c, 0x89, 0x13, 0xcf, 0xe6, 0x92, 0xdc, 0x72, 0x3a, 0x0d, 0x56, 0x34, 0x37,
	0x98, 0xe2, 0x16, 0x09, 0x6c, 0x3c, 0x6b, 0x27, 0x0e, 0x54, 0x18, 0x1d, 0x5c, 0x73, 0x7f, 0xf0,
	0x5d, 0x8f, 0x36, 0xf6, 0x26, 0x58, 0x71, 0x76, 0x2d, 0x67, 0xcd, 0x91, 0xee, 0x90, 0xa8, 0xa8,
	0xf8, 0x02, 0x48, 0x34, 0x48, 0x7c, 0x04, 0xa0, 0xa4, 0x4a, 0x83, 0x94, 0xf2, 0x2a, 0x84, 0xd7,
	0xcd, 0x95, 0x57, 0x5e, 0x89, 0xec, 0x9d, 0x7d, 0x77, 0xc7, 0x78, 0xc0, 0x81, 0x6e, 0xe7, 0xf7,
	0xcc, 0x8c, 0xdf, 0xd9, 0x67, 0x3d, 0x7a, 0xe9, 0xa7, 0x27, 0xfd, 0xe8, 0x8b, 0xf1, 0x51, 0xb5,
	0x1b, 0x9e, 0xd5, 0x7a, 0x61, 0xf7, 0xd4, 0x1f, 0xd5, 0xce, 0x9f, 0x79, 0xa3, 0xb3, 0xd3, 0x7e,
	0x54, 0x1b, 0x8e, 0xc2, 0x28, 0x3c, 0x1a, 0x1f, 0xd7, 0x86, 0x83, 0xf1, 0x49, 0x3f, 0xa8, 0xf5,
	0x7c, 0x7f, 0xd8, 0x0d, 0x87, 0x17, 0xb5, 0xc8, 0x3f, 0x8f, 0x60, 0x54, 0x9d, 0x4f, 0xb3, 0xd7,
	0x66, 0x61, 0xf9, 0xbd, 0xdc, 0x76, 0x27, 0xe1, 0x49, 0x98, 0xed, 0x31, 0x1b, 0xcd, 0x07, 0xf3,
	0xa7, 0x64, 0x51, 0xe5, 0x6b, 0x42, 0xad, 0xb6, 0x77, 0xde, 0xef, 0x3e, 0xe9, 0x7a, 0x03, 0x6f,
	0x64, 0xdf, 0xa6, 0xc5, 0x4f, 0xfa, 0xfe, 0xa0, 0x57, 0x67, 0x58, 0x60, 0x07, 0x77, 0xd4, 0x08,
	0x72, 0xc9, 0x0a, 0x02, 0x3b, 0x05, 0x95, 0x4b, 0xc8, 0x5d, 0x46, 0x04, 0x76, 0xd6, 0x55, 0xee,
	0x42, 0xde, 0x60, 0x6b, 0x02, 0x3b, 0x44, 0xe5, 0x0d, 0xc8, 0x9b, 0x6c, 0x5d, 0x60, 0xe7, 0x86,
	0xca, 0x9b, 0x90, 0xef, 0xb3, 0xa2, 0xc0, 0xce, 0x9a, 0xca, 0xf7, 0x21, 0x3f, 0x60, 0x1b, 0x02,
	0x3b, 0x37, 0x55, 0x7e, 0x00, 0x79, 0x8b, 0x6d, 0x0a, 0xec, 0xd8, 0x2a, 0x6f, 0x41, 0x7e, 0xc8,
	0x4a, 0x02, 0x3b, 0x1b, 0x2a, 0x3f, 0xb4, 0x19, 0xdd, 0x48, 0x4e, 0xf2, 0x3e, 0xa3, 0x02, 0x3b,
	0x3b, 0x9d, 0x74, 0x98, 0x91, 0x3a, 0xb3, 0x04, 0x76, 0x8a, 0x29, 0xa9, 0x67, 0x44, 0xb2, 0x2d,
	0x81, 0x9d, 0xdd, 0x94, 0xc8, 0x8c, 0xb8, 0xec, 0x86, 0xc0, 0xce, 0x66, 0x4a, 0xdc, 0x8c, 0x34,
	0xd8, 0xb6, 0xc0, 0x4e, 0x29, 0x25, 0x8d, 0x8c, 0x34, 0xd9, 0x8e, 0xc0, 0xce, 0x56, 0x4a, 0x9a,
	0x95, 0x6f, 0x08, 0xdd, 0xee, 0xf8, 0x43, 0xdf, 0x8b, 0xfc, 0xde, 0x12, 0x0d, 0xc4, 0xa0, 0x81,
	0x18, 0x34, 0x10, 0x83, 0x06, 0x62, 0xd0, 0x40, 0x0c, 0x1a, 0x88, 0x41, 0x03, 0x31, 0x68, 0x20,
	0x06, 0x0d, 0xc4, 0xa4, 0x81, 0x18, 0x35, 0x10, 0xa3, 0x06, 0x62, 0xd4, 0x40, 0x8c, 0x1a, 0x88,
	0x51, 0x03, 0xc9, 0x6b, 0xf8, 0x96, 0xd0, 0x5b, 0xba, 0x86, 0xc7, 0x5e, 0xf7, 0xd4, 0xef, 0xd9,
	0x65, 0x5d, 0x46, 0xbb, 0xb0, 0x9b, 0x09, 0x29, 0xeb, 0x42, 0x72, 0x4c, 0x02, 0x53, 0x52, 0x72,
	0xcc, 0x05, 0xa6, 0xc4, 0xe4, 0x58, 0x03, 0x98, 0x92, 0x93, 0x63, 0x4d, 0x60, 0x4a, 0x50, 0x8e,
	0xed, 0x03, 0x53, 0x92, 0x72, 0xec, 0x00, 0x98, 0x12, 0x95, 0x63, 0x2d, 0x60, 0x4a, 0x56, 0x8e,
	0x1d, 0xda, 0x7b, 0x0b, 0xc2, 0xe6, 0x10, 0xa4, 0xed, 0x2d, 0x48, 0xcb, 0xd3, 0x7a, 0x46, 0x95,
	0xb8, 0x3c, 0x95, 0x19, 0x55, 0xf2, 0xf2, 0xd4, 0xad, 0x7c, 0x8f, 0xe9, 0xf6, 0xbd, 0xaf, 0x22,
	0x7f, 0x14, 0x78, 0x83, 0x27, 0xd1, 0x68, 0xdc, 0x8d, 0xec, 0x77, 0xb4, 0xab, 0xc9, 0x92, 0x37,
	0xab, 0xb3, 0x0b, 0xaf, 0x9a, 0xbb, 0xbd, 0xc0, 0xca, 0xbb, 0xda, 0x6d, 0x65, 0xc9, 0x5b, 0xc9,
	0x54, 0xdd, 0x2e, 0x78, 0x92, 0xda, 0x1d, 0x66, 0xc9, 0xf2, 0xb2, 0xd9, 0xc9, 0xb7, 0x90, 0xfa,
	0xab, 0xfc, 0x88, 0xe9, 0xed, 0x74, 0xc2, 0x3f, 0xd4, 0x49, 0x56, 0xaf, 0x93, 0x5c, 0xab, 0x4e,
	0xb2, 0x62, 0x9d, 0xbf, 0x62, 0xfa, 0xe6, 0xc3, 0x30, 0x78, 0x38, 0x1e, 0x0c, 0xbc, 0xa3, 0x81,
	0xbf, 0x50, 0x6a, 0xed, 0x5f, 0x5f, 0x69, 0x7b, 0xed, 0xf2, 0x8f, 0x3b, 0x08, 0x0a, 0x96, 0xab,
	0xbc, 0x58, 0x6d, 0x8d, 0xb4, 0x5b, 0xab, 0xbf, 0x5e, 0x6d, 0xa5, 0x5b, 0xf9, 0x0d, 0xd3, 0xb7,
	0xd2, 0x69, 0xab, 0x1d, 0x82, 0x5c, 0xf7, 0x10, 0xe4, 0x3f, 0x1c, 0x82, 0x5c, 0xeb, 0x10, 0xbf,
	0x17, 0x68, 0xe9, 0x81, 0x37, 0x54, 0xc5, 0x7e, 0x4c, 0xb7, 0x02, 0x75, 0x8c, 0xcf, 0xcf, 0xbc,
	0xa1, 0x2a, 0x59, 0x24, 0xbb, 0xc1, 0xb4, 0x6a, 0x7a, 0xd4, 0x07, 0xde, 0xf0, 0x5e, 0x10, 0x8d,
	0x2e, 0x3a, 0x56, 0x90, 0x25, 0x76, 0x87, 0xee, 0x04, 0x61, 0xa0, 0xed, 0x93, 0x9c, 0xe4, 0xed,
	0xbf, 0xed, 0x93, 0x4d, 0x4b, 0xb7, 0x52, 0xe5, 0x6d, 0x07, 0x1a, 0x2a, 0x7f, 0x46, 0x77, 0x17,
	0x7f, 0xd4, 0xde, 0xa5, 0xe4, 0xd4, 0xbf, 0x98, 0x7f, 0x1b, 0xa5, 0xce, 0xec, 0xd1, 0xbe, 0x4b,
	0xd7, 0xbf, 0xf4, 0x06, 0x63, 0x5f, 0xe9, 0x5f, 0xf2, 0x69, 0x27, 0xfc, 0x83, 0x42, 0x0b, 0x97,
	0x9f, 0xd2, 0x37, 0x96, 0xfc, 0xfe, 0xff, 0xdc, 0xb5, 0xf2, 0x0b, 0xa1, 0xeb, 0x8f, 0x02, 0xff,
	0xd1, 0xb1, 0xcd, 0xf4, 0x5e, 0xe5, 0x7e, 0x66, 0x98, 0xe9, 0xdd, 0xca, 0xfd, 0xcc, 0x23, 0xd3,
	0xfb, 0x15, 0x20, 0x2e, 0x10, 0xd5, 0xb1, 0x00, 0x69, 0x00, 0x51, 0x3d, 0x0b, 0x90, 0x26, 0x90,
	0xa4, 0x6b, 0x29, 0x01, 0xd9, 0x07, 0x92, 0xf4, 0x2d, 0x5b, 0x40, 0x0e, 0xe0, 0x7a, 0x48, 0x3a,
	0x17, 0x4b, 0xee, 0x2c, 0x38, 0x83, 0xa9, 0x2d, 0xfb, 0x23, 0xad, 0x99, 0xb1, 0xe4, 0x5d, 0xfd,
	0xa3, 0x33, 0xfe, 0x25, 0x60, 0x8b, 0x43, 0xfb, 0x43, 0xbd, 0xef, 0xb1, 0xe4, 0x9d, 0x64, 0x0f,
	0xf3, 0xda, 0xdc, 0xf5, 0xde, 0xd2, 0x5b, 0x23, 0x4b, 0xee, 0xe9, 0x05, 0x98, 0x56, 0xd6, 0xdb,
	0x9b, 0xb4, 0x78, 0x3c, 0x7b, 0x3c, 0x6f, 0x5b, 0xb4, 0x94, 0x3c, 0x3d, 0x7d, 0x16, 0xb6, 0x1f,
	0x5f, 0x4e, 0x38, 0xba, 0x9a, 0x70, 0xf4, 0x62, 0xc2, 0xd1, 0xcb, 0x09, 0x47, 0xaf, 0x26, 0x1c,
	0xbd, 0x9e, 0x70, 0xfc, 0x3c, 0xe6, 0xf8, 0xa7, 0x98, 0xe3, 0x9f, 0x63, 0x8e, 0x2f, 0x63, 0x8e,
	0xae, 0x62, 0x8e, 0xfe, 0x8c, 0x39, 0x7a, 0x19, 0x73, 0xf4, 0x2a, 0xe6, 0xe8, 0x75, 0xcc, 0xd1,
	0xf3, 0x29, 0x47, 0xdf, 0x4d, 0x39, 0xfa, 0x61, 0xca, 0xd1, 0xd5, 0x94, 0xa3, 0x17, 0x53, 0x8e,
	0x8e, 0x8a, 0xf3, 0x36, 0xd6, 0xfd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xe2, 0x1f, 0x5d, 0x46,
	0x0b, 0x00, 0x00,
}

func (m *BasicScalar) Copy() *BasicScalar { _ = "STUB: not implemented"; return nil }

func (m *BasicScalar) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *RepeatedScalar) Copy() *RepeatedScalar { _ = "STUB: not implemented"; return nil }

func (m *RepeatedScalar) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *RepeatedScalarPacked) Copy() *RepeatedScalarPacked { _ = "STUB: not implemented"; return nil }

func (m *RepeatedScalarPacked) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *ExternalStruct) Copy() *ExternalStruct { _ = "STUB: not implemented"; return nil }

func (m *ExternalStruct) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *RepeatedExternalStruct) Copy() *RepeatedExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func (m *RepeatedExternalStruct) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *NonNullableExternalStruct) Copy() *NonNullableExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func (m *NonNullableExternalStruct) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *RepeatedNonNullableExternalStruct) Copy() *RepeatedNonNullableExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func (m *RepeatedNonNullableExternalStruct) CopyFrom(src interface{}) {
	_ = "STUB: not implemented"
	return
}

func (m *MapStruct) Copy() *MapStruct { _ = "STUB: not implemented"; return nil }

func (m *MapStruct) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (m *OneOf) Copy() *OneOf { _ = "STUB: not implemented"; return nil }

func (m *OneOf) CopyFrom(src interface{}) { _ = "STUB: not implemented"; return }

func (this *BasicScalar) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *RepeatedScalar) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *RepeatedScalarPacked) Equal(that interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func (this *ExternalStruct) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *RepeatedExternalStruct) Equal(that interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func (this *NonNullableExternalStruct) Equal(that interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func (this *RepeatedNonNullableExternalStruct) Equal(that interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func (this *MapStruct) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field1) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field2) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field3) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field4) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field5) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field6) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field7) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field8) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field9) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field10) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *OneOf_Field11) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func NewPopulatedBasicScalar(r randyDeepcopy, easy bool) *BasicScalar {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedRepeatedScalar(r randyDeepcopy, easy bool) *RepeatedScalar {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedRepeatedScalarPacked(r randyDeepcopy, easy bool) *RepeatedScalarPacked {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedExternalStruct(r randyDeepcopy, easy bool) *ExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedRepeatedExternalStruct(r randyDeepcopy, easy bool) *RepeatedExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedNonNullableExternalStruct(r randyDeepcopy, easy bool) *NonNullableExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedRepeatedNonNullableExternalStruct(r randyDeepcopy, easy bool) *RepeatedNonNullableExternalStruct {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedMapStruct(r randyDeepcopy, easy bool) *MapStruct {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf(r randyDeepcopy, easy bool) *OneOf { _ = "STUB: not implemented"; return nil }

func NewPopulatedOneOf_Field1(r randyDeepcopy, easy bool) *OneOf_Field1 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field2(r randyDeepcopy, easy bool) *OneOf_Field2 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field3(r randyDeepcopy, easy bool) *OneOf_Field3 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field4(r randyDeepcopy, easy bool) *OneOf_Field4 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field5(r randyDeepcopy, easy bool) *OneOf_Field5 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field6(r randyDeepcopy, easy bool) *OneOf_Field6 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field7(r randyDeepcopy, easy bool) *OneOf_Field7 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field8(r randyDeepcopy, easy bool) *OneOf_Field8 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field9(r randyDeepcopy, easy bool) *OneOf_Field9 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field10(r randyDeepcopy, easy bool) *OneOf_Field10 {
	_ = "STUB: not implemented"
	return nil
}

func NewPopulatedOneOf_Field11(r randyDeepcopy, easy bool) *OneOf_Field11 {
	_ = "STUB: not implemented"
	return nil
}

type randyDeepcopy interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneDeepcopy(r randyDeepcopy) rune { _ = "STUB: not implemented"; return 0 }

func randStringDeepcopy(r randyDeepcopy) string { _ = "STUB: not implemented"; return "" }

func randUnrecognizedDeepcopy(r randyDeepcopy, maxFieldNumber int) (dAtA []byte) {
	_ = "STUB: not implemented"
	return nil
}

func randFieldDeepcopy(dAtA []byte, r randyDeepcopy, fieldNumber int, wire int) []byte {
	_ = "STUB: not implemented"
	return nil
}

func encodeVarintPopulateDeepcopy(dAtA []byte, v uint64) []byte {
	_ = "STUB: not implemented"
	return nil
}

func (this *BasicScalar) String() string { _ = "STUB: not implemented"; return "" }

func (this *RepeatedScalar) String() string { _ = "STUB: not implemented"; return "" }

func (this *RepeatedScalarPacked) String() string { _ = "STUB: not implemented"; return "" }

func (this *ExternalStruct) String() string { _ = "STUB: not implemented"; return "" }

func (this *RepeatedExternalStruct) String() string { _ = "STUB: not implemented"; return "" }

func (this *NonNullableExternalStruct) String() string { _ = "STUB: not implemented"; return "" }

func (this *RepeatedNonNullableExternalStruct) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (this *MapStruct) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field1) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field2) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field3) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field4) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field5) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field6) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field7) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field8) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field9) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field10) String() string { _ = "STUB: not implemented"; return "" }

func (this *OneOf_Field11) String() string { _ = "STUB: not implemented"; return "" }

func valueToStringDeepcopy(v interface{}) string { _ = "STUB: not implemented"; return "" }
